### ISSUE TITLE
Image perturbation for poisoning - bug

### ISSUE THREAD

**Issue by yusong-tan** [Trusted-AI/adversarial-robustness-toolbox#1006]
**Describe the bug**
https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/37c04d596f42f2a887caaea87431405237c82cd7/art/attacks/poisoning/perturbations/image_perturbations.py#L128-L131

should be (assuming `channels_first` indicates whether not `x` has channel on the first axis):

```
if channels_first:
    data = data.transpose([1, 2, 0])

    width, height, num_channels = data.shape
```

**System information (please complete the following information):**
 - ART version or commit number: ART 1.6.x

**Comment by beat-buesser** [comment]
Hi @yusong-tan Thank you very much for reporting this issue!

@ebubae Could you please take a look?

**Comment by ebubae** [comment]
Thanks for finding this issue @yusong-tan! I've made a PR that addresses this in #1009 so you can track changes there.
