### ISSUE TITLE
Auto Attack on KerasClassifier

### ISSUE THREAD

**Issue by saigontrade88** [Trusted-AI/adversarial-robustness-toolbox#1007]
Hi,

**Question:**
Is there any way to use AutoProjectedGradientDescent attack against KerasClassifier? 

**Exact issue**
I am looking to attack a KerasClassifier model. When looking at the source code, the classifier needs to be of type  TensorFlowClassifier, TensorFlowV2Classifier, PyTorchClassifier
as seen below:
`class AutoProjectedGradientDescent(EvasionAttack):
...
from art.estimators.classification import TensorFlowClassifier, TensorFlowV2Classifier, PyTorchClassifier
....
`
**Observations:**
When I run the below command
`
def build_discriminator():
     model = tf.keras.models.Sequential([
            Conv2D(32, kernel_size=(5, 5), activation='relu', input_shape=(28, 28, 1)),
            Conv2D(64, (5,5), activation='relu'),
            MaxPooling2D(pool_size=(2, 2)),
            Flatten(),
            Dense(1024, activation='relu'),
            Dropout(0.25),
            Dense(11, activation='softmax')], name = 'Detector')
    model.summary()
    image = Input(shape=(28, 28, 1))
    output = model(image)
    return Model(image, output)

classifier = KerasClassifier(model=model, use_logits=False, clip_values=[0,1])
attack_autoPGD = autoPGD(classifier, targeted=False, batch_size=100, loss_type='cross_entropy')`,
I received this error, "The loss type cross entropy is not supported for the provided estimator."

**Comment by beat-buesser** [comment]
Hi @saigontrade88 Thank you very much for using ART!

You can use `KerasClassifier` with `AutoProjectedGradientDescent` but as a special case it does not provide the loss function options and only supports `loss_type=None` for `KerasClassifier` which means `AutoProjectedGradientDescent` will attack the loss function defined by the user as part of the model/estimator.

**Comment by saigontrade88** [comment]
Hi,

Thanks you for your support. 

Is it possible attack a `KerasClassifier` model with `difference_logits_ratio` loss function using `AutoProjectedGradientDescent`? When I run this command,

`attacker_aa = AutoAttack(classifier, norm="inf", eps=0.3, attacks=None, batch_size=100, targeted=False)`

I receive this error, `ValueError: The loss type difference_logits_ratio is not supported for the provided estimator.`

When looking at the Traceback log, it infers that `AutoProjectedGradientDescent` will only attack the `difference_logits_ratio` loss function if the model is defined as `TensorFlowV2Classifier`, and `PyTorchClassifier`.

**Comment by beat-buesser** [comment]
Exactly, that's what I have meant with my previous comment. If you would like to attack a difference logits ratio loss (or any other loss) with `KerasClassifier` you have to implement and add it to your model and set `loss_type=None`.

**Comment by saigontrade88** [comment]
Can you provide instruction on how to add a user-defined loss function to `KerasClassifier`? Thanks.

**Comment by saigontrade88** [comment]
Hi,
I have also found an old but related discussion under this link, 
https://github.com/Trusted-AI/adversarial-robustness-toolbox/issues/427. You suggested to use the `TensorflowV2Classifier`. Is this suggestion still valid? Many thanks.

**Comment by beat-buesser** [comment]
Yes, if you are using `tensorflow.keras` you can use `TensorflowV2Classifier`. To your message before the last, you would need to add the loss to your` keras` model, not `KerasClassifier`.
