### ISSUE TITLE
TensorFlowV2Classifier.layer_names does not return a list of strings

### ISSUE THREAD

**Issue by podschwadt** [Trusted-AI/adversarial-robustness-toolbox#1008]
**Describe the bug**
`TensorFlowV2Classifier.layer_names` does not return a list of strings as, as the type hint states, but rather it returns a list of layer instances. This leads to incorrect behaviour in other functions such as `TensorFlowV2Classifier.get_activations`. Further, this breaks `art.defences.detector.evasion.BinaryActivationDetector`.  The constructor does not work with a string value for the `layer` argument, since it checks if the value is in the list returned by `layer_names`.  An int value saves a reference to the actual layer instance, which breaks later when calling `fit`

**To Reproduce**
```
import tensorflow as tf
from art.estimators.classification import TensorFlowV2Classifier
import numpy as np


model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(1, input_shape=(1,), name='test' ))
model.add(tf.keras.layers.Dense(1))

tf_clf = TensorFlowV2Classifier( model, nb_classes=1, input_shape=(1,))

print(tf_clf.layer_names)
print(tf_clf.get_activations(np.ones(10), layer='test'))
```

**Expected behavior**
The code above should return the activations of  the layer test, but it fails with the error

```
ValueError: Layer name test is not part of the graph.
```

**System information (please complete the following information):**
 - OS: Ubuntu 18.04.5 LTS
 - Python version: 3.7.10
 - art: 1.6.0
 - TensorFlow: 2.4.1

**Comment by beat-buesser** [comment]
Hi @podschwadt Thank you very much for using ART and reporting this issue! I have implemented an improvement in #1011. If you have time, let me please know if it work for you?
