### ISSUE TITLE
Bullseye Polytope Bug When Attacking Multiple Layers of Model

### ISSUE THREAD

**Issue by ng390** [Trusted-AI/adversarial-robustness-toolbox#1045]
**Describe the bug**
When the bullseye polytope attack is used attacking multiple layers of the underlying network (as implemented in PR #1003), only the first poison is changed from the corresponding poison base image. Since the attack needs multiple poisons, it then always fails. This behavior is only exhibited when attacking multiple layers.

**To Reproduce**
1. Open the linked [notebook](https://drive.google.com/file/d/17C9XXE2JVmpKxrAS6C-wwbOZq996BKAB/view?usp=sharing) (a MWE with a few cells changed from the original Bullseye polytope notebook). Standard CIFAR-10 images result in the same problem, but it is much easier to visually see when solid color images are used as in the example.
2. Run all cells
3. Compare poison base images to final poisons

**Expected behavior**
The final poisons should all differ from the base poisons, rather than just the first poison. If cell 10 is changed to attack only one layer, all final poisons do differ from the base poisons.

**Screenshots**
![poison_bases_and_fnl_poisons](https://user-images.githubusercontent.com/6437791/114561871-fad1f780-9c3b-11eb-8a3d-38e33481cd92.png)

**Notebook**
The MWE notebook reproducing the bug is available at the following [Google Drive link](https://drive.google.com/file/d/17C9XXE2JVmpKxrAS6C-wwbOZq996BKAB/view?usp=sharing)

**System information (please complete the following information):**
 - OS: Ubuntu 18.04.4 LTS
 - Python version: 3.7.9
 - ART version or commit number: dev_1.6.1 / 09942d2dda38f53898bc2e878ddbf99ec67037c9
 - TensorFlow / Keras / PyTorch / MXNet version: torch 1.7.0

**Comment by beat-buesser** [comment]
Hi @ng390 Thank you very much for reporting this issue, we'll investigate it as soon as possible.
