### ISSUE TITLE
Outputting alternative transcripts

### ISSUE THREAD

**Issue by scfang** [Trusted-AI/adversarial-robustness-toolbox#1059]
Greetings,

I am working with the DeepSpeech Pytorch wrapper to generate adversarial examples. I was wondering if the the classifier has a way of retrieving alternative transcripts in addition to the most probable transcript. 

Regards

**Comment by minhitbk** [comment]
@scfang: You can use the parameter `decoder_type` to use beam search for other alternative transcripts. Other params like `beam_width`, `cutoff_prob`, etc. also help.

**Comment by scfang** [comment]
@minhitbk thank you for your answer. I managed to retrieve the alternative text.

I have another question though, what would be the right way to retrieve the probability/confidence level of a transcript as a whole? I see in the documentation that using `estimator.predict()` with `transcription_output=False` returns an output of probability of characters with shape (nb_samples, seq_length, nb_classes), but I am not sure how to translate this into overall transcript probability/confidence.

Regards

**Comment by minhitbk** [comment]
@scfang : This depends on the language model that you are going to use. Currently there are only 2 supported by DeepSpeech, namely the greedy search and the beam search. Both are also supported by the art estimator. There maybe other strategies available if you want to make a further investigation.
