### ISSUE TITLE
I can't modify the epoch value, it seems that the default epoch for adversarial training is 20?

### ISSUE THREAD

**Issue by LxyoryxL** [Trusted-AI/adversarial-robustness-toolbox#1085]
question:
- [ ] When I am using the function `AdversarialTrainer`, I cannot modify the `epoch` value. It seems that the default adversarial training epoch=20?

here is my code....
```
attacker_rob=FastGradientMethod(classifier,eps=0.5,eps_step=0.01,batch_size=60)
trainer_rob=AdversarialTrainer(robust_classifier,attacker_rob,ratio=0.5)
trainer_rob.fit(x_train, y_train,nb_epoches=40,kwargs={ "verbose": True})
```
```
Precompute adv samples: 100%|██████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15252.01it/s]
Adversarial training epochs: 100%|██████████████████████████████████████████████████| 20/20 [00:24<00:00,  1.22s/it]
```

**Comment by beat-buesser** [comment]
Hi @LxyoryxL The argument name in `trainer_rob.fit` should be `nb_epochs` instead of `nb_epoches`.

**Comment by LxyoryxL** [comment]
> Hi @LxyoryxL The argument name in `trainer_rob.fit` should be `nb_epochs` instead of `nb_epoches`.

oh, The code is now working properly. thanks a lot!!
