### ISSUE TITLE
Conda/conda-forge installation support

### ISSUE THREAD

**Issue by TS-Lee** [Trusted-AI/adversarial-robustness-toolbox#1086]
**Is your feature request related to a problem? Please describe.**
Currently, the installation of ART is either through `pip` or from source.

**Describe the solution you'd like**
It would be great we can use conda to install it. For example,
`conda install art`

**Comment by TS-Lee** [comment]
Just realized it is available on conda-forge. So, the following is possible.
`conda install -c conda-forge adversarial-robustness-toolbox`

**Comment by beat-buesser** [comment]
Hi @TS-Lee Thank you very much for this feature request! I think this will be very useful.

**Comment by beat-buesser** [comment]
Closing this issue after discussing with @TS-Lee , `conda install -c conda-forge adversarial-robustness-toolbox` shared above is the preferred method for `conda`.
