### ISSUE TITLE
How to launch HopSkipJump or Square example generation on GPU?

### ISSUE THREAD

**Issue by Code-Ranger** [Trusted-AI/adversarial-robustness-toolbox#1088]
The provided example code of Hop Skip Jump adverarial exmaple generation uses only CPU, which is very slow. Can I use GPU to speed up the generation? How should I to write the code with GPU?

Thanks in advance!

**Comment by beat-buesser** [comment]
Hi @Code-Ranger Nice to hear from you. I don't think that's correct, the example runs with GPU if one is available. Could you please provide more details how you are running the example and links to related code?

**Comment by Code-Ranger** [comment]
Hi @beat-buesser 
Thanks very much for helping.
The code used for Hop Skip Jump adv generation is basically from https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/notebooks/classifier_blackbox.ipynb
```
classifier = BlackBoxClassifier(predict_to_onehot, image_array[0].shape, 1000, clip_values=(0, 255))

attack = HopSkipJump(classifier=classifier, targeted=False, max_iter=0, max_eval=1000, init_eval=10)
iter_step = 50
x_adv = None
for i in range(5):
    x_adv = attack.generate(x=image_array, x_adv_init=x_adv)

```
Where predict_to_onehot() is encapsulating PyTorch ResNet152 as image classifier.
How should I make the code working on GPU?

**Comment by beat-buesser** [comment]
Hi @Code-Ranger 

Ok, I see. Would you be able to share `predict_to_onehot` and the definition of the model? I suspect that you are using a pytorch model but might not have moved it to the device before making predictions.

**Comment by beat-buesser** [comment]
Hi @Code-Ranger Yes, ART fully supports GPUs, and some attacks are using CPUs. Why are you using `BlackBoxClassifier`?

**Comment by Code-Ranger** [comment]
Hi @beat-buesser 
Because I am working on black box scenario, the target model will be the remote image classification service. Now the local ResNet model has been used only for testing reason temporarily.
Can black-box adv methods like HopSkipJump, Square attacking take advantage of GPU?

THX

**Comment by Code-Ranger** [comment]
Hi @beat-buesser,

The HopSkipJump adv generation code is as following,
‘’‘
classifier = BlackBoxClassifier(predict_to_onehot, image_array[0].shape, 1000, clip_values=(0, 255))

attack = HopSkipJump(classifier=classifier, targeted=False, max_iter=0, max_eval=1000, init_eval=10)
iter_step = 50
x_adv = None
for i in range(5):
    x_adv = attack.generate(x=image_array, x_adv_init=x_adv)
’‘’
And I am using ART V1.6.1

**Comment by beat-buesser** [comment]
Hi @Code-Ranger 

I think your code looks good. How many images are in `image_array`? Do keep a GPU busy you would need more than a single image. `HopSkipJump` is supporting mini-batches since ART 1.6.1.

**Comment by Code-Ranger** [comment]
Hi @beat-buesser 
Currently there is only one image in image_array. I will try to using mini-batch.
So the HopSkipJump can automatically use GPU if there is one? I don't have to explicitly enable GPU.

THX

**Comment by beat-buesser** [comment]
Hi @Code-Ranger 

Yes, if a GPU is available, and in the case of ART's PyTorch estimators the device has been set to `gpu`,  the models will be evaluated on GPUs. In case of `BlackBoxClassifier` it is the user's responsibility to setup the model on GPU, as discussed above. Some steps of tools like `HopSkipJump` still require some processing on CPU in their current implementation.

**Comment by Code-Ranger** [comment]
Hi @beat-buesser 

Just for clarification, when you say "ART's PyTorch estimators", you mean the image classifier (predict_to_onehot() in my case)?
Because after I set the predict_to_onehot() on GPU, the HopSkipJump is still pretty slow, and my GPU usage is only 0~15%, which is strange.
THX

**Comment by beat-buesser** [comment]
Hi @Code-Ranger 

I mean the ART's estimators in `art.estimators` for PyTorch which provide argument `device_type`, which automates the steps you had to do in `predict_to_onehot` to move model and data to the GPU.

I think one reason for your low utilisation of the GPU is that you are only using 1 image, which means `batch_size=1`. Maybe try using larger batches to achieve better utilisation. You also could investigate the number of iterations for the various steps of `HopSkipJump`, probably you can find good adversarial examples with less iterations.
