### ISSUE TITLE
random_sphere function 

### ISSUE THREAD

**Issue by jinglin80** [Trusted-AI/adversarial-robustness-toolbox#1093]
The random_sphere function is defined https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/1078e811688ce9f5f07139c4f6d305949207fa4e/art/utils.py#L359. 

On line 396, why is the lower incomplete gamma function used here? 
On line 401, what happens if someone provides an np.array of shape (nb_points, ) for the radius?

Thank you very much for the clarification,
Jing

**Comment by beat-buesser** [comment]
Hi @jinglin80 Thank you very much for using ART! We'll try to answer your question as soon as possible.

**Comment by beat-buesser** [comment]
Hi @jinglin80 What is the application of your example?
