### ISSUE TITLE
How to retrieve number of applied perturbations

### ISSUE THREAD

**Issue by le000043** [Trusted-AI/adversarial-robustness-toolbox#1103]
Hello, thank you for creating such great software. I want to know how to retrieve the number of perturbations of the Fast gradient method or any evasion attacks in order to measure the robustness of models.
Thanks :D

**Comment by beat-buesser** [comment]
Hi @le000043 Thank you very much!

You would have to calculate the properties of the obtained perturbations as difference between the adversarial examples and the original samples, `numpy.linalg.norm` it often useful.

**Comment by le000043** [comment]
Thank you for your response. Below is my code, can you double-check if I got it right?
`for idx in range(x_test_adv.shape[0]):
  diff = x_test[idx] - x_test_adv[idx]
  l2_distances.append(np.linalg.norm(diff))`
