### ISSUE TITLE
success rate of AutoProjectedGradientDescent

### ISSUE THREAD

**Issue by le000043** [Trusted-AI/adversarial-robustness-toolbox#1104]
how to get the success rate of AutoProjectedGradientDescent

Thanks :D

**Comment by beat-buesser** [comment]
Hi @le000043 

You have to calculate the success rate by comparing predicted and true labels.

**Comment by le000043** [comment]
Thank you for your response. I believe the success rate here is the relative number of images for which an adversarial example can be generated
