### ISSUE TITLE
Bug/Typo in HopSkipJump Attack Notebook

### ISSUE THREAD

**Issue by SecantZhang** [Trusted-AI/adversarial-robustness-toolbox#1111]
**Describe the bug**
In the attack_hopskipjump.ipynb, the x parameter of the attack generate method should be the array of the initial images instead of the target images. 

**To Reproduce**
1. Go to notebooks/attack_hopskipijump.ipynb file. 
2. Navigate to code cell 4-7, the code line that calls the attack.generate() method to generate the adversarial sample. 
3. The first parameter x should be `x=np.array([init_image])` instead of `x=np.array([target_image])` according to the comment of the hopskipjump attack in this repo. 
4. Reference: `art/attacks/evasion/hop_skip_jump.py`, line `113`: ":param x: An array with the original inputs to be attacked."

**To Fix**
Change all 
`x_adv = attack.generate(x=np.array([target_image]), y=to_categorical([866], 1000), x_adv_init=x_adv, resume=True)`
to 
`x_adv = attack.generate(x=np.array([init_image]), y=to_categorical([866], 1000), x_adv_init=x_adv, resume=True)`
and re-run the notebook.

**Comment by beat-buesser** [comment]
Hi @SecantZhang

Thank you very much for using ART and raising this issue! I think the original author referred with `target_image` to the image that should be "targeted" and for which an adversarial example should be generated. I see that this variable name is somewhat in conflict with the `targeted` option of the attack. I would propose we switch
```
init_image_name = 'koala.jpg'
target_image_name = 'tractor.jpg'
```
and exchange all `init_image_name` and `target_image_name` with each other. That way we can keep `koala` the attacked class and `tractor` be the targeted class of the targeted attack.

Would you be interested in opening a pull request?

**Comment by SecantZhang** [comment]
Sure, I'd love to. Thanks for the reply!

**Comment by beat-buesser** [comment]
That's great, thank you! You can target branch `main` with the pull request.
