### ISSUE TITLE
carlini.py

### ISSUE THREAD

**Issue by jinglin80** [Trusted-AI/adversarial-robustness-toolbox#1117]
TO WHOM IT MAY CONCERN:

I have a question related to https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/art/attacks/evasion/carlini.py.

Line 471:  c_current1 = (c_current - c_lower_bound)[~overall_attack_success & ~c_double]

An element in ~overall_attack_success & ~c_double returns True when the corresponding element in overall_attack_success returns False and the corresponding element in c_double returns False.

However, line 465 indicates that the element in c_double returns False when the corresponding overall_attack_success returns True only.

Line 465: c_double[overall_attack_success] = False

In this case, should we delete lines 471-472 since ~overall_attack_success & ~c_double is always false. 

Thank you very much for the clarification,
Jing

**Comment by mathsinn** [comment]
Thank you @jinglin80 for the close inspection of the code and your question.

Note that `c_double` gets continuously updated in the loop starting in line 273 and might already be False from a previous iteration. Therefore the corresponding element in `overall_attack_success` being True is a sufficient but not a necessary condition for the element in `c_double` being False after the execution of line 465.

Does that make sense?

**Comment by jinglin80** [comment]
Thank you @mathsinn for the rapid response. It still does not make sense as overall_attack_success gets continuously updated in the loop as well (line 455). 

If an element in c_double already be False from a previous iteration, then the corresponding element in overall_attack_success is also already be False. 

Line 455: overall_attack_success = overall_attack_success | attack_success

**Comment by mathsinn** [comment]
@jinglin80 Note the difference in scope: `c_double` is defined outside the `bss` loop (l.267), while `overall_attack_success` is defined inside (l.297). So you could have an element in `c_double` having been set to False in a previous `bss` iteration, while in the current `bss` iteration the corresponding element in `overall_attack_success` is False, too.
