### ISSUE TITLE
Enable using ground-truth y for ART object detectors' loss_gradient()

### ISSUE THREAD

**Issue by lcadalzo** [Trusted-AI/adversarial-robustness-toolbox#1119]
**Is your feature request related to a problem? Please describe.**
When computing `loss_gradient(x, y)` for ART object detectors, it's required that `y` contains a `"scores"` key. This will be true when using the benign prediction for `y` but not when using the actual ground-truth `y` (since ground-truth of course has no notion of a score).

**Describe the solution you'd like**
The ability to input ground-truth labels for `y` when calling `loss_gradient(x, y)` for ART object detectors.

**Additional context**
ART 1.6.1. This applies to both PyTorch and TF F-RCNN's.

**Comment by beat-buesser** [comment]
Hi @lcadalzo Thank you very much for reporting this issue! We'll fix it as soon as possible with ART 1.6.2.
