### ISSUE TITLE
Attack Pytorch model

### ISSUE THREAD

**Issue by le000043** [Trusted-AI/adversarial-robustness-toolbox#1121]
Hello,
Thank you for creating and maintaining this great framework. Is it possible that I can use some of the attacks from ART to attack Pytorch models such as ResNet20 implemented in Pytorch?
Thanks

**Comment by SecantZhang** [comment]
As long as your ResNet20 model is in the torch.nn.module type, I think you can pass it to your PytorchClassifier to perform the attack.

**Comment by le000043** [comment]
Any test examples of attacking Pytorch models that you can point me too ?
Thanks :D

**Comment by SecantZhang** [comment]
One pytorch example: https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/examples/get_started_pytorch.py there are more attack examples in the notebook folder, however, I think most of them are in Tensorflow and you need to modify the code a bit to fit the pytorch.

**Comment by le000043** [comment]
sweet, thanks for your help!
