### ISSUE TITLE
Got error prompt while introducing mini-batch into HopSkipJump 

### ISSUE THREAD

**Issue by cyber-ranger** [Trusted-AI/adversarial-robustness-toolbox#1130]
Hello, 

I am working on utilizing mini-batch in adv generation by HopSkipJump for taking advantage of GPU, as recommened in issue #1088.

After loading multiple images into an numpy array with shape of (8, 256, 256, 3)
```
    for name in image_names:
        image = Image.open(os.path.join(image_path, name))
        image = image.convert('RGB')
        image = image.resize((256, 256), Image.ANTIALIAS)
        if 'image_array' not in vars():
            image_array = np.array([np.array(image, dtype='float32')])
        else:
            image_array = np.append(image_array, np.array([np.array(image, dtype='float32')]), axis=0)
```
I utilize the similar code for HopSkipJump adv generation as introduced in  https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/notebooks/classifier_blackbox.ipynb
```
        classifier = BlackBoxClassifier(predicts_to_onehot, image_array[0].shape, 1000, clip_values=(0, 255))

        # Generate HopSkipJump attack against black box classifier
        attack = HopSkipJump(classifier=classifier, targeted=False, max_iter=0, max_eval=1000, init_eval=10)
        iter_step = 50
        x_adv = None
        for i in range(5):
            x_adv = attack.generate(x=image_array, x_adv_init=x_adv)

            attack.max_iter = iter_step
            print("Total number of predict() has been called: ", ADV_COUNTER)
```

At the same time, implementing predict_one_hot() as following (ResNet model has already been put on the same GPU)

```
def classify(img: Image) -> torch.tensor:
    img_t = preprocess(img).to(DEVICE)
    batch_t = torch.unsqueeze(img_t, 0)
    resnet.eval()
    output = resnet(batch_t)
    return output

def logits_to_onehot(y: np.array) -> np.array:
    _, index = torch.max(torch.from_numpy(y), 1)
    one_hot = np.zeros(y.shape[1])
    one_hot[index] = 1
    return one_hot

def predict(x: np.array) -> np.array:
    img = Image.fromarray(x.astype(np.uint8))
    logits = classify(img)
    return logits.cpu().detach().numpy()

def predicts_to_onehot(x_array: np.array) -> np.array:
    one_hot = list()
    for x in x_array:
        logits = predict(x)
        one_hot.append(logits_to_onehot(x))
    one_hot_array = np.array(one_hot)
    return one_hot_array
```

Unfortunately, I got error message as following. So could you please give me some hints on how to solve it? Thanks very much!

Traceback (most recent call last):
  File "/home/ranger/.pycharm_helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/ranger/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)python-BaseException

  File "/home/ranger/lizhu/src/query_distance/sample/adv/generate_batches.py", line 63, in <module>
    batch_adv_generation.generate_adv_batch(args.method, args.folder, image_batch, classes, folders, args.debug)
  File "/home/ranger/lizhu/src/query_distance/sample/adv/batch_adv_generation.py", line 177, in generate_adv_batch
    x_adv = attack.generate(x=image_array, x_adv_init=x_adv)
  File "/home/ranger/anaconda3/lib/python3.8/site-packages/art/attacks/attack.py", line 75, in replacement_function
    return fdict[func_name](self, *args, **kwargs)
  File "/home/ranger/anaconda3/lib/python3.8/site-packages/art/attacks/evasion/hop_skip_jump.py", line 154, in generate
    preds = np.argmax(self.estimator.predict(x, batch_size=self.batch_size), axis=1)
  File "/home/ranger/anaconda3/lib/python3.8/site-packages/art/estimators/classification/classifier.py", line 71, in replacement_function
    return fdict[func_name](self, *args, **kwargs)
  File "/home/ranger/anaconda3/lib/python3.8/site-packages/art/estimators/classification/blackbox.py", line 123, in predict
    predictions[begin:end] = self._predict_fn(x_preprocessed[begin:end])
ValueError: could not broadcast input array from shape (8,256) into shape (8,1000)

**Comment by beat-buesser** [comment]
Hi @cyber-ranger Thank you for using ART! Could you please check the shape of the output of method `predicts_to_onehot`?

**Comment by cyber-ranger** [comment]
Hi @beat-buesser ，

Thanks for hints. The error is due to I have mistakenly passed the image array instead of logits to logits_to_onehot() in predicts_one_hot().

But after I fixed the bug. I found out that after predict_one_hot() has been called on processing mini-batch images (e.g. the shape of x_array is (8, 256, 256, 3) for one time, it has been called many times to processing only one page (the shape of  inputing x_array is (1, 256, 256, 3)) after another. 
Is this right? Shouldn't the algorithm processing all images in batch, not one by one?

Thanks again.

**Comment by beat-buesser** [comment]
Hi @cyber-ranger 

Great! Yes, `HopSkipJump` should work with mini-batches larger than 1 since ART 1.6.1. Which version of ART are you using?

**Comment by cyber-ranger** [comment]
Hi @beat-buesser ,

I am using version 1.6.1.
As I described in above, the adv generation has not been actually improved since HopSkipJump is not always processing the images in batch. So just checking with you if there is anything wrong here.

THX

**Comment by beat-buesser** [comment]
Hi @cyber-ranger 

I think `HopSkipJump` is doing the batching correctly. Your prediction method is applied to batches but inside of your method  the model is evaluated on single images by loping over the mini-batch, e.g. in `predicts_to_onehot`:
```
for x in x_array:
    logits = predict(x)
    one_hot.append(logits_to_onehot(x))
```

Instead, try something like 
```
logits = predict(x_array)
one_hot = logits_to_onehot(logits)
```

**Comment by cyber-ranger** [comment]
Hello @beat-buesser ，

Thanks for helping.
I have modified the predict() to directly handling mini-batch as following,
```
def predict(x: np.array) -> np.array:
    tensor_batch = torch.empty(0).cuda(0)
    for idx, _ in enumerate(x):
        img = Image.fromarray(x[idx].astype(np.uint8))
        img_tensor = preprocess(img).to(DEVICE)
        tensor_batch = torch.cat((tensor_batch, torch.unsqueeze(img_tensor, 0)), dim=0)
    resnet.eval()
    logits = resnet(tensor_batch)
    return logits.cpu().detach().numpy()
```
But still found (like mentioned above) after predict_one_hot() has been called on processing mini-batch of images (the shape of x_array is (8, 256, 256, 3) for one time, it has been called many times to processing only one page (the shape of inputing x_array is (1, 256, 256, 3)) after another.
Just wondering if it is the way the algorithm should be?

**Comment by beat-buesser** [comment]
Hi @cyber-ranger Could you please describe where and how do you observe the shape `(1, 256, 256, 3)`?

**Comment by cyber-ranger** [comment]
Hi @beat-buesser ，

My code is as above. 
I preapare a mini-batch with 8 images in image_array, and set a breakpoint in predicts_to_onehot(). So the first time that predict_one_hot() has been called, the shape inputting parameter x_array is (8, 256, 256, 3). Then I traced the process to hop_skip_jump.py, line 199, following code call predict_one_hot() with input shape (1, 256, 256, 3)
```
                x_adv[ind] = self._perturb(
                    x=val,
                    y=-1,
                    y_p=preds[ind],
                    init_pred=init_preds[ind],
                    adv_init=x_adv_init[ind],
                    mask=mask[ind],
                    clip_min=clip_min,
                    clip_max=clip_max,
                )
```
Since this code is in the loop 
`
for ind, val in enumerate(tqdm(x_adv, desc="HopSkipJump", disable=not self.verbose)):
`
It looks like only one image has been used for predict.

**Comment by beat-buesser** [comment]
Hi @cyber-ranger That's correct, `HopSkipJump` attacks one image at a time, but for each attacked image it evaluates `num_eval` random samples around that attacked image as mini-batch of size `batch_size`. `num_eval` increasing as function of iteration and can become quite large, so large that processing all images with their randomly perturbed versions at once could likely run out of memory.  This evaluation happens in line 634 on `dev_1.7.0` where `samples` contains `num_eval` randomly perturbed samples during the main compute call in line 599.
