### ISSUE TITLE
Literature Basis for the MembershipInference Blackbox Attack?

### ISSUE THREAD

**Issue by blauertee** [Trusted-AI/adversarial-robustness-toolbox#1131]
Hey,

I wasn't able to find any paper or linked literature that describes what is actually implemented in the MembershipInferenceBlackboxAttack. Where does this implementation come from? Can anyone give me some source for that? 

Thank's in advance,

Jakob

**Comment by beat-buesser** [comment]
Hi @blauertee I'll check with the author and come back soon.

**Comment by beat-buesser** [comment]
Hi @blauertee I have talked with @abigailgold, the attack is based on [Shokri et al](https://arxiv.org/abs/1610.05820) with a few additions and extensions. Let us know if you have further questions!

**Comment by blauertee** [comment]
Thanks! I know that paper, but I thought that describes MIAs on k shadow models. The Blackbox MIA implemented in art only allows to train an attack model on a single shadow model or the target model directly right? And if so why is that?

**Comment by abigailgold** [comment]
Hi @blauertee, the Blackbox MIA in ART can receive any train and test datasets in its fit() method. Those could be derived in a number of ways, including using shadow models. But you are correct that this is assumed to be done external to the attack implementation.
BTW - it may be possible to use ART's extraction attack implementations to create such shadow models.
