### ISSUE TITLE
Test fixture for functional Keras image classifier never used

### ISSUE THREAD

**Issue by hesseltuinhof** [Trusted-AI/adversarial-robustness-toolbox#1143]
In line https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/d2d10d8f2041a2e7c59125a525b9ea31c018c740/conftest.py#L521 `functional` will always be `False` because the outer condition of this block in line https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/d2d10d8f2041a2e7c59125a525b9ea31c018c740/conftest.py#L520 can only be true if `functional` is `False`.

I'm not sure what are the consequences of this, but I just noticed it. Probably necessary to further investigate unintended consequences.

**System information (please complete the following information):**

 - ART 1.6.0

**Comment by beat-buesser** [comment]
Hi @hesseltuinhof Thank you very much for noticing and reporting this issue!
