### ISSUE TITLE
Clever score parameters

### ISSUE THREAD

**Issue by kfarivar** [Trusted-AI/adversarial-robustness-toolbox#1144]
Hello

I have read the Clever paper mentioned in the docs. I couldn't find any mention of a `pool_factor` parameter or a `c_init`. 
The docs are not clear what they are. My questions are :

1. what is the difference between `pool_factor` and `batch_size` to me it seems eventually the number of samples ends up being their multiplication so why was `pool_factor` introduced and how does it affect the computation ?

2. what is c_init (initialization of Weibull distribution) , is this related to solving the MLE ? 

thanks.

**Comment by beat-buesser** [comment]
Hi @kfarivar Thank you very much for your interest in ART!

I have not implemented the CLEVER metric myself, I think 

1. `batch_size` corresponds to `N_b` and `pool_factor` corresponds to `N_s` in the paper (e.g. Algorithm 1). The `pool_factor` lets you define how many random samples contribute to a single max-gradient-norm value for the Weilbull distribution. The `batch_size` defines how many max-gradient-norm values are being calculated before fitting the Weibull distribution on them.
2. `c_init` corresponds to your initial guess of parameter `c` in the first equasion in section Notes on https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.weibull_min.html

**Comment by kfarivar** [comment]
Thanks for the quick reply,

1. I am still confused, since there is also a parameter called `nb_batches` which in the code seems to be doing the job of `N_b`.
[code](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/d2d10d8f2041a2e7c59125a525b9ea31c018c740/art/metrics/metrics.py#L358)
So to summarize the paper has only 2 parameters related to samples `N_b` and `N_s` but here we have 3,  `pool_factor`, `batch_size` and `nb_batches`.

2. Is adjusting `c_init` necessary or should I leave it as 1 ? I have no intuition how to adjust this parameter.

**Comment by kfarivar** [comment]
thanks, so my take is that in the paper's pseudocode Algorithm 1 at each iteration of the inner loop a new point is sampled. But in the `clever_t` we first make a pool of random points and in the same loop sample from this pool instead of creating a new sample. I guess the later method was faster.

**Comment by kfarivar** [comment]
So I checked the [original implementation](https://github.com/IBM/CLEVER-Robustness-Score/blob/b25f9c94279ada813c4e6a33a0c330e2bc2273c0/clever.py) of clever and there seems to be some differences. For instance the original heavily uses multiprocessing. For instance to find the best c_init or to calculate the score on multiple samples. These all contribute to a faster code and more accurate results. hope this will be improved in the future versions of this library.

**Comment by beat-buesser** [comment]
Hi @kfarivar Thank you very much for the updates. Are you planning to implement these improvements? We would be happy to provide support.
