### ISSUE TITLE
Implement EoT for rotation in object detection

### ISSUE THREAD

**Issue by beat-buesser** [Trusted-AI/adversarial-robustness-toolbox#1145]
We would like to implement support for Expectation over Transformation (EoT) of rotation (in steps of 90 degrees) in object detection applications in PyTorch and maybe TensorFlow.

**Comment by igor-barinov** [comment]
Hi, I am interested in this issue.

**Comment by beat-buesser** [comment]
Hi @igor-barinov Thank you very much for your interest in contributing to ART!
