### ISSUE TITLE
auto_projected_gradient_descent.py 

### ISSUE THREAD

**Issue by jinglin80** [Trusted-AI/adversarial-robustness-toolbox#1150]
TO WHOM IT MAY CONCERN:

I have a question related to https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/art/attacks/evasion/auto_projected_gradient_descent.py

Lines 522-526: 

```
if (not self.targeted and f_k_p_1 > self.f_max) or (self.targeted and f_k_p_1 < self.f_max):
      self.count_condition_1 += 1
      self.x_max = x_k_p_1
      self.x_max_m_1 = x_k
      self.f_max = f_k_p_1
```
May I know why to update f_max when (self.targeted and f_k_p_1 < self.f_max)?

**Comment by beat-buesser** [comment]
Hi @jinglin80 Thank you very much for using ART! This condition is for the targeted attack where the goal is to find perturbations that decrease the loss towards the targeted label.

**Comment by jinglin80** [comment]
Hi @beat-buesser Thank you for the clarification! One more question about the auto_projected_gradient_descent.py.

Lines 518-520: 

```
if f_k_p_1 == 0.0:
       x_k = x_k_p_1.copy()
       break
```
May I know why break when the loss (f_k_p_1) is zero?

**Comment by beat-buesser** [comment]
Hi @jinglin80 The condition and break in lines 518-520 are checking if the loss has become numerically zero, if it has become numerically zero it stops the attack to prevent  iterations based on numerical noise in the loss value `f_k_p_1`.
