### ISSUE TITLE
_apply_preprocessing

### ISSUE THREAD

**Issue by le000043** [Trusted-AI/adversarial-robustness-toolbox#1151]
Hello, I am trying to attack my Keras model. Currently, I am using TensorflowV2Classifer to wrap my Keras model. What is the difference between using TensorflowV2Classifer and KerasClassifier. Also, I don't specify any preprocessing defense, what is the default behavior of the _apply_preprocessing function? If any, how does that affect the robustness of the Keras model?
Thanks

**Comment by beat-buesser** [comment]
Hi @le000043 `TensorflowV2Classifer` is used for all TensorFlow v2 models in eager execution mode whereas `KerasClassifier` is used for `keras` and `tf.keras` models with eager execution disabled. If you don't specify any preprocessing defences then no preprocessing defences will be applied. Their effect on robustness is something that you will have to investigate for your experiment.
