### ISSUE TITLE
[MembershipInferenceBlackBox] Why does the attack shuffles the inputed data?

### ISSUE THREAD

**Issue by marisanest** [Trusted-AI/adversarial-robustness-toolbox#1165]
Hey, 

I recently used the [MembershipInferenceBlackBox](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/art/attacks/inference/membership_inference/black_box.py) attack to test my target model. I noticed that if I input data into the `infer()` method, the data points are shuffled before the attack infers the membership status (See: [black_box.py#L273](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/24a616befec9d35ba053d16d4a6ac6cfc573039c/art/attacks/inference/membership_inference/black_box.py#L273)). As a result, the returned values can not be matched to their corresponding data points anymore. 

Is this behaviour intended? And if so, it would be great to hear an opinion on why this is intended behaviour.

Thanks!

**Comment by beat-buesser** [comment]
Hi @marisanest Thank you very much for your question and checking the code of ART! We'll be back with an answer as soon as possible.

**Comment by abigailgold** [comment]
Actually, you're right, this shouldn't happen in infer. Thanks @marisanest, I will fix it as soon as possible.

**Comment by marisanest** [comment]
Greate, thanks for your quick reply! Let me know if I can help in any way. Otherwise, looking forward to ART 1.7.1 :+1:
