### ISSUE TITLE
Documentation for the art.attacks and art.metrics are missing

### ISSUE THREAD

**Issue by AkhileshAdithya** [Trusted-AI/adversarial-robustness-toolbox#1168]
**Describe the bug**
Documentation for the art.attacks.evasion and art.metrics are missing

**To Reproduce**
1. Go to 'https://adversarial-robustness-toolbox.readthedocs.io/en/stable/modules/metrics.html'
2. Go to 'https://adversarial-robustness-toolbox.readthedocs.io/en/stable/modules/attacks/evasion.html'

**Expected behavior**
Expecting to see the description of attack and the paper it references to. More parts like art.evaluations are also down and the above are not an exhaustive list of the missing documentation.

**Screenshots**
![Screenshot from 2021-06-17 01-05-49](https://user-images.githubusercontent.com/38578610/122281907-6ec4a080-cf08-11eb-83df-6fdddc776459.png)

**System information (please complete the following information):**
[should'nt matter]
 - OS - Linux 
 - Broeser - firefox
 - Python version
 - ART version or commit number
 - TensorFlow / Keras / PyTorch / MXNet version

**Comment by beat-buesser** [comment]
Hi @AkhileshAdithya Thank you very much for letting us know! We'll take a look as soon as possible.

**Comment by beat-buesser** [comment]
@AkhileshAdithya The documentation should now be back correctly.

**Comment by AkhileshAdithya** [comment]
Thanks :+1:
