### ISSUE TITLE
feature_adversaries_numpy.py

### ISSUE THREAD

**Issue by jinglin80** [Trusted-AI/adversarial-robustness-toolbox#1185]
Both [feature_adversaries_tensorflow.py](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/art/attacks/evasion/feature_adversaries/feature_adversaries_tensorflow.py) and [feature_adversaries_pytorch.py](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/art/attacks/evasion/feature_adversaries/feature_adversaries_pytorch.py) support layer: Union[int, str, Tuple[int, ...], Tuple[str, ...]] = -1. However, [feature_adversaries_numpy.py](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/art/attacks/evasion/feature_adversaries/feature_adversaries_numpy.py) only supports type(layer) = int. Please update feature_adversaries_numpy.py so that layer: Union[int, str, Tuple[int, ...], Tuple[str, ...]] = -1.

Thank you!

**Comment by beat-buesser** [comment]
Hi @jinglin80 Thank you very much for using ART and this feature proposal. I think this feature would be very useful.

Would you be interested in implementing it? We would be happy to help and provide support.

**Comment by jinglin80** [comment]
Yes, I am interested!

**Comment by beat-buesser** [comment]
Hi @jinglin80 That's amazing! I think this would be a nice feature for the upcoming ART 1.8 release on branch `dev_1.8.0`. Please let us know if you have questions on how to proceed, we are very happy to provide help and support!

**Comment by jinglin80** [comment]
Hi @beat-buesser, I have the code ready, but it has not been tested yet. May I know how to proceed?

**Comment by beat-buesser** [comment]
Hi @jinglin80 That's great! The next step would be to open a pull request (in tab `Pull requests" click on green button "New pull request") and select branches from your forked repository to the upstream ART repository targeting branch `dev_1.8.0`.

**Comment by beat-buesser** [comment]
Hi @jinglin80 Thank you very much for your pull request. Your pull request #1207 does not contain your code additions because it is from the official ART repo. Instead, you need to open a new pull request from your forked repo at https://github.com/jinglin80/adversarial-robustness-toolbox from the branch where you have pushed your new commits to the branch `dev_1.8.0` of the upstream repo.
