### ISSUE TITLE
Spectral Signature Defense Bug When Testing on CNN trained on CIFAR10

### ISSUE THREAD

**Issue by Yi-Zoey** [Trusted-AI/adversarial-robustness-toolbox#1188]
**Describe the bug**
When using the spectral signature defense to identify poisoned images, the defense rejects 100% of the clean images. The defense treats all images as poisoned images regardless of the value of `expected_pp_poison`.

**To Reproduce**
1. Train a simple CNN (`KerasClassifier`) on the CIFAR10 dataset.
2. Define the defense as `defence = SpectralSignatureDefense(model, x_train, y_train)`.
3. Call `report, is_clean_lst = defence.detect_poison()` and compute the total clean points as `np.sum(is_clean_lst)`
4. Always see `0` as the total clean points despite all `x_train` is clean and `expected_pp_poison` is set to different values.

**Expected behavior**
When `x_train` is all clean, the value of `np.sum(is_clean_lst)` should be a positive number. And when changing the value of `expected_pp_poison`, the value of `np.sum(is_clean_lst)` should change. In particular, when decreasing the value of `expected_pp_poison`, `np.sum(is_clean_lst)` should increase.

**System information (please complete the following information):**
 - OS: macOS Big Sur 11.3.1
 - Python version: 3.7.9 
 - ART version or commit number: dev_1.6.2
 - TensorFlow / Keras / PyTorch / MXNet version: tensorflow 2.2.0, Keras 2.3.1

**Comment by beat-buesser** [comment]
Hi @Yi-Zoey Thank you very much for reporting this bug!
