### ISSUE TITLE
Using the aliases of builtin types like np.int is deprecated¶

### ISSUE THREAD

**Issue by konosubakonoakua** [Trusted-AI/adversarial-robustness-toolbox#1204]
**Describe the bug**
Using the aliases of builtin types like np.int is deprecated¶
Details here: [numpy 1.20 deprecations](https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations)

**To Reproduce**
update numpy to v1.20 or above, then get:
```
D:\app\Miniconda3\envs\adv\lib\site-packages\art\estimators\pytorch.py:167: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
```

**System information (please complete the following information):**
 - OS win10
 - Python version 3.8
 - ART version 1.7.0
 - TensorFlow / Keras / PyTorch / MXNet version

**Comment by beat-buesser** [comment]
Hi @konosubakonoakua Thank you very much for using ART and proposing this improvement! We'll include it in one of our upcoming releases!
