### ISSUE TITLE
Tensors on different devices lead to RuntimeError with PyTorchClassifier

### ISSUE THREAD

**Issue by inesvalentim** [Trusted-AI/adversarial-robustness-toolbox#1221]
**Describe the bug**
When a GPU is available but the `device_type` of a `PyTorchClassifier` is set to `cpu`, a `RuntimeError` occurs when applying the default preprocessing because not all tensors are on the same device.

**To Reproduce**
1. Get the `get_started_pytorch.py` example.
2. Instantiate the `PyTorchClassifier` with `device_type='cpu'` in a machine with a GPU available.
3. The `RuntimeError` is raised.

**Expected behavior**
The example should run without problems on the CPU.

**Possible fix**
https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/3d86b8d66b646fd736beda570254786bcff55e0e/art/estimators/pytorch.py#L69

When instantiating the `StandardisationMeanStdPyTorch` preprocessor while initializing a `PyTorchEstimator`, the `device_type` should be passed instead of using the default value of `'gpu'`.

**System information (please complete the following information):**
 - OS: Windows 10
 - Python version: 3.8.10
 - ART version or commit number: 1.6.2
 - PyTorch version: 1.9.0

**Comment by beat-buesser** [comment]
Hi @inesvalentim Thank you very much for using ART and reporting this issue! I agree, this a bug and your proposed solution makes sense. 

Would you be interested to open a pull request to branch `dev_1.7.1`?

**Comment by inesvalentim** [comment]
Hi @beat-buesser , yes, I can definitely work on it!

**Comment by beat-buesser** [comment]
That's great, thank you very much! Let us know if you have questions, etc.!
