### ISSUE TITLE
Examples for tabular data

### ISSUE THREAD

**Issue by shreyakhandelwal07** [Trusted-AI/adversarial-robustness-toolbox#1222]
I am exploring ART for tabular data. But I cannot find examples of its application. Most examples seem to be centered around image data. 

Could you please guide me to/include some examples where ART is being used to create adversarial examples for tabular data and to generate metrics for such attacks? It would be very helpful. Thanks.

**Comment by beat-buesser** [comment]
Hi @shreyakhandelwal07 Thank you very much for exploring ART! 

This notebook contains examples for tabular data: [imperceptible_attack_on_tabular_data.ipynb
](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/notebooks/imperceptible_attack_on_tabular_data.ipynb)

It demonstrates the LowProFool attack, but most of ART's evasion attacks should be compatible with tabular data and might only need minor adjustments to the new dataset like the model's input shape, etc. Continuous data is fully supported whereas categorical data still needs manual preparations by the user, but we aim to improve support for categorical data in the near future.

**Comment by shreyakhandelwal07** [comment]
Alright thank you @beat-buesser 👍 will check it out.
