### ISSUE TITLE
Audio classification attacks?

### ISSUE THREAD

**Issue by XiYuan68** [Trusted-AI/adversarial-robustness-toolbox#1241]
**Is your feature request related to a problem? Please describe.**
There are a few speech recognition attacks in ART but lack of audio classification attacks.

**Describe the solution you'd like**
Adding audio classification attacks.

**Describe alternatives you've considered**
Universal Adversarial Audio Perturbations (UAP) should be a good start, it looks simple and already has a official implementation [https://github.com/sajabdoli/UAP](https://github.com/sajabdoli/UAP)

**Comment by beat-buesser** [comment]
Hi @XiYuan68 Thank you very much for you interest in ART! I think your proposal to add Universal Adversarial Audio Perturbations  would be result in an interesting new tool.

Would you be interested to work on the implementation? We would be happy to provide help and support!

**Comment by XiYuan68** [comment]
I am working on my conference paper now, so I won't be available in the future months. But I'll sure give it a try after the conference if no one implements it yet.

**Comment by beat-buesser** [comment]
That sounds great!

**Comment by somiljain7** [comment]
can I give it a try?

**Comment by beat-buesser** [comment]
Hi @somiljain7 That's great to hear! I think @XiYuan68 has not started yet working on this issue. I think it would be great if you could implement the attack and unit tests. Let me know if you have questions or would like to discuss you implementation steps, etc.
