### ISSUE TITLE
image length-width ratio limits in square attack

### ISSUE THREAD

**Issue by XiYuan68** [Trusted-AI/adversarial-robustness-toolbox#1244]
**Describe the bug**
for image shape as [128, 188, 1], square attack raise value error

**To Reproduce**
1. train a model with images shape as [128, 188, 1], apply square attack with default arguments
2. error raised:
```
  File "/home/user/.local/lib/python3.9/site-packages/art/attacks/evasion/square_attack.py", line 233, in generate
    height_mid = np.random.randint(0, height - height_tile)

  File "mtrand.pyx", line 748, in numpy.random.mtrand.RandomState.randint

  File "_bounded_integers.pyx", line 1247, in numpy.random._bounded_integers._rand_int64

ValueError: high <= 0
```

**Expected behavior**
length-width ratio being validated before attacking or allow long images to be attacked

**Screenshots**
I did a little bit digging. [`height_mid = np.random.randint(0, height - height_tile)`](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/8c58a962a27394041b01e79435697b7723a5888e/art/attacks/evasion/square_attack.py#L233) is where thing goes wrong. 
for 
[`percentage_of_elements = self._get_percentage_of_elements(i_iter)`](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/8c58a962a27394041b01e79435697b7723a5888e/art/attacks/evasion/square_attack.py#L216)
and
[`height_tile = max(int(round(math.sqrt(percentage_of_elements * height * width))), 1)` ](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/8c58a962a27394041b01e79435697b7723a5888e/art/attacks/evasion/square_attack.py#L231)

with my data:
i_iter = 0
percentage_of_elements = 0.8
height = 128
width = 188
int(round(math.sqrt(percentage_of_elements * height * width))) = 139

it seems when height and width differ too much, the following two lines:
```
height_mid = np.random.randint(0, height - height_tile)
width_start = np.random.randint(0, width - height_tile)
```
will always raise value error because `height - height_tile <= 0` or  `width - height_tile <= 0`

**System information (please complete the following information):**
 - OS: Manjaro
 - Python version: 3.9
 - ART version or commit number: 1.7.0
 - TensorFlow / Keras / PyTorch / MXNet version : tensorflow-gpu 2.5.0

**Comment by beat-buesser** [comment]
Hi @XiYuan68 Thank you very much for using ART! Yes, it is correct that the current version of `SqaureAttack` assumes square input images (the name of the attack refers to the shape of the perturbations not the input requirement). We'll try to add a check or better see if the sampling can be extended to support rectangular images. 

Have you already tried updating the sampling of the `height_mid` and `height_mid`? We would be interested to include your solution in ART 1.8!

**Comment by XiYuan68** [comment]
My computer is running a lot of attacks now so I can't test it myself but the simplest way to allow square-attacking rectangular images seems to add one line  after [line231](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/8c58a962a27394041b01e79435697b7723a5888e/art/attacks/evasion/square_attack.py#L231):

```
height_tile = max(int(round(math.sqrt(percentage_of_elements * height * width))), 1)
height_tile = np.min([height - 1, width - 1, height_tile])
``` 

so that 

```
height_mid = np.random.randint(0, height - height_tile)
width_start = np.random.randint(0, width - height_tile)
```

should always be within the limit and get a square-shape perturbation within the image's shape

hope this will work : )

**Comment by beat-buesser** [comment]
Hi @XiYuan68 Thank you very much, this is very helpful! This is optional, but would you be interested to open a pull request for your solution for the upcoming release of ART 1.8?

**Comment by XiYuan68** [comment]
sure! it may take some time though cause it's my first time to PR and it looks quite complex..

**Comment by beat-buesser** [comment]
Hi @XiYuan68 That's great news! Thank you very much! I'll take soon a look at your PR.
