### ISSUE TITLE
PyTorchClassifier.compute_loss() doesn't accept index-based labels

### ISSUE THREAD

**Issue by jacobalanbond** [Trusted-AI/adversarial-robustness-toolbox#1245]
**Describe the bug**
The `PyTorchClassifier.compute_loss()` method does not accept index-based labels, contradicting the documentation.

**To Reproduce**
1. Go to the `get_started_pytorch.py` example.
2. Follow steps 0-3 in the example.
3. Run
`y = np.array(range(10)); classifer.compute_loss(x_train[:10,...], y)`
4. When `compute_loss` calls `reduce_labels(y_preprocessed)`, `reduce_labels` will try to take an `argmax` along `dim=1`, raising an error.

**Expected behavior**
I expected the `compute_loss` method to accept index-based labels, following the documentation.

**Possible fix**
Similar to the case of binary classification, in the case that `self.nb_classes > 2`, `reduce_labels` could check whether `len(y.shape) == 2`.

**System information (please complete the following information):**
 - Python version 3.6.3
 - ART version 1.6.1
 - PyTorch version 1.7

**Comment by beat-buesser** [comment]
Hi @jacobalanbond Thank you very much for reporting this bug! We'll fix it in the next release.
