### ISSUE TITLE
Exception is raised even if min_epsilon is a positive float in BoundaryAttack

### ISSUE THREAD

**Issue by kaitokishi** [Trusted-AI/adversarial-robustness-toolbox#1258]
**Describe the bug**
[`BoundaryAttack`](https://adversarial-robustness-toolbox.readthedocs.io/en/latest/modules/attacks/evasion.html#boundary-attack-decision-based-attack) cannot receive `min_epsilon`.

**To Reproduce**
1. Train a model.
2. Call `BoundaryAttack(model, min_epsilon=0.001)`.
3. See an exception.

**Expected behavior**
`min_epsilon` is a positive `float` (or `None`), so `0.001` should be valid.

**Cause of the bug**  
[boundary.py:L473-L474](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/art/attacks/evasion/boundary.py#L473-L474)  
```python
if self.min_epsilon is not None and (isinstance(self.min_epsilon, float) or self.min_epsilon <= 0):
    raise ValueError("The minimum epsilon must be a positive float.")
```
raise error when `self.min_epsilon` is `float`. Therefore, we need `not` before the `isinstance`.

**Comment by beat-buesser** [comment]
Hi @kaitokishi Thank you very much for using ART and reporting this bug! I think your solution of adding the missing `not` is correct.

Would you be interested to open a pull request with your solution to branch `dev_1.7.2`? Otherwise we'll include the solution in the upcoming release 1.7.2 in the coming days.

**Comment by kaitokishi** [comment]
Thank you for your reply. So, I will try making the pull request.

**Comment by beat-buesser** [comment]
Hi @kaitokishi That's great! Let us know you if you need help or support for the PR!
