### ISSUE TITLE
Dimension incompatability when using EoT rotation

### ISSUE THREAD

**Issue by McLovin90** [Trusted-AI/adversarial-robustness-toolbox#1267]
**Describe the bug**
When generating 1000 adversarial samples with PGD and EoT, Python returns a ValueError.

**To Reproduce**
1. Choose 1000 images from the CIFAR10 dataset.
2. Initialize an instance of `EoTImageRotationTensorflow` with `nb_samples=10`.
3. Train a simple CNN (`TensorFlowV2Classifier`) with `prepocessing_defence = [eot_rotation]` on the whole CIFAR10 dataset.
4. Initialize an instance of `ProjectedGradientDescentTensorFlowV2` with 100 iterations and `eps = 8.0 / 255.0` and `eps_step = 2.0 / 255.0`
5. Generate 1000 adversarial samples.
6. Error message:
ValueError: Dimensions 1000 and 10000 are not compatible

**Expected behavior**
Successfully generate 1000 adversarial samples with `ProjectedGradientDescentTensorFlowV2` and `EoTImageRotationTensorflow`

**System information (please complete the following information):**
 - Windows 10
 - Python 3.7
 - ART 1.7.1
 - TensorFlow 2.4.2

An example file for reproducing the error is attached. 
[test.txt](https://github.com/Trusted-AI/adversarial-robustness-toolbox/files/6985237/test.txt)

**Comment by beat-buesser** [comment]
Hi @McLovin90 Thank you very much for using ART and reporting this issue! We will test your example script and fix the bug as soon as possible.

**Comment by beat-buesser** [comment]
Hi @McLovin90 Yes, instead of true labels (for untargeted attacks) you also can provide any other label (for targeted attacks) but you will have to set the argument `targeted=True`.

**Comment by McLovin90** [comment]
Thanks for your answer and your help. I think we can close this issue.
