### ISSUE TITLE
Link failure problem

### ISSUE THREAD

**Issue by Zengyf-CVer** [Trusted-AI/adversarial-robustness-toolbox#1275]
https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/notebooks/README.md#attacks
**This link is no longer working!**
![image](https://user-images.githubusercontent.com/41098760/130345143-c9855a8d-1b4a-4030-b5bd-132219232600.png)

**Comment by beat-buesser** [comment]
Hi @Zengyf-CVer Thank you very much for reporting this broken link! We will fix it as soon as possible. The notebook is still available at https://github.com/Trusted-AI/adversarial-robustness-toolbox/tree/main/notebooks/adversarial_patch
