### ISSUE TITLE
Issue of import error when running model inversion attack notebook

### ISSUE THREAD

**Issue by iRxyzzz** [Trusted-AI/adversarial-robustness-toolbox#1311]
**Describe the bug**
There exists an import error when running model inversion attack notebook, caused by the changed API of MIFace algorithm. 

**To Reproduce**
1. Go to 'notebooks'
2. Click on 'model_inversion_attacks_mnist.ipynb'
3. Scroll down to 'import area' and run the code

**Comment by beat-buesser** [comment]
Hi @iRxyzzz Thank you very much for reporting this issue! It looks like the import needs to be updated to `from art.attacks.inference.model_inversion import MIFace`. Could you please try it out and if possible open a pull request?

**Comment by iRxyzzz** [comment]
Hi Beat,

I have created a PR request. Pls check.

Regards,
Runhua Xu

**Comment by beat-buesser** [comment]
Hi @iRxyzzz That's great! Thank you very much!
