### ISSUE TITLE
Inconsistency input shape for AdversarialPatchPyTorch

### ISSUE THREAD

**Issue by YuhengHuang42** [Trusted-AI/adversarial-robustness-toolbox#1324]
**Describe the bug**
The `__init__` function assumes that the input should be in shape `NCHW` . 

For example: 

https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/49e13eac6f4d1154ccfdc5eb398a93924455fec6/art/attacks/evasion/adversarial_patch/adversarial_patch_pytorch.py#L152

https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/49e13eac6f4d1154ccfdc5eb398a93924455fec6/art/attacks/evasion/adversarial_patch/adversarial_patch_pytorch.py#L136

However, the generate function requires the input shape to be `NHWC`:

https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/49e13eac6f4d1154ccfdc5eb398a93924455fec6/art/attacks/evasion/adversarial_patch/adversarial_patch_pytorch.py#L415

If you follow all the requirements in the doc, then you will get an error:

```
~/.local/lib/python3.8/site-packages/art/attacks/evasion/adversarial_patch/adversarial_patch_pytorch.py in _random_overlay(self, images, patch, scale, mask)
    407         inverted_mask = torch.from_numpy(np.ones(shape=image_mask.shape, dtype=np.float32)) - image_mask
    408 
--> 409         return images * inverted_mask + padded_patch * image_mask
    410 
    411     def generate(self, x: np.ndarray, y: Optional[np.ndarray] = None, **kwargs) -> Tuple[np.ndarray, np.ndarray]:

RuntimeError: The size of tensor a (3) must match the size of tensor b (224) at non-singleton dimension 3
```

**Expected behavior**
The shape should be consistent 

Version: ART 1.8.0

**Comment by YuhengHuang42** [comment]
What I mentioned above should be a documentation error. If you just use `NCHW`, then it should be OK.

However, when running the code on GPU enabled server, you will get a device error at the same location:

```
~/.local/lib/python3.8/site-packages/art/attacks/evasion/adversarial_patch/adversarial_patch_pytorch.py in _random_overlay(self, images, patch, scale, mask)
    407         inverted_mask = torch.from_numpy(np.ones(shape=image_mask.shape, dtype=np.float32)) - image_mask
    408 
--> 409         return images * inverted_mask + padded_patch * image_mask
    410 
    411     def generate(self, x: np.ndarray, y: Optional[np.ndarray] = None, **kwargs) -> Tuple[np.ndarray, np.ndarray]:

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

**Comment by beat-buesser** [comment]
Hi @YuhengHuang42 Thank you very much for using ART and raising this issue! We will be taking a closer look as soon as possible. Do you have a simple example code that we can run to reproduce the error?

**Comment by YuhengHuang42** [comment]
> Hi @YuhengHuang42 Thank you very much for using ART and raising this issue! We will be taking a closer look as soon as possible. Do you have a simple example code that we can run to reproduce the error?

Sure

```
import torch
import torch.nn as nn
import torchvision
from art.attacks.evasion import AdversarialPatchPyTorch
from art.estimators.classification import PyTorchClassifier
import numpy as np

images = torch.randn(16, 3, 224, 224)
target_name = 'toaster'
image_shape = (3, 224, 224)
clip_values = (0, 1)
nb_classes  =1000
batch_size = 16
scale_min = 0.4
scale_max = 1.0
rotation_max = 22.5
learning_rate = 5000.
max_iter = 200

resnet = torchvision.models.resnet18(pretrained=True)
resnet.cuda()
model_wrapper = PyTorchClassifier(model=resnet, loss=nn.CrossEntropyLoss, nb_classes=nb_classes, 
                                        input_shape=image_shape, clip_values=clip_values, device_type="cuda")

ap = AdversarialPatchPyTorch(classifier=model_wrapper, rotation_max=rotation_max, 
                      scale_min=scale_min, scale_max=scale_max,
                      learning_rate=learning_rate, max_iter=max_iter, batch_size=batch_size,
                      patch_shape=(3, 31, 31), patch_type="square", verbose=True)

label = 1
y_one_hot = np.zeros(nb_classes)
y_one_hot[label] = 1.0
y_target = np.tile(y_one_hot, (images.shape[0], 1))
patch, patch_mask = ap.generate(x=images, y=y_target)
```

**Comment by shuoli90** [comment]
I found where the "bug" is. Briefly, your patch should be of the same dimension as your input data. Particularly, if your input data is NCHW, your patch shape should be (1,3,31,31). On the other hand, if your input data is CHW, your patch shape should be (3,31,31). For more detail, please check lines 145 to 151 and 257 to 262.

**Comment by YuhengHuang42** [comment]
> I found where the "bug" is. Briefly, your patch should be of the same dimension as your input data. Particularly, if your input data is NCHW, your patch shape should be (1,3,31,31). On the other hand, if your input data is CHW, your patch shape should be (3,31,31). For more detail, please check lines 145 to 151 and 257 to 262.

Oh, as I said before, this should be a documentation error. Another error is the device error, which happens at where you create the mask.

**Comment by beat-buesser** [comment]
@YuhengHuang42 I think you are right, I was able to reproduce your description. I have opened pull request #1333 to fix this issue. Could you please take a look and try out the improved version?

**Comment by YuhengHuang42** [comment]
> @YuhengHuang42 I think you are right, I was able to reproduce your description. I have opened pull request #1333 to fix this issue. Could you please take a look and try out the improved version?

Yes, everything seems to work fine now. Thanks for the timely reply!
