### ISSUE TITLE
integrate "indicators of attack failure" from Pintor et al 2021

### ISSUE THREAD

**Issue by Embeddave** [Trusted-AI/adversarial-robustness-toolbox#1325]
Hi @beat-buesser I don't see an issue for this yet, even though you just mentioned it in your presentation, so I am selfishly raising this issue in the hopes I can track development. If I'm just missing the issue, please feel free to close this.

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Integrate metrics described in https://arxiv.org/abs/2106.09947 that provide quantitative indicators of attack failure.
Implementations here: https://github.com/pralab/IndicatorsOfAttackFailure

This is the specific module:
https://github.com/pralab/IndicatorsOfAttackFailure/blob/master/src/indicators/indicators.py

**Describe alternatives you've considered**
Since you mentioned implementing for certain attacks:

Would it be possible to add these in a way so that user is empowered to apply them with any attack? 

That is, instead of separately implementing additional logic that does all the tracking of metrics, but only for certain attacks, instead give users access to variables they need to compute any of the metrics themselves.

E.g., to compute the `break_point_angle` a user would need `loss`. To get `loss` they would need to pass in a `tensor_board` instance to any attack. 

Currently this is only available for PGD and patch, but it would be easier to implement this for any attack than, say, separately implementing a `compute_breakpoint_angle` method for every single attack.

So with the `tensor_board` approach, these metrics could go in their own module, e.g. `art.attacks.indicators`. 

A user would have to know how to do this, so `art` wouldn't magically do everything for them, but that could be addressed with a Jupyter notebook and/or tutorial in docs.

Maybe this is what you all already have in mind -- just thought I'd offer my 2 cents

**Comment by beat-buesser** [comment]
Hi @Embeddave

Thank you very much! I was very happy to see that my presentation on ART today already resonated with users of ART! 

A few initial thoughts: I agree with you, ideally we want a solution that supports all attacks immediately, I'm sometimes a bit cautious and say we'll have it at the beginning at least for some of the attacks. We haven't done a lot of abstraction so far for the TensorBoard support but this issue could include more abstraction and combine it with the indicators.

For `break_point_angle` we could use the new method `compute_loss` which is now part of the Estimator API.

The indicators could also go to `art.metrics.indicators`.

Let's continue the discussion!

**Comment by Embeddave** [comment]
Ah I see, I was unaware of `compute_loss` -- good to know.
Yes, that method makes things much easier
