### ISSUE TITLE
Implement Adversarial Laser Beam attack

### ISSUE THREAD

**Issue by beat-buesser** [Trusted-AI/adversarial-robustness-toolbox#1327]
We would like to implement the Adversarial Laser Beam attack to simulate and investigate easily realisable physical attack.

Paper link: https://openaccess.thecvf.com/content/CVPR2021/papers/Duan_Adversarial_Laser_Beam_Effective_Physical-World_Attack_to_DNNs_in_a_CVPR_2021_paper.pdf

**Comment by mateuszGorczany** [comment]
I am eager to implement it.
