### ISSUE TITLE
Implement SIGN-OPT: A Query-Efficient Hard-label Black-box Attack

### ISSUE THREAD

**Issue by synergit** [Trusted-AI/adversarial-robustness-toolbox#1331]
Adding a new evasion attack based on paper https://arxiv.org/pdf/1909.10773.pdf, [Reference Codebase](https://github.com/cmhcbb/attackbox)
- single query for retrieving sign of directional derivative.
- 5x to 10x fewer queries when compared to state-of-art approaches

**Additional context**
Related class in ART:  [BoundaryAttack](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/art/attacks/evasion/boundary.py) which is a black box attack. 
- random walk along the boundary

Related paper: 
1. https://arxiv.org/pdf/1807.04457.pdf, [Reference Codebase](https://github.com/LeMinhThong/blackbox-attack) 
- solved by zeroth order optimization algorithm
- 3~4 times less queries when compared to state-of-art approaches
2. [Model definition](https://arxiv.org/pdf/1608.04644.pdf) for matching the performance. 

Author of Sign_OPT uses the NN model in paper https://arxiv.org/pdf/1608.04644.pdf, parameter listed in table 1

**Comment by beat-buesser** [comment]
Hi @synergit Thank you very much for implementing a new black-box evasion attack!

**Comment by synergit** [comment]
Notes after the sync with Beat on Nov. 1st. 
1. starting from examples [here](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/examples/get_started_pytorch.py); Make sure the model is only trained once
2. use MNIST dataset to build the SIGN-OPT

**Comment by synergit** [comment]
hi @beat-buesser , I tried to push my WIP code to branch with command 
```
git push --set-upstream origin develop
ment_issue_1331
Username for 'https://github.com': synergit
Password for 'https://synergit@github.com': 
remote: Permission to Trusted-AI/adversarial-robustness-toolbox.git denied to synergit.
fatal: unable to access 'https://github.com/Trusted-AI/adversarial-robustness-toolbox.git/': The requested URL returned error: 403
```
But I got 403 error, is this related to access limitation? Please advice, thank you!

**Comment by beat-buesser** [comment]
Hi @synergit Sorry for the delayed response. It looks like git needs to switch to your forked repo.

**Comment by synergit** [comment]
Hi @beat-buesser , I've updated the Dockerfile for my development. The commit is [here](https://github.com/Trusted-AI/adversarial-robustness-toolbox/commit/38c48d7122febbf5cf1fe6f4856208b11e43918b?diff=split). 

As I showed you this Monday about the error of `ValueError: The shape of mean and the standard deviation must be identical.`, I reproduced it with notebook [here](https://github.com/synergit/adversarial-robustness-toolbox/blob/development_issue_1331/notebooks/attack_decision_based_boundary.ipynb) , please let me know if you know the root cause. I suspect it is due to the old version of torch, but please let me know the recommended versions. Thank you!

**Comment by beat-buesser** [comment]
Hi @synergit That's great. The `ValueError`is raised because both values in the tuple `preprocessing=(mean_imagenet, 1)` need to have the same shape. In your notebook `mean_imagenet` is of shape (224, 224, 3), therefore the `1` would have to be replaced with an array of ones with the same shape. Btw, the values of `preprocessing` follow the Numpy broadcasting rules, which means `mean_imagenet` can be of shape (3,) because there is only one mean value per channel.

**Comment by synergit** [comment]
Thank you @beat-buesser you are right! Check [this](https://github.com/synergit/adversarial-robustness-toolbox/blob/development_issue_1331/notebooks/attack_decision_based_boundary.ipynb) out, no more `ValueError`

**Comment by synergit** [comment]
Hi Beat, I've done the the code for Sign_OPT with `untargeted` case. So I am thinking the next steps could be one of:
- complete Sign_OPT with `targeted` case
- test Sign_OPT with `untargeted` with new popular data besides MNIST
- add unit test to Sign_OPT. 

Please help me to prioritize. Thank you!

**Comment by beat-buesser** [comment]
Hi @synergit That's great news! Sorry for the delayed response.

- I think adding tests would be the next step to complete the requirements for a pull request.
- Adding support for Algorithm 2/SVM-OPT would be great (but not a requirement for a pull request). It seems even more query efficient.

I understand that you have now Sign-OPT for targeted and untargeted attacks? Are you able to reproduce the papers results?

**Comment by synergit** [comment]
Good questions @beat-buesser ! 
Yes to 
> I understand that you have now Sign-OPT for targeted and untargeted attacks? 

Can you please elaborate what papers results I will need to reproduce?

**Comment by beat-buesser** [comment]
That's great! To validate the implementation I would propose to reproduce the performance reported in Table 1 for Sign-OPT attack for MIST and maybe CIFAR-10.

**Comment by synergit** [comment]
sure! 
About average L2, it is straightforward, please note the data from paper is summarized on 100 randomly sampled examples. 
About SR(success rage), I need some help about the definition: on page 6 of [Sign_OPT paper](https://arxiv.org/pdf/1909.10773.pdf)

> Besides, we also show success rate (SR) for x queries for a given threshold (`epsilon`), which
> is the percentage of number of examples that have achieved an adversarial perturbation below `epsilon` with
> less than x queries. We evaluate success rate on different thresholds which depend on the dataset
> being used. 

@beat-buesser can you please help me to understand setting up this `epsilon` for calculate SR?

**Comment by kanak000** [comment]
> Thank you @beat-buesser you are right! Check [this](https://github.com/synergit/adversarial-robustness-toolbox/blob/development_issue_1331/notebooks/attack_decision_based_boundary.ipynb) out, no more `ValueError`

I am still getting that same value error, can you hep me with it?

**Comment by kanak000** [comment]
> Hi @synergit That's great. The `ValueError`is raised because both values in the tuple `preprocessing=(mean_imagenet, 1)` need to have the same shape. In your notebook `mean_imagenet` is of shape (224, 224, 3), therefore the `1` would have to be replaced with an array of ones with the same shape. Btw, the values of `preprocessing` follow the Numpy broadcasting rules, which means `mean_imagenet` can be of shape (3,) because there is only one mean value per channel.


Can you provide the written code to solve this error, coz i am still getting the error.
