### ISSUE TITLE
check_and_transform_label_format with return_one_hot=True does not one hot encode when nb_classes=2

### ISSUE THREAD

**Issue by GalHorowitz** [Trusted-AI/adversarial-robustness-toolbox#1334]
**Describe the bug**
When the number of classes is 2, the `check_and_transform_label_format` function from `art.utils` does not one one-hot-encode labels even though the `return_one_hot` keyword argument is true. Instead, the label is kept as is (`0 -> [0], 1 -> [1]`)

**To Reproduce**
When using the MembershipInferenceBlackBox attack on a classifier with 2 classes with the default neural network attack models, if the `y` labels array is not already one hot encoded when calling the `fit` function, training fails because the neural network receives input of incorrect shape.

**Expected behavior**
Binary labels should correctly be one-hot-encoded when `return_one_hot` is true, i.e. `0 -> [1, 0], 1 -> [0, 1]`.

**Comment by beat-buesser** [comment]
Hi @GalHorowitz Thank you very much for reporting this issue! I have been able to reproduce your description. We'll fix it as soon as possible!
