### ISSUE TITLE
Add PyTorch implementation for Poison Frogs poisoning attack

### ISSUE THREAD

**Issue by Nathalie-B** [Trusted-AI/adversarial-robustness-toolbox#1387]
**Is your feature request related to a problem? Please describe.**
Add the implementation for keras for the Poison Frogs 
https://proceedings.neurips.cc/paper/2018/file/22722a343513ed45f14905eb07621686-Paper.pdf

**Describe the solution you'd like**
- Add Jupyter notebook demonstrating functionality 

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by monshri** [comment]
I am currently working on this issue.

**Comment by monshri** [comment]
The current version of Feature Collision Attacks/Poison Frogs includes Keras implementation already : [https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/notebooks/poisoning_attack_feature_collision.ipynb](url) 
We need to add PyTorch implementation to it.

**Comment by beat-buesser** [comment]
@monshri Thank you, I'll update the issue title accordingly.
