### ISSUE TITLE
Implement ensemble defense for poisoning 

### ISSUE THREAD

**Issue by Nathalie-B** [Trusted-AI/adversarial-robustness-toolbox#1389]
**Is your feature request related to a problem? Please describe.**
Deep Partition Aggregation: Provable Defense against General Poisoning Attacks
https://arxiv.org/abs/2006.14768 

**Describe the solution you'd like**
- jupyter notebook
- examples 

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by keykholt** [comment]
I can work on implementing this
