### ISSUE TITLE
Poisoning defense: modified adv. training  

### ISSUE THREAD

**Issue by Nathalie-B** [Trusted-AI/adversarial-robustness-toolbox#1391]
**Is your feature request related to a problem? Please describe.**
What Doesn’t Kill You Makes You Robust(er): Adversarial Training against Poisons and Backdoors
https://arxiv.org/pdf/2102.13624.pdf 

**Describe the solution you'd like**
- notebooks
- examples 

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by TS-Lee** [comment]
I will work on this.
