### ISSUE TITLE
Implement sleeper agent 

### ISSUE THREAD

**Issue by Nathalie-B** [Trusted-AI/adversarial-robustness-toolbox#1392]
**Is your feature request related to a problem? Please describe.**
Sleeper Agent: Scalable Hidden Trigger Backdoors for Neural Networks Trained from Scratch
https://arxiv.org/pdf/2106.08970.pdf 

**Describe the solution you'd like**
- jupyter notebooks

**Comment by monshri** [comment]
I can work on implementing this.
