### ISSUE TITLE
remove "doesn't work for pytorch" from `SimBA` tests

### ISSUE THREAD

**Issue by beat-buesser** [Trusted-AI/adversarial-robustness-toolbox#1410]
### Discussed in https://github.com/Trusted-AI/adversarial-robustness-toolbox/discussions/1409

<div type='discussions-op-text'>

<sup>Originally posted by **Embeddave** November 17, 2021</sup>
**Is your feature request related to a problem? Please describe.**
When troubleshooting the `SimBA` attack I found several places in the tests that state it does not work for `torch`:

https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/85ca10ff6b696dbaa66dcf179d0493b12ff594bb/tests/attacks/test_simba.py#L42

https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/85ca10ff6b696dbaa66dcf179d0493b12ff594bb/tests/attacks/test_simba.py#L97

(which is particularly surprising since it was originally written in `torch`)

**Describe the solution you'd like**
Remove that language from comments in tests or please clarify if there's something I'm not understanding.
After troubleshooting I was able to run the attacks with a `torch` model.
It does seem to be working for me, although I haven't done extensive runs yet.</div>

**Comment by beat-buesser** [comment]
Hi @Embeddave Thank you very much for your proposal. Sorry for reposting this issue, I had transferred it to discussions in-between to ask for more information about your trouble-shooting. Looking at the commit history of SimBA, it looks so far like a simple case where a comment in a different file got forgotten to be updated. The initial version in the SimBA PR was channels last only, but with ART we were able to easily extend this SimBa implementation to support channels first too. We can update the comments accordingly.

Let me know your findings on further testing SimBA, I would be interested to learn your insights.

**Comment by Embeddave** [comment]
Thank you @beat-buesser 

So far it seems to be working with a `torch` model wrapped in a vanilla `PyTorchClassifier`.  
I am computing probabilities "manually" outside of `art` and passing them in when I call `simba_attack.generate()`.  

I am using parameters from the README to attack Imagenet images with the `'dct'` version of the attack, `freq_dim=28, stride=7`

Running on Imagenette from the FastAI folks against a ResNet50, I am at ~600 attacks after ~16 hours on epsilon=1/255 (0.003), and ~1200 attacks on epsilon=8/255 (0.0313).

So it's definitely takes a while esp. compared to the huge eps=0.2 they use in the paper. But on par if not faster than square attack

Not sure if you saw, and this is off-topic for this issue, but looks like @cg563 recently added L-inf bound (and there's a batch size > 1 in their implementation)
https://github.com/cg563/simple-blackbox-attack/blob/418b25f4dd8cc0f988376c5730ae3988b95fbce0/simba.py#L58

I'm sure you have no shortage of things to work on but having the L-inf bound would be very nice!

**Comment by beat-buesser** [comment]
Hi @Embeddave Thank you, I think these would definitely be useful features. Maybe you could create a separate feature issue so that it does not get forgotten when this issue closes with #1423.

We'll try our best, but let me know if you are interested in trying to implement these features, we always appreciate contributions and are happy to help and provide support

Please also take a look at #1407 for `x` with multiple samples.

**Comment by Embeddave** [comment]
Excellent, thank you.

I will raise a separate issue: re L-inf, just to track it

We may consider implementing it depending on these results and in that case I would be happy to contribute back
