### ISSUE TITLE
insert_image in art.attacks.poisoning.perturbations does not preserve the dtype of the passed  ndarray.

### ISSUE THREAD

**Issue by keykholt** [Trusted-AI/adversarial-robustness-toolbox#1440]
**Describe the bug**
When passing data to `insert_image`, the returned type of the array is not the same as the original data passed. This can occasionally cause issues with data types when using the returned value. This is probably a minor issue and I can bypass this issue by simply converting the returned data back to the original dtype, but it might be nice to not require this step.

**To Reproduce**
In my case, I had a PyTorch model trained using input data with dtype=float32. The pytorch model weights appeared to be float tensors.
Steps:
1. I feed the input data of dtype=float32 to `insert_image` and receive a numpy array with dtype=float64
2. I convert the returned value into a PyTorch Tensor using torch.from_numpy(). This converts the returned value into a DoubleTensor
3. An error occurs when I use the converted tensor as input to `art.estimator.get_activations()`. The error is `RuntimeError: Input type (torch.cuda.DoubleTensor) and weight type (torch.cuda.FloatTensor) should be the same`

I get similar issues if I pass an Int. I will get a float back.

**Expected behavior**
The dtype of the input to `insert_image` should be preserved.

**System information (please complete the following information):**
 - Unbuntu 18.04
 - Python 3.8
 - ART 1.9

**Comment by beat-buesser** [comment]
Hi @keykholt Thank you very much for reporting this issue!
