### ISSUE TITLE
_device is not automatically initialized in PreprocessorPyTorch

### ISSUE THREAD

**Issue by nilakshdas** [Trusted-AI/adversarial-robustness-toolbox#1442]
**Describe the bug**
The `_device` parameter is never initialized in a `PreprocessorPyTorch` object. It is referenced in the `PreprocessorPyTorch.device` [property](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/09e0e19d92c57695c360b8c51e7def6b190a2cbb/art/defences/preprocessor/preprocessor.py#L169:L174), which in turn is used in the `PreprocessorPyTorch.__call__` method.

**To Reproduce**
```python
# test.py

from art.defences.preprocessor.preprocessor import PreprocessorPyTorch


class TestPreprocessorPyTorch(PreprocessorPyTorch):
    def forward(self, x, y):
        return x, y


if __name__ == "__main__":
    preprocessor = TestPreprocessorPyTorch()
    preprocessor(None, None) # doesn't matter what we pass here
```

```bash
$ python test.py
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    preprocessor(None, None)
  File ".../art/defences/preprocessor/preprocessor.py", line 186, in __call__
    x = torch.tensor(x, device=self.device)
  File ".../art/defences/preprocessor/preprocessor.py", line 174, in device
    return self._device
AttributeError: 'TestPreprocessorPyTorch' object has no attribute '_device'
```

**Expected behavior**
`PreprocessorPyTorch._device` should be initialized to a value that is compatible with `torch.tensor(..., device=self.device)`.

**System information (please complete the following information):**
 - OS: Ubuntu 18.04.6 LTS
 - Python version: Python 3.7.5
 - ART version or commit number: 6d8aacf
 - PyTorch: 1.7.0

**Comment by beat-buesser** [comment]
Hi @nilakshdas Thank you very much for using ART and for the detailed description! 

Currently, all implementations of `PreprocessorPyTorch` in ART (e.g. `Mp3CompressionPyTorch`) define the attribute `self._device` in their own `__init__` methods. In your example it would require
```python
class TestPreprocessorPyTorch(PreprocessorPyTorch):

    def __init__(..., device_type: str = "gpu"):

        [...]

        # Set device
        if device_type == "cpu" or not torch.cuda.is_available():
            self._device = torch.device("cpu")
        else:  # pragma: no cover
            cuda_idx = torch.cuda.current_device()
            self._device = torch.device("cuda:{}".format(cuda_idx))

    def forward(self, x, y):
        return x, y
```

But, I agree with you, it would be much better if `device_type` would be passed to `super().__init__` to define the attribute `self._device` in `PreprocessorPyTorch.__init__`.

Would you be interested to push a solution in a pull request? I'd be happy to provide support!
