### ISSUE TITLE
Implement momentum iterative fast gradient sign method (MIFGSM)

### ISSUE THREAD

**Issue by cxmscb** [Trusted-AI/adversarial-robustness-toolbox#1447]
**Is your feature request related to a problem? Please describe.**
Boosting Adversarial Attacks with Momentum
https://arxiv.org/pdf/1710.06081

**Comment by beat-buesser** [comment]
Hi @cxmscb Thank you very much for suggesting the implementation of momentum iterative fast gradient sign method. I think this attack would be a great feature in ART.

Would you be interested to implement the attack?

**Comment by sechkova** [comment]
Hi @beat-buesser, can I give it a try?

**Comment by beat-buesser** [comment]
Hi @sechkova Yes! Thank you very much and let us know if you have questions, etc.
