### ISSUE TITLE
ImportError when importing `art 1.9.0` due to `matplotlib` in `laser_attack.utils`

### ISSUE THREAD

**Issue by Embeddave** [Trusted-AI/adversarial-robustness-toolbox#1456]
**Describe the bug**
when I attempt to import `art` 1.9.0 I get a `ModuleNotFoundError`
```
../../../.cache/pypoetry/virtualenvs/neurips-2021-nd2ZNWoA-py3.7/lib/python3.7/site-packages/art/attacks/evasion/laser_attack/utils.py:30: in <module>
    import matplotlib.pyplot as plt
E   ModuleNotFoundError: No module named 'matplotlib'
```

I think this is due to the import of `matplotlib` in `laser_attack.utils` that @mateuszGorczany added last month?
https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/cbf4f9df679a9e434e3c42de89ed438400335d44/art/attacks/evasion/laser_attack/utils.py#L30

Looks like you all have it declared as an extras or dev dependency, but not in `install_requires`. I'm guessing it's not intended for import to fail just because I haven't installed extras though?

```
install_requires = [
    "numpy>=1.18.0",
    "scipy>=1.4.1",
    "scikit-learn>=0.22.2,<1.1.0",
    "six",
    "setuptools",
    "tqdm",
    "numba>=0.53.1",
]
```

**System information (please complete the following information):**
 - Ubuntu
 -  3.7
 -  1.9.0
 - torch 1.10

**Comment by beat-buesser** [comment]
Hi @Embeddave Happy New Year! Thank you very much for reporting this issue. I completely agree and we will fix it soon with ART 1.9.1.

We will probably move the import of `matplotlib` to make it required for `laser_attack` only.

For ART 1.9.0, this error can be avoided by installing `matplotlib`.

**Comment by Embeddave** [comment]
Understood, thank you @beat-buesser -- I did end up fixing by just installing `matplotlib`.

Looks like you have this on the to-do list so I will leave open for now?

Happy 2022 to you as well. We made it 🎉 😏

**Comment by beat-buesser** [comment]
Yes, please leave the issue open, it will close automatically once the solution is merged to branch `main`.
