### ISSUE TITLE
get_activations for pytorch_estimator returns incorrect values when framework=True?

### ISSUE THREAD

**Issue by keykholt** [Trusted-AI/adversarial-robustness-toolbox#1468]
**Describe the bug**
The implementation of `get_activations()` for the pytorch estimator returns the value of x when `framework=True`.
https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/art/estimators/classification/pytorch.py#L853

**Expected behavior**
It should return the value of the tensor for x_preprocessed

**Comment by beat-buesser** [comment]
Hi @keykholt Thank you very much for reporting this issue! We will fix it with ART 1.9.1
