### ISSUE TITLE
Add functionality to save attack models.

### ISSUE THREAD

**Issue by ROYALBEFF** [Trusted-AI/adversarial-robustness-toolbox#1541]
I'm currently running multiple experiments and want to store the trained attack models for later use, similar to `torch.save()`.
I couldn't find anything in the documentation, so I assume it's not yet possible to store attack models.

This is a crucial feature for any ML library!

**Comment by beat-buesser** [comment]
Hi @ROYALBEFF

Thank you very much for using ART! I think that could be a useful feature.

Could you please describe your use case in more detail?

Would be interested to implement a prototype?
