### ISSUE TITLE
Support continuous attributes in attribute inference attacks

### ISSUE THREAD

**Issue by abigailgold** [Trusted-AI/adversarial-robustness-toolbox#1543]
**Is your feature request related to a problem? Please describe.**
Currently attribute inference attacks only support categorical features.

**Describe the solution you'd like**
At least in the black box and baseline attacks it should be possible to support continuous features as well (using a regression attack model instead of a classifier).

**Comment by beat-buesser** [comment]
Hi @abigailgold Thank you very much for proposing this new feature!
