### ISSUE TITLE
Fix `art/estimators/classification/tensorflow.py` to work in TF2 compat.v1 mode

### ISSUE THREAD

**Issue by shenshaw26** [Trusted-AI/adversarial-robustness-toolbox#1558]
**Is your feature request related to a problem? Please describe.**
When testing things in armory, we are moving away from supporting tf1 directly in favor of using tf2 compatability mode.  As such we run into issue when we try to use: `art/estimators/classification/tensorflow.py` as it has a call (`graph = tf.get_default_graph()`) which is incompatible.  

**Describe the solution you'd like**
It would be great if art supported the compat mode more directly, which would amount to changing `graph = tf.get_default_graph()` to `graph = tf.compat.v1.get_default_graph()` in my very specific problem, but it would be nice if that generalized across the entire art codebase.

**Describe alternatives you've considered**
To reproduce the issue, create venv with python3.7.12 and tensorflow 2.7.0 and run:
```
from art.estimators.classification import TFClassifier
import tensorflow.compat.v1 as tf
tf.disable_eager_execution()

input_ph = tf.placeholder(tf.float32, shape=[None, 28, 28, 1])
labels_ph = tf.placeholder(tf.int32, shape=[None, 10])
training_ph = tf.placeholder(tf.bool, shape=())

x = tf.layers.conv2d(input_ph, filters=4, kernel_size=(5, 5), activation=tf.nn.relu)
x = tf.layers.max_pooling2d(x, 2, 2)
x = tf.layers.conv2d(x, filters=10, kernel_size=(5, 5), activation=tf.nn.relu)
x = tf.layers.max_pooling2d(x, 2, 2)
x = tf.layers.flatten(x)
x = tf.layers.dense(x, 100, activation=tf.nn.relu)
logits = tf.layers.dense(x, 10)

loss = tf.reduce_mean(
    tf.losses.softmax_cross_entropy(logits=logits, onehot_labels=labels_ph)
)
optimizer = tf.train.AdamOptimizer(learning_rate=0.01)
train_op = optimizer.minimize(loss)
sess = tf.Session()
sess.run(tf.global_variables_initializer())


wrapped_model = TFClassifier(
    clip_values=(0.0, 1.0),
    input_ph=input_ph,
    output=logits,
    labels_ph=labels_ph,
    train=train_op,
    loss=loss,
    learning=training_ph,
    sess=sess
)
```

**Additional context**
@davidslater please feel free to add additional context.

**Comment by davidslater** [comment]
It looks like several of the tests are using `tf.compat.v1`, especially `tf.compat.v1.disable_eager_execution()`. However, there seems to be a huge amount of tensorflow-related code in the codebase (I didn't realize there was so much in there), so trying to get this to work on everything would be quite challenging, I think. 
```
adversarial-robustness-toolbox% grep -src tensorflow . | grep -v ':0$' | grep \.py: | wc -l
129
```
Not sure our best way forward.

**Comment by beat-buesser** [comment]
Hi @shenshaw26 and @davidslater I think your proposal is good. We have made a step towards support for compatibility mode in the past which introduced the CI runs with `tensorflow2v1` but I think it focused mainly on the object detection estimators. We'll try to update `TensorFlowClassifier` for ART 1.10.
