### ISSUE TITLE
Pixel Attack error if no rescale is needed

### ISSUE THREAD

**Issue by bunni90** [Trusted-AI/adversarial-robustness-toolbox#1571]
**Describe the bug**
The pixel attack (pixel_threshold.py) in ART 1.9.1 throws the error "AttributeError: 'PixelAttack' object has no
attribute 'rescale'" if you do not need to rescale.
Solution is to set self.rescale = False in the init, a pull request wil be created.

**To Reproduce**
1. Create a Classifier with clip_values=(0,255)
2. Initialize PixelAttack
3. Call generate()

**Expected behavior**
Expected to generate the attack.

**Screenshots**

**System information (please complete the following information):**
 - Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-91-generic x86_64)
 - Python3.8
 - ART 1.9.1
 - PyTorch 1.10.2 (should affect the other frameworks and versions aswell)

**Comment by beat-buesser** [comment]
Hi @bunni90 Thank you very much for noticing and reporting this bug!
