### ISSUE TITLE
art.estimators.classification.PyTorchClassifier: cloned classifier from `clone_for_refitting` still uses the optimizer which binds to original model's parameters

### ISSUE THREAD

**Issue by chao1995** [Trusted-AI/adversarial-robustness-toolbox#1579]
**Describe the bug**

I was using [ShadowModels](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/art/attacks/inference/membership_inference/shadow_models.py#L58) and found that the cloned model(s) was not getting trained while strangely the original model's parameters were updated, turns out that the optimizer still binds to the original model's parameters.

Below is how an optimizer is usually created:
```
optimizer = torch.optim.SGD(model.parameters(), lr=0.01, momentum=0.9)
```
And then the same optimizer was [assigned](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/a0c93362166e0e598545ea693d093e24b0c03655/art/estimators/classification/pytorch.py#L493) to the cloned classifier, which causes the issue.

**Suggested fix**
Currently I am using below workaround, which creates a new instance of the same type of optimizer:
```
shadow_models = ShadowModels(art_classifier, num_shadow_models=1)
for sm in shadow_models.get_shadow_models():
    new_optimizer = type(sm._optimizer)(sm.model.parameters())
    new_optimizer.load_state_dict(sm._optimizer.state_dict())
    sm._optimizer = new_optimizer
```

**System information (please complete the following information):**
 - OS: macOS
 - Python version: 3.8.10
 - ART version or commit number: 1.9.1
 - PyTorch version: 1.10.2

**Comment by beat-buesser** [comment]
Hi @chao1995 Thank you very much for opening this issue and providing a pull request to fix it! We'll take a closer look as soon as possible.
