### ISSUE TITLE
Bull's eye polytope attack not working properly 

### ISSUE THREAD

**Issue by Nathalie-B** [Trusted-AI/adversarial-robustness-toolbox#1594]
**Describe the bug**
Current implementation of the Bullseye polytope attack does not reproduce the expected behavior: attack doesn't work.

**Expected behavior**
Ensure the code works for non-sequential models. I recommend verifying the error still exists with the new ART version which contains a modified `get_activations` function and support for `non-sequential` models in Pytorch. 

**System information (please complete the following information):**
Test performed using a sequential Pytorch model. While trying to use the current implementation for a sequential model with CIFAR10, numbers in the original paper could not be reproduced

**Comment by beat-buesser** [comment]
Hi @Nathalie-B Thank you very much for reporting this issue!

**Comment by Swanand-Kadhe** [comment]
Hi @beat-buesser, I am interested to work on this issue. Could you please assign it to me? Many thanks!

**Comment by beat-buesser** [comment]
Hi @Swanand-Kadhe Thank you very much! Let me know if you have questions.
