### ISSUE TITLE
Inconsistent API for AdversarialTrainer

### ISSUE THREAD

**Issue by davidslater** [Trusted-AI/adversarial-robustness-toolbox#1609]
**Describe the bug**
https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/art/defences/trainer/adversarial_trainer_madry_pgd.py#L58

The standard API for ART `fit` method is to pass in `batch_size` as a kwargs:
https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/art/estimators/pytorch.py#L107
This is what is done in the FBF AdversarialTrainer API here:
https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/art/defences/trainer/adversarial_trainer_fbf_pytorch.py#L72

However, the Madry AdversarialTrainer sets batch_size in `__init__`:
https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/art/defences/trainer/adversarial_trainer_madry_pgd.py#L58
and then uses this value internally inside its `fit` method:
https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/art/defences/trainer/adversarial_trainer_madry_pgd.py#L105

**To Reproduce**
If you simply instantiate the Madry trainer and call `fit` with a `batch_size` kwarg, you'll get something like:
```
TypeError: new_fit() got multiple values for keyword argument 'batch_size'
```

**Expected behavior**
API should be consistent and `batch_size` should be set in `fit`, not `__init__`.

The fix is simple: move where `batch_size` is set.

**Comment by beat-buesser** [comment]
Hi @davidslater Thank you very much, I think that's a good idea!
