### ISSUE TITLE
Implementation of (De)Randomized Smoothing

### ISSUE THREAD

**Issue by GiulioZizzo** [Trusted-AI/adversarial-robustness-toolbox#1613]
(De)Randomized Smoothing,  https://arxiv.org/abs/2002.10733, is a simple yet highly effective method for certifying against patch attacks in neural networks. It has also recently been extended and shown to be very effective on Transformers (https://arxiv.org/abs/2110.07719) due to their ability to handle large masked images. Adding this feature to ART will be a valuable and important step in expanding the suite of certification methods offered.

**Comment by beat-buesser** [comment]
Hi @GiulioZizzo Thank you very much, I think (De)Randomized Smoothing will be a great addition to ART.
