### ISSUE TITLE
Update object detector _get_losses() to support mulitmodal inputs

### ISSUE THREAD

**Issue by lcadalzo** [Trusted-AI/adversarial-robustness-toolbox#1630]
**Is your feature request related to a problem? Please describe.**
I'm trying to run the AdversarialPatchPyTorch attack on a mulitmodal object detector that takes inputs with 6 channels.

**Describe the solution you'd like**
Updating [this](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/art/estimators/object_detection/python_object_detector.py#L217) line to include `6` in the list

**Comment by beat-buesser** [comment]
Hi @lcadalzo I think that's great proposal, we'll include it in ART 1.10.1.
