### ISSUE TITLE
Add 'targeted' attribute + input kwarg to adversarial_patch attack

### ISSUE THREAD

**Issue by lcadalzo** [Trusted-AI/adversarial-robustness-toolbox#1662]
**Is your feature request related to a problem? Please describe.**
Many/most attacks in ART take a `targeted` kwarg at construction and then set a `.targeted` attribute. Armory uses this attribute to determine whether an attack is targeted, and Armory also feeds in a `targeted` input to attacks at construction. If the `adversarial_patch` attack was consistent with other ART attacks (including `adversarial_patch_pytorch`) with regard to this, this would simplify things greatly on Armory's end.

**Describe the solution you'd like**
Modify the `__init__()` of `adversarial_patch` to take a `"targeted"` kwarg and set a `.targeted` attribute

**Comment by beat-buesser** [comment]
Hi @lcadalzo Thank you very much! I think this is a good idea to make the `targeted` argument consistent across attacks.
