### ISSUE TITLE
Minor errors on expectation over transformation notebook

### ISSUE THREAD

**Issue by anselmoferreira** [Trusted-AI/adversarial-robustness-toolbox#1673]
**Describe the bug**

There are some errors while running the notebook in https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/notebooks/expectation_over_transformation_classification_rotation.ipynb

The first one is that the following part is wrong

```
from art.classifiers import TensorFlowV2Classifier
```

It returns ModuleNotFoundError: No module named 'art.classifiers'

I could fix it in the following way

```
import art.estimators.classification as abc
 abc.TensorFlowV2Classifier()
```
The other error happens at the end of the notebook. The correction is below:

```
x_adv_eot = attack_eot.generate(x=np.expand_dims(x,axis=0), y=y_target)
```

**System information (please complete the following information):**
 - Linux
 - Python 3.8
 - ART 10.1
 - TensorFlow 2.4

**Comment by beat-buesser** [comment]
Hi @anselmoferreira Thank you very much for reporting this issue! I agree, the import for `TensorFlowV2Classifier` needs to be updated.

Would you be interested to make a pull request for the updated notebook?

**Comment by anselmoferreira** [comment]
> Hi @anselmoferreira Thank you very much for reporting this issue! I agree, the import for `TensorFlowV2Classifier` needs to be updated.
> 
> Would you be interested to make a pull request for the updated notebook?

Yes, I will. Just give me some time. Thank you!
