### ISSUE TITLE
attacks.evasion.carlini.CarliniLinf doesn't have attacks param `"batch_size"`

### ISSUE THREAD

**Issue by davidslater** [Trusted-AI/adversarial-robustness-toolbox#1679]
**Describe the bug**
`CarliniL0` and `CarliniL2` have the following attack params:
```
    attack_params = EvasionAttack.attack_params + [
        "confidence",
        "targeted",
        "learning_rate",
        "max_iter",
        "binary_search_steps",
        "initial_const",
        "max_halving",
        "max_doubling",
        "batch_size",
        "verbose",
    ]
```
`CarliniLinf` has all of those except `"batch_size"`

**Expected behavior**
I would have expected all of the attacks in that file to have the same params. However, looking at the implementation, it doesn't actually use `batch_size` as the other ones do.

So, this is probably more of a style decision.

**Comment by beat-buesser** [comment]
Hi @davidslater Thank you very much for suggesting this improvement! We'll add it with ART 1.10.2
