### ISSUE TITLE
PreprocessorPyTorch preprocessor cannot be used with PyTorchDeepSpeech class

### ISSUE THREAD

**Issue by davidslater** [Trusted-AI/adversarial-robustness-toolbox#1683]
**Describe the bug**
When a PreprocessorPyTorch preprocessor is added to the PyTorchDeepSpeech class, `predict` will error out with a trace similar to this (in this case, we were using Mp3CompressionPyTorch). (The problem also exists, I believe, in `loss_gradient`.)
```
    y_pred = self.model.predict(x, **self.predict_kwargs)
             │    │     │       │    │    └ {'transcription_output': True}
             │    │     │       │    └ <armory.scenarios.audio_asr.AutomaticSpeechRecognition object at 0x7ff113c87730>
             │    │     │       └ array([[ 0.0000000e+00, -3.0517578e-05,  3.0517578e-05, ...,
             │    │     │                 -1.2207031e-04, -1.2207031e-04, -9.1552734e-05]], dtype=...
             │    │     └ <function PyTorchDeepSpeech.predict at 0x7fefd3209940>
             │    └ PyTorchDeepSpeech(channels_first=None, model=DeepSpeech(
             │        (conv): MaskConv(
             │          (seq_module): Sequential(
             │            (0): Conv2d(...
             └ <armory.scenarios.audio_asr.AutomaticSpeechRecognition object at 0x7ff113c87730>

  File "/workspace/art/estimators/speech_recognition/pytorch_deep_speech.py", line 363, in predict
    x_preprocessed, _ = self._apply_preprocessing(x_in, y=None, fit=False)
                        │    │                    └ array([array([ 0.0000000e+00, -3.0517578e-05,  3.0517578e-05, ...,
                        │    │                                    -1.2207031e-04, -1.2207031e-04, -9.1552734e-...
                        │    └ <function PyTorchEstimator._apply_preprocessing at 0x7fefd97a6820>
                        └ PyTorchDeepSpeech(channels_first=None, model=DeepSpeech(
                            (conv): MaskConv(
                              (seq_module): Sequential(
                                (0): Conv2d(...

  File "/workspace/art/estimators/pytorch.py", line 214, in _apply_preprocessing
    x, y = preprocess(x, y)
    │      │          │  └ None
    │      │          └ array([array([ 0.0000000e+00, -3.0517578e-05,  3.0517578e-05, ..., 
    │      │                          -1.2207031e-04, -1.2207031e-04, -9.1552734e-...
    │      └ <art.defences.preprocessor.mp3_compression_pytorch.Mp3CompressionPyTorch object at 0x7fefd0c2cee0>
    └ array([array([ 0.0000000e+00, -3.0517578e-05,  3.0517578e-05, ...,
                    -1.2207031e-04, -1.2207031e-04, -9.1552734e-...

  File "/workspace/art/defences/preprocessor/preprocessor.py", line 196, in __call__
    x_tensor = torch.tensor(x, device=self.device)
               │     │      │         │    └ <property object at 0x7fefd32e2cc0>
               │     │      │         └ <art.defences.preprocessor.mp3_compression_pytorch.Mp3CompressionPyTorch object at 0x7fefd0c2cee0>
               │     │      └ array([array([ 0.0000000e+00, -3.0517578e-05,  3.0517578e-05, ...,
               │     │                      -1.2207031e-04, -1.2207031e-04, -9.1552734e-...
               │     └ <built-in method tensor of type object at 0x7ff0e1bc1e80>
               └ <module 'torch' from '/opt/conda/lib/python3.8/site-packages/torch/__init__.py'>

TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and boo
l.
```
This was produced in Armory using `armory run scenario_configs/librispeech_asr_imperceptible_defended.json --check` and is related to issue https://github.com/twosixlabs/armory/issues/1465 (it was found after resolving the Mp3Compression issue).

When the model calls `_apply_preprocessing(x_in, ...)`, it passes in a numpy object array. See: https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/art/estimators/speech_recognition/pytorch_deep_speech.py#L355

When in `art.estimators.pytorch.PyTorchEstimator`, `all_framework_preprocessing` is `True` but that path is not taking because `x.dtype == object` is `True` here: https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/art/estimators/pytorch.py#L169

That results in the second branch being taken and the standard `preprocess.__call__` function being called here (_with the numpy object input for `x`_), which passes it to the `PreprocessorPyTorch` base class: https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/art/estimators/pytorch.py#L209

This then fails when trying to cast the numpy object array as a torch tensor:
```
x_tensor = torch.tensor(x, device=self.device)
```
https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/art/defences/preprocessor/preprocessor.py#L196

**To Reproduce**

```
import numpy as np
from art.estimators.speech_recognition.pytorch_deep_speech import PyTorchDeepSpeech
from art.defences.preprocessor.mp3_compression_pytorch import Mp3CompressionPyTorch
sample_rate = 16000
defense = Mp3CompressionPyTorch(sample_rate)
model = PyTorchDeepSpeech(preprocessing_defences=[defense], pretrained_model="librispeech")
x = np.random.random((1, sample_rate))
model.predict(x)
```

**Expected behavior**
I expect it to simply predict correctly. This error only occurs when preprocessors are added.

There are two potential solutions:
1) The most direct (but one with potential ramifications) is to enable the `__call__` method of `PreprocessorPyTorch` to handle a numpy object array and loop through the inputs.
2) The second is more surgical. Update `PyTorchDeepSpeech` to check for `PreprocessorPyTorch` preprocessors and if present (and np type is object), loop through the inner objects and apply preprocessing to them one by one, similar to:
https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/art/estimators/speech_recognition/pytorch_deep_speech.py#L681-L686

**Comment by beat-buesser** [comment]
Hi @davidslater Thank you very much for raising the issue and providing the detailed description! I'll take a closer look following your description.
