### ISSUE TITLE
Bugs in knockoff_nets depending on the output of victim classifier and thieved classifier

### ISSUE THREAD

**Issue by KatsunariShishido** [Trusted-AI/adversarial-robustness-toolbox#1746]
**Describe the bug**
The program is aborted when calculating reward diverges to infinity, depends on the output of victim classifier and thieved classifier.

**To Reproduce**
There exists three patterns.
1. The victim classifier confidence diverges to infinity when the logit of victim classifier `y_output[0]` is large value in [knockoff_nets.py:L362](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/301df378b2fdcada23eebfdc8b8a502b018f9bf6/art/attacks/extraction/knockoff_nets.py#L362).
2. `np.log(probs_hat[k])` diverges to negative infinity when `probs_hat[k]` is zero in [knockoff_nets.py:L372](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/301df378b2fdcada23eebfdc8b8a502b018f9bf6/art/attacks/extraction/knockoff_nets.py#L372).
3. `(reward - self.reward_avg) / np.sqrt(self.reward_var)` diverges to infinity when `np.sqrt(self.reward_var)` is zero in [knockoff_nets.py:L394](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/301df378b2fdcada23eebfdc8b8a502b018f9bf6/art/attacks/extraction/knockoff_nets.py#L394).

**Expected behavior**
Attack runs.

**System information (please complete the following information):**
 - OS: Ubuntu18.04
 - Python version: 3.8
 - ART version or commit number: 1.10.3

**Comment by beat-buesser** [comment]
Hi @KatsunariShishido Thank you very much for using ART and reporting this issue! Would you have a specific script that reproduces the behaviors that we could use for testing?

**Comment by beat-buesser** [comment]
Hi @KatsunariShishido Thank you very much. I have been able to reproduce it. We'll aim to fix this with one of the upcoming releases.
