### ISSUE TITLE
Untargeted attack in AdversarialPatch don't work

### ISSUE THREAD

**Issue by DariaShel** [Trusted-AI/adversarial-robustness-toolbox#1767]
**Describe the bug**
If chose parameter _targeted=False_ in `__init__()`, then in function **generate** I get error `ValueError: Adversarial Patch attack requires target values y`

**To Reproduce**
1. Go to https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/art/attacks/evasion/adversarial_patch/adversarial_patch.py
2. Scroll down to 167 row
3. This error implies that the attack cannot be untargeted. But the presence of the targeted parameter says the opposite.

**System information (please complete the following information):**
 - OS Ubuntu 20.04.4 LTS
 - Python version 3.8.10
 - ART version or commit number 1.11.0
 - PyTorch

**Comment by beat-buesser** [comment]
Hi @DariaShel Thank you for raising this issue. I think you are right, we need to udpate that condition and let the internal attack `self._attack` decide if it can support untargeted attacks.
