### ISSUE TITLE
Bug in apply_patch function in Adversarial Patch PyTorch

### ISSUE THREAD

**Issue by DariaShel** [Trusted-AI/adversarial-robustness-toolbox#1770]
**Describe the bug**
In function **apply_patch()** np.ndarray _x_ convert to tensor in row 685: `x_tensor = torch.Tensor(x)` which suggests that the matrix should be on the cpu. (When I tried to pass _x.cuda()_ to the **apply_patch()** function, I got the corresponding error). Then _x_tensor_ is passed to the **_random_overlay()** function and in line 464: `patched_images = images * inverted_mask + padded_patch * image_mask` an error occurs: `RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!` because _inverted_mask_ on cuda device but _images_ on cpu. A similar error with variables _padded_patch_ and _image_mask_

**To Reproduce**
1. Go to https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/4e32899eb3de5a5e7185eff5e7c0ae04a9dd4c33/art/attacks/evasion/adversarial_patch/adversarial_patch_pytorch.py
2. See the lines that I indicated above

**System information (please complete the following information):**
- OS Ubuntu 20.04.4 LTS
- Python version 3.8.10
- ART version or commit number 1.11.0
- PyTorch

**Comment by beat-buesser** [comment]
Hi @DariaShel Thank you very much for raising this issue! It looks like `apply_patch` has only been tested on machines without GPUs. I think all 3 calls to `torch.Tensor(...)` in `apply_patch` have to be extended with `.to(self.estimator.device)`.

Would you be interested in opening a pull request for ART 1.11.1?

**Comment by DariaShel** [comment]
> Hi @DariaShel Thank you very much for raising this issue! It looks like `apply_patch` has only been tested on machines without GPUs. I think all 3 calls to `torch.Tensor(...)` in `apply_patch` have to be extended with `.to(self.estimator.device)`.
> 
> Would you be interested in opening a pull request for ART 1.11.1?

Yes, sure

**Comment by beat-buesser** [comment]
Great, thank you!
