### ISSUE TITLE
A metric that just launch an attack and return the success rate (or the model accuracy).

### ISSUE THREAD

**Issue by TS-Lee** [Trusted-AI/adversarial-robustness-toolbox#1775]
Adding a simple alias to repeated code that launch an attack and returns the success rate into https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/art/metrics/metrics.py can be useful.

It can be as simple as the following.

```
def empirical_robustness(
    classifier: "CLASSIFIER_TYPE",
    x: np.ndarray,
    attack_name: str,
    attack_params: Optional[Dict[str, Any]] = None,
) -> float:
    crafter = get_crafter(classifier, attack_name, attack_params)
    crafter.set_params(**{"minimal": True})
    adv_x = crafter.generate(x)

    # Predict the labels for adversarial examples
    y = classifier.predict(x)
    y_pred = classifier.predict(adv_x)

    idxs = np.argmax(y_pred, axis=1) != np.argmax(y, axis=1)
    return np.sum(idxs) / len(y)
```

This can make it explicit to use an attack to "measure" the robustness for attack-based testing.

**Comment by beat-buesser** [comment]
Hi @TS-Lee I think this could be very useful. I would suggest to call it `adversarial_accuracy` instead of `empirical_robustness`.

**Comment by TS-Lee** [comment]
Sure. I forgot to delete/change the function name when I copied and pasted the empirical_robustness code.
