### ISSUE TITLE
Dependency conflict in building Dockerfile

### ISSUE THREAD

**Issue by keode** [Trusted-AI/adversarial-robustness-toolbox#1789]
I'm trying to build the docker image via make build, but end up with the following error. How can I solve this? Thanks!

> ERROR: No matching distribution found for scipy==1.8.1 (from -r /project/requirements_test.txt (line 4))
> WARNING: You are using pip version 20.1; however, version 21.3.1 is available.
> You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
> The command '/bin/sh -c pip3 install --upgrade -r /project/requirements_test.txt' returned a non-zero code: 1
> make: *** [Makefile:7: build] Error 1

The whole log is below.

> ubuntu@ubuntu:/media/data/adversarial-robustness-toolbox$ make build
> docker build -t project-art-tf2 .
> Sending build context to Docker daemon    308MB
> Step 1/29 : FROM  tensorflow/tensorflow:2.2.0
>  ---> 6ca08e7b0d92
> Step 2/29 : RUN pip3 install keras==2.3.1
>  ---> Using cache
>  ---> 607601a7c4a7
> Step 3/29 : RUN pip3 install numpy==1.19.1 scipy==1.4.1 matplotlib==3.3.1 scikit-learn==0.22.2 six==1.15.0 Pillow==7.2.0 pytest-cov==2.10.1
>  ---> Using cache
>  ---> 7a94d77f555a
> Step 4/29 : RUN pip3 install tqdm==4.48.2 statsmodels==0.11.1 pydub==0.24.1 resampy==0.2.2 ffmpeg-python==0.2.0 cma==3.0.3 mypy==0.770
>  ---> Using cache
>  ---> bf655ccf75d3
> Step 5/29 : RUN pip3 install ffmpeg-python==0.2.0
>  ---> Using cache
>  ---> 0cfb8b7fdf1e
> Step 6/29 : RUN pip3 install pandas==1.1.1
>  ---> Using cache
>  ---> d19b0d9ea113
> Step 7/29 : RUN pip3 install jupyter==1.0.0 && pip3 install jupyterlab==2.1.0
>  ---> Using cache
>  ---> 666a534a8359
> Step 8/29 : RUN pip3 install h5py==2.10.0
>  ---> Using cache
>  ---> 4846cdba6ca9
> Step 9/29 : RUN pip3 install tensorflow-addons==0.11.1
>  ---> Using cache
>  ---> fdb998d606d0
> Step 10/29 : RUN pip3 install mxnet==1.6.0
>  ---> Using cache
>  ---> f146cbfd2e85
> Step 11/29 : RUN pip3 install torch==1.5.0 torchvision==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html
>  ---> Running in 3c3ef89cbbaa
> Looking in links: https://download.pytorch.org/whl/torch_stable.html
> Collecting torch==1.5.0
>   Downloading https://download.pytorch.org/whl/cu92/torch-1.5.0%2Bcu92-cp36-cp36m-linux_x86_64.whl (603.7 MB)
> Collecting torchvision==0.7.0
>   Downloading https://download.pytorch.org/whl/cu92/torchvision-0.7.0%2Bcu92-cp36-cp36m-linux_x86_64.whl (5.8 MB)
> Requirement already satisfied: future in /usr/local/lib/python3.6/dist-packages (from torch==1.5.0) (0.18.2)
> Requirement already satisfied: numpy in /usr/local/lib/python3.6/dist-packages (from torch==1.5.0) (1.19.1)
> Requirement already satisfied: pillow>=4.1.1 in /usr/local/lib/python3.6/dist-packages (from torchvision==0.7.0) (7.2.0)
> ERROR: torchvision 0.7.0+cu92 has requirement torch==1.6.0, but you'll have torch 1.5.0+cu92 which is incompatible.
> Installing collected packages: torch, torchvision
> Successfully installed torch-1.5.0+cu92 torchvision-0.7.0+cu92
> WARNING: You are using pip version 20.1; however, version 21.3.1 is available.
> You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
> Removing intermediate container 3c3ef89cbbaa
>  ---> c11c6a9e65c1
> Step 12/29 : RUN pip3 install catboost==0.24
>  ---> Running in ea142a0a075b
> Collecting catboost==0.24
>   Downloading catboost-0.24-cp36-none-manylinux1_x86_64.whl (65.9 MB)
> Requirement already satisfied: matplotlib in /usr/local/lib/python3.6/dist-packages (from catboost==0.24) (3.3.1)
> Requirement already satisfied: graphviz in /usr/local/lib/python3.6/dist-packages (from catboost==0.24) (0.8.4)
> Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.6/dist-packages (from catboost==0.24) (1.1.1)
> Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.6/dist-packages (from catboost==0.24) (1.19.1)
> Requirement already satisfied: scipy in /usr/local/lib/python3.6/dist-packages (from catboost==0.24) (1.4.1)
> Collecting plotly
>   Downloading plotly-5.9.0-py2.py3-none-any.whl (15.2 MB)
> Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from catboost==0.24) (1.15.0)
> Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.6/dist-packages (from matplotlib->catboost==0.24) (0.11.0)
> Requirement already satisfied: certifi>=2020.06.20 in /usr/local/lib/python3.6/dist-packages (from matplotlib->catboost==0.24) (2022.6.15)
> Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.6/dist-packages (from matplotlib->catboost==0.24) (7.2.0)
> Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib->catboost==0.24) (2.8.2)
> Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in /usr/local/lib/python3.6/dist-packages (from matplotlib->catboost==0.24) (3.0.9)
> Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib->catboost==0.24) (1.3.1)
> Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.24.0->catboost==0.24) (2022.1)
> Collecting tenacity>=6.2.0
>   Downloading tenacity-8.0.1-py3-none-any.whl (24 kB)
> Installing collected packages: tenacity, plotly, catboost
> Successfully installed catboost-0.24 plotly-5.9.0 tenacity-8.0.1
> WARNING: You are using pip version 20.1; however, version 21.3.1 is available.
> You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
> Removing intermediate container ea142a0a075b
>  ---> 5f114efbf44f
> Step 13/29 : RUN pip3 install GPy==1.9.9
>  ---> Running in bef52abf80d6
> Collecting GPy==1.9.9
>   Downloading GPy-1.9.9.tar.gz (995 kB)
> Requirement already satisfied: numpy>=1.7 in /usr/local/lib/python3.6/dist-packages (from GPy==1.9.9) (1.19.1)
> Requirement already satisfied: scipy>=0.16 in /usr/local/lib/python3.6/dist-packages (from GPy==1.9.9) (1.4.1)
> Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from GPy==1.9.9) (1.15.0)
> Collecting paramz>=0.9.0
>   Downloading paramz-0.9.5.tar.gz (71 kB)
> Requirement already satisfied: decorator>=4.0.10 in /usr/local/lib/python3.6/dist-packages (from paramz>=0.9.0->GPy==1.9.9) (5.1.1)
> Building wheels for collected packages: GPy, paramz
>   Building wheel for GPy (setup.py): started
>   Building wheel for GPy (setup.py): still running...
>   Building wheel for GPy (setup.py): finished with status 'done'
>   Created wheel for GPy: filename=GPy-1.9.9-cp36-cp36m-linux_x86_64.whl size=2633988 sha256=9910fe3b2936ea49d769d9b1651f22d02065500e16745711f1cf5f877c052a33
>   Stored in directory: /root/.cache/pip/wheels/1c/b9/22/3c8a2f0294d140333f6610f075eaf5f22508b2ba154e487a23
>   Building wheel for paramz (setup.py): started
>   Building wheel for paramz (setup.py): finished with status 'done'
>   Created wheel for paramz: filename=paramz-0.9.5-py3-none-any.whl size=102716 sha256=82690dca4c60f595576e6258bc275948f5a162c5b05f3644b61030ef6641111e
>   Stored in directory: /root/.cache/pip/wheels/72/d5/80/7921b405df363b0f10446fc93491092c20bc75491cbbd0a354
> Successfully built GPy paramz
> Installing collected packages: paramz, GPy
> Successfully installed GPy-1.9.9 paramz-0.9.5
> WARNING: You are using pip version 20.1; however, version 21.3.1 is available.
> You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
> Removing intermediate container bef52abf80d6
>  ---> 33c6d79fa8ea
> Step 14/29 : RUN pip3 install lightgbm==2.3.1
>  ---> Running in 79640ddcd943
> Collecting lightgbm==2.3.1
>   Downloading lightgbm-2.3.1-py2.py3-none-manylinux1_x86_64.whl (1.2 MB)
> Requirement already satisfied: numpy in /usr/local/lib/python3.6/dist-packages (from lightgbm==2.3.1) (1.19.1)
> Requirement already satisfied: scikit-learn in /usr/local/lib/python3.6/dist-packages (from lightgbm==2.3.1) (0.22.2)
> Requirement already satisfied: scipy in /usr/local/lib/python3.6/dist-packages (from lightgbm==2.3.1) (1.4.1)
> Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.6/dist-packages (from scikit-learn->lightgbm==2.3.1) (1.1.0)
> Installing collected packages: lightgbm
> Successfully installed lightgbm-2.3.1
> WARNING: You are using pip version 20.1; however, version 21.3.1 is available.
> You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
> Removing intermediate container 79640ddcd943
>  ---> 6671880c6652
> Step 15/29 : RUN pip3 install xgboost==1.1.1
>  ---> Running in 65d21480f651
> Collecting xgboost==1.1.1
>   Downloading xgboost-1.1.1-py3-none-manylinux2010_x86_64.whl (127.6 MB)
> Requirement already satisfied: numpy in /usr/local/lib/python3.6/dist-packages (from xgboost==1.1.1) (1.19.1)
> Requirement already satisfied: scipy in /usr/local/lib/python3.6/dist-packages (from xgboost==1.1.1) (1.4.1)
> Installing collected packages: xgboost
> Successfully installed xgboost-1.1.1
> WARNING: You are using pip version 20.1; however, version 21.3.1 is available.
> You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
> Removing intermediate container 65d21480f651
>  ---> 2d277f726c77
> Step 16/29 : RUN pip3 install kornia==0.3.1
>  ---> Running in 894adcaf9d86
> Collecting kornia==0.3.1
>   Downloading kornia-0.3.1-py2.py3-none-any.whl (158 kB)
> Requirement already satisfied: numpy in /usr/local/lib/python3.6/dist-packages (from kornia==0.3.1) (1.19.1)
> Requirement already satisfied: torch==1.5.0 in /usr/local/lib/python3.6/dist-packages (from kornia==0.3.1) (1.5.0+cu92)
> Requirement already satisfied: future in /usr/local/lib/python3.6/dist-packages (from torch==1.5.0->kornia==0.3.1) (0.18.2)
> Installing collected packages: kornia
> Successfully installed kornia-0.3.1
> WARNING: You are using pip version 20.1; however, version 21.3.1 is available.
> You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
> Removing intermediate container 894adcaf9d86
>  ---> 9288dff6b469
> Step 17/29 : RUN pip3 install lief==0.11.4
>  ---> Running in 281ed28b3c02
> Collecting lief==0.11.4
>   Downloading lief-0.11.4-cp36-cp36m-manylinux1_x86_64.whl (3.2 MB)
> Installing collected packages: lief
> Successfully installed lief-0.11.4
> WARNING: You are using pip version 20.1; however, version 21.3.1 is available.
> You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
> Removing intermediate container 281ed28b3c02
>  ---> e28d555df953
> Step 18/29 : RUN pip3 install pytest==5.4.1 pytest-pep8==1.0.6 pytest-mock==3.2.0 codecov==2.1.8 requests==2.24.0
>  ---> Running in 9c55eeee0462
> Collecting pytest==5.4.1
>   Downloading pytest-5.4.1-py3-none-any.whl (246 kB)
> Collecting pytest-pep8==1.0.6
>   Downloading pytest-pep8-1.0.6.tar.gz (7.3 kB)
> Collecting pytest-mock==3.2.0
>   Downloading pytest_mock-3.2.0-py3-none-any.whl (10 kB)
> Collecting codecov==2.1.8
>   Downloading codecov-2.1.8-py2.py3-none-any.whl (16 kB)
> Collecting requests==2.24.0
>   Downloading requests-2.24.0-py2.py3-none-any.whl (61 kB)
> Requirement already satisfied: py>=1.5.0 in /usr/local/lib/python3.6/dist-packages (from pytest==5.4.1) (1.11.0)
> Requirement already satisfied: wcwidth in /usr/local/lib/python3.6/dist-packages (from pytest==5.4.1) (0.2.5)
> Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.6/dist-packages (from pytest==5.4.1) (21.4.0)
> Collecting more-itertools>=4.0.0
>   Downloading more_itertools-8.13.0-py3-none-any.whl (51 kB)
> Collecting pluggy<1.0,>=0.12
>   Downloading pluggy-0.13.1-py2.py3-none-any.whl (18 kB)
> Requirement already satisfied: importlib-metadata>=0.12; python_version < "3.8" in /usr/local/lib/python3.6/dist-packages (from pytest==5.4.1) (4.8.3)
> Requirement already satisfied: packaging in /usr/local/lib/python3.6/dist-packages (from pytest==5.4.1) (21.3)
> Collecting pytest-cache
>   Downloading pytest-cache-1.0.tar.gz (16 kB)
> Collecting pep8>=1.3
>   Downloading pep8-1.7.1-py2.py3-none-any.whl (41 kB)
> Requirement already satisfied: coverage in /usr/local/lib/python3.6/dist-packages (from codecov==2.1.8) (6.2)
> Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests==2.24.0) (3.0.4)
> Requirement already satisfied: idna<3,>=2.5 in /usr/lib/python3/dist-packages (from requests==2.24.0) (2.6)
> Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests==2.24.0) (2022.6.15)
> Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests==2.24.0) (1.25.9)
> Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.6/dist-packages (from importlib-metadata>=0.12; python_version < "3.8"->pytest==5.4.1) (3.6.0)
> Requirement already satisfied: typing-extensions>=3.6.4; python_version < "3.8" in /usr/local/lib/python3.6/dist-packages (from importlib-metadata>=0.12; python_version < "3.8"->pytest==5.4.1) (4.1.1)
> Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.6/dist-packages (from packaging->pytest==5.4.1) (3.0.9)
> Collecting execnet>=1.1.dev1
>   Downloading execnet-1.9.0-py2.py3-none-any.whl (39 kB)
> Building wheels for collected packages: pytest-pep8, pytest-cache
>   Building wheel for pytest-pep8 (setup.py): started
>   Building wheel for pytest-pep8 (setup.py): finished with status 'done'
>   Created wheel for pytest-pep8: filename=pytest_pep8-1.0.6-py3-none-any.whl size=7528 sha256=a093f66b8a97f97da5b87ea75ac8a35397f827cb6dbd223ac298694b5b00dcc5
>   Stored in directory: /root/.cache/pip/wheels/23/d5/e6/a0e3991c566924ea7fbc5a174c8e8ddf2c40bcb41ae32bdcb9
>   Building wheel for pytest-cache (setup.py): started
>   Building wheel for pytest-cache (setup.py): finished with status 'done'
>   Created wheel for pytest-cache: filename=pytest_cache-1.0-py3-none-any.whl size=8773 sha256=0d10e35c58dbf850d7b798da42a39eeca46854ce95c36215f933faad5ca8f0b8
>   Stored in directory: /root/.cache/pip/wheels/1a/af/c9/28c17870e142169f9f10ded868d34f1119a1aa2321d31f05d6
> Successfully built pytest-pep8 pytest-cache
> Installing collected packages: more-itertools, pluggy, pytest, execnet, pytest-cache, pep8, pytest-pep8, pytest-mock, requests, codecov
>   Attempting uninstall: pluggy
>     Found existing installation: pluggy 1.0.0
>     Uninstalling pluggy-1.0.0:
>       Successfully uninstalled pluggy-1.0.0
>   Attempting uninstall: pytest
>     Found existing installation: pytest 7.0.1
>     Uninstalling pytest-7.0.1:
>       Successfully uninstalled pytest-7.0.1
>   Attempting uninstall: requests
>     Found existing installation: requests 2.23.0
>     Uninstalling requests-2.23.0:
>       Successfully uninstalled requests-2.23.0
> Successfully installed codecov-2.1.8 execnet-1.9.0 more-itertools-8.13.0 pep8-1.7.1 pluggy-0.13.1 pytest-5.4.1 pytest-cache-1.0 pytest-mock-3.2.0 pytest-pep8-1.0.6 requests-2.24.0
> WARNING: You are using pip version 20.1; however, version 21.3.1 is available.
> You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
> Removing intermediate container 9c55eeee0462
>  ---> 96514a4b8238
> Step 19/29 : RUN mkdir /project; mkdir /project/TMP
>  ---> Running in 352bcbb3074e
> Removing intermediate container 352bcbb3074e
>  ---> a58d427573e6
> Step 20/29 : VOLUME /project/TMP
>  ---> Running in 0b996a490631
> Removing intermediate container 0b996a490631
>  ---> 8c1e322e63e4
> Step 21/29 : WORKDIR /project
>  ---> Running in a6b565d30005
> Removing intermediate container a6b565d30005
>  ---> 11378969dd0e
> Step 22/29 : ADD . /project/
>  ---> 77df1ac53137
> Step 23/29 : RUN pip3 install --upgrade -r /project/requirements_test.txt
>  ---> Running in fa787074ecf5
> Looking in links: https://download.pytorch.org/whl/cpu/torch_stable.html
> Obtaining file:///project (from -r /project/requirements_test.txt (line 62))
>   Installing build dependencies: started
>   Installing build dependencies: finished with status 'done'
>   Getting requirements to build wheel: started
>   Getting requirements to build wheel: finished with status 'done'
>     Preparing wheel metadata: started
>     Preparing wheel metadata: finished with status 'done'
> Collecting numpy>=1.18.5
>   Downloading numpy-1.19.5-cp36-cp36m-manylinux2010_x86_64.whl (14.8 MB)
> ERROR: Could not find a version that satisfies the requirement scipy==1.8.1 (from -r /project/requirements_test.txt (line 4)) (from versions: 0.8.0, 0.9.0, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 1.0.0, 1.0.1, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.3.0rc1, 1.3.0rc2, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0rc1, 1.4.0rc2, 1.4.0, 1.4.1, 1.5.0rc1, 1.5.0rc2, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4)
> ERROR: No matching distribution found for scipy==1.8.1 (from -r /project/requirements_test.txt (line 4))
> WARNING: You are using pip version 20.1; however, version 21.3.1 is available.
> You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
> The command '/bin/sh -c pip3 install --upgrade -r /project/requirements_test.txt' returned a non-zero code: 1
> make: *** [Makefile:7: build] Error 1
>

**Comment by beat-buesser** [comment]
Hi @keode Thank you very much for raising this issue! I think the Dockerfile hasn't been testes for a while now. I think the error is caused by a conflict of Python 3.6 with scipy==1.8.1. Can you try updating the docker file to start from `tensorflow/tensorflow:2.9.1` instead of `tensorflow/tensorflow:2.2.0` in the first line?

There might be other lines requiring updates.

**Comment by keode** [comment]
Hi @beat-buesser Thanks a lot for your prompt reply. After changing the parent image from tensorflow:2.2.0 to tensorflow:2.9.1, I was able to build the image without error. But importing art would fail from within the container bash (entered via make run-bash), giving the error "numba needs numpy 1.22 or less". So I change numpy>=1.18.5 to numpy>=1.18.5,<1.22 in requirements_test.txt to resolve the issue.

**Comment by beat-buesser** [comment]
Hi @keode That's great news, thank you very much! Would you be interested to open a pull request with your updated Dockerfile?

**Comment by keode** [comment]
@beat-buesser Sure, my pleasure.

**Comment by beat-buesser** [comment]
@keode Amazing! Please let me know if you need anything for the PR.
