### ISSUE TITLE
Implementation of Certified Training based on IBP Methods

### ISSUE THREAD

**Issue by GiulioZizzo** [Trusted-AI/adversarial-robustness-toolbox#1806]
**Is your feature request related to a problem? Please describe.**
Certified training for Abstract Interpretation/Interval bound propagation methods have been shown to boost the achievable certified performance. Adding these to ART can provide useful tools for building and developing certified defences. 

**Describe the solution you'd like**
Implementation of interval based loss functions (eg such as those found in "On the effectiveness of interval bound propagation for training verifiably robust models") and associated training methods.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by beat-buesser** [comment]
Hi @GiulioZizzo Thank you for proposing this new certification feature!
