### ISSUE TITLE
Implementation of DP-InstaHide and Data Augmentation Defenses

### ISSUE THREAD

**Issue by f4str** [Trusted-AI/adversarial-robustness-toolbox#1827]
**Is your feature request related to a problem? Please describe.**
Mixup, CutOut, CutMix, and Maxup are relatively simple data augmentation defenses that have been shown to provide robustness against poisoning attacks. ART currently does not have any data augmentation defenses so this implementation will provide more features and open the doors for additional data augmentation defenses. DP-InstaHide is a relatively simple training method that utilizes data augmentation defenses and has privacy guarantees. This implementation will be a good utilization of the data augmentation defenses and provide another useful tool to ART.

**Describe the solution you'd like**
Implementation of data augmentation defenses would involve creation of the `data_augmentation` submodule under `art.defenses.preprocessor`. Here, an abstract class for data augmentation would be created that follows the same structure as the preprocessor defenses. This abstract class would then be extended to create defenses for `Mixup`, `CutOut`, `CutMix`, and `Maxup` for the four main data augmentation defenses used with DP-InstaHide.

Implementation of DP-InstaHide would involve creating a new trainer under `art.defenses.trainer` which would run similarly to the adversarial trainer. This would take parameters to specify the type of data augmentation defense along with the hyperparameters.

**Describe alternatives you've considered**
Originally, the idea was to have `data_augmentation` be its own submodule under `art.defenses` rather than a type of preprocessor. However, after some thought and discussion, the data augmentation defenses should be a submodule under `art.defenses.preprocessor`.

**Additional context**
It might be worth splitting this into two separate issues for organization purposes. One for the implementation of data augmentation defenses and another for the implementation of DP-InstaHide.

**Comment by beat-buesser** [comment]
Hi @f4str Thank you very much for proposing this new feature! I think it will of interest for many users of ART!
