### ISSUE TITLE
Remove max version constraint from scikit-learn

### ISSUE THREAD

**Issue by davidslater** [Trusted-AI/adversarial-robustness-toolbox#1874]
**Is your feature request related to a problem? Please describe.**
Currently, scikit-learn requires version < 1.1.0. This constraint seems unnecessary, and none of the other basic requirements have max version limitations.
https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/setup.py#L12

**Describe the solution you'd like**
Simply remove the second part of the requirement:
`    "scikit-learn>=0.22.2,<1.1.0",` --> `    "scikit-learn>=0.22.2",`

**Describe alternatives you've considered**
If there is a clear reason or breaking change in version 1.1.0, I can see it making sense. In that case, can you document it with a comment in the `setup.py`?

**Comment by beat-buesser** [comment]
Hi @davidslater I think this should be possible, we'll test and update it. It got added in an earlier version to limit newer versions of `sklearn` from being used automatically before testing because they sometimes changed internals of their models, etc.

**Comment by davidslater** [comment]
Gotcha, that makes sense.

**Comment by beat-buesser** [comment]
I started with this issue and noticed we are already on `scikit-learn>=0.22.2,<1.2.0` allowing all patch releases of scikit-learn 1.1. We'll keep continuously updating it.
