### ISSUE TITLE
Make numba an optional dependency

### ISSUE THREAD

**Issue by davidslater** [Trusted-AI/adversarial-robustness-toolbox#1875]
**Is your feature request related to a problem? Please describe.**
Currently, `numba` is a required dependency: https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/setup.py#L16
However, it is only used in a single file: https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/art/attacks/evasion/brendel_bethge.py
This seems a bit overkill for dependency management.

**Describe the solution you'd like**
Move numba to an optional requirement below in `extras_require`,
https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/setup.py#L66

This would require some sort of ImportError catching in https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/art/attacks/evasion/__init__.py , but that would be pretty straightforward.

**Comment by beat-buesser** [comment]
Hi @davidslater Thank you for the suggestion! I agree, I have noticed recently conflicts with most recent versions of Numpy. I'll make `numba` an optional dependency for now.
