### ISSUE TITLE
Miscalculation on accuracy of poisoned datasets in clean labels

### ISSUE THREAD

**Issue by dujiaode** [Trusted-AI/adversarial-robustness-toolbox#1876]
When calculating the accuracy of the poisoning dataset, the denominator is the number of the entire test set (y_test.shape[0]
) instead of the total number of poisoned datasets (py_test[0])
The problem link is:
https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/notebooks/poisoning_attack_clean_label_backdoor.ipynb

The code in question is:
clean_total = y_test.shape[0]

**Comment by beat-buesser** [comment]
Hi @dujiaode Thank you very much for raising this issue, we'll investigate as soon as possible.
