### ISSUE TITLE
attack_params such as verbose and batch_size not passed in Universal Perturbation.

### ISSUE THREAD

**Issue by adityagupta1089** [Trusted-AI/adversarial-robustness-toolbox#1895]
https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/46b66e66ab95172fd8ed316feb75e5ff70627668/art/attacks/evasion/universal_perturbation.py#L177

For e.g. DeepFool still uses `batch_size=1` and `verbose=True` if `UniversalPerturbation(verbose=False, batch_size=512)` is used. Could also be the reason for performance degradation when not used directly.

**Comment by beat-buesser** [comment]
Hi @adityagupta1089 Thank you very much for using ART! Would you be able to share an example code showing how to reproduce your observation?

**Comment by adityagupta1089** [comment]
I think I might have confused the API, seems like the params for the top-level function UniversalPerturbation (batch_size, verbose) are different from the sub-attacker (DeepFool: batch_size, verbose). 

Depends if this is an intended use case or if keeping the batch_size and verbosity for both makes more sense.

Feel free to close this if former.

**Comment by beat-buesser** [comment]
@adityagupta1089 Thank you for the updates!
