### ISSUE TITLE
How to load .model and .optimizer file for load pytorch model?

### ISSUE THREAD

**Issue by telemorne** [Trusted-AI/adversarial-robustness-toolbox#1898]
### Discussed in https://github.com/Trusted-AI/adversarial-robustness-toolbox/discussions/1308

<div type='discussions-op-text'>

<sup>Originally posted by **LxyoryxL** September 12, 2021</sup>
![image](https://user-images.githubusercontent.com/35552946/132969956-8a24a675-3906-4a2f-8109-390025fe9af2.png)
The `.model` and `.Optimizer` files above are the ones I saved with `pytorch_model.save()` functions,but I don't know how to load them again  </div>

**Comment by beat-buesser** [comment]
Closing issue to continue in Discussion #1308.
