### ISSUE TITLE
Sleeper Agent get_poison_indices() may return stale array

### ISSUE THREAD

**Issue by swsuggs** [Trusted-AI/adversarial-robustness-toolbox#1952]
**Describe the bug**

In Sleeper Agent, ```get_poison_indices()``` returns ```self.indices_poison``` ([link](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/c226388533f0029d03f2c40bdd9a4e7b853e5f30/art/attacks/poisoning/sleeper_agent_attack.py#L277)); however, the poisoning procedure does not update this variable to the final indices used.

**Details**

This attack makes ```max_trials``` [attempts](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/c226388533f0029d03f2c40bdd9a4e7b853e5f30/art/attacks/poisoning/sleeper_agent_attack.py#L200-L236) to poison the data.  Each time, a new ```self.indices_poison``` is sampled (L201-208).  If this attempt is the most successful so far, then ```best_indices_poison``` is set to ```self.indices_poison``` (L231).  But at the end of all the trials, ```self.indices_poison``` still points to the indices from the latest attempt, even if the best attempt was earlier.

**Expected behavior**

At the end of the poisoning loop, after all poisoning attempts are complete (L237), set ```self.indices_poison = best_indices_poison```.

**Comment by monshri** [comment]
Submitted PR with the fix discussed with Sterling - [`1952`](https://github.com/Trusted-AI/adversarial-robustness-toolbox/pull/1955)
