### ISSUE TITLE
Update version of scikit-learn in setup.py and CI yml files

### ISSUE THREAD

**Issue by beat-buesser** [Trusted-AI/adversarial-robustness-toolbox#1953]
### Discussed in https://github.com/Trusted-AI/adversarial-robustness-toolbox/discussions/1950

<div type='discussions-op-text'>

<sup>Originally posted by **sr1998** December  3, 2022</sup>
Hi, is it possible for the library to support newer versions of scikit-learn? At the moment it supports scikit-learn<1.1.0,>=0.22.2  but I also tested part of ART with scikit-learn 1.1.2 and it works like a charm. The question is of course whether everything will keep working which you know better of course. 

I hope support for newer versions of scikit-learn, at least 1.1.2 for me, is possible in the near future. I look forward to any reply.</div>

**Comment by jamesmyatt** [comment]
1.2.x and 1.3.x have also been released in the meantime
