### ISSUE TITLE
DeepZ Certification: No default value for reshape_op_num 

### ISSUE THREAD

**Issue by GiulioZizzo** [Trusted-AI/adversarial-robustness-toolbox#1973]
**Describe the bug**
There is currently no default value provided in self.reshape_op_num for ConvertedModel.
This can case a bug in forward/abstract_forward is a pure dense network is supplied

**To Reproduce**
Create a dense neural network, supply it to PytorchDeepZ, and run predict_zonotopes. 

**Expected behavior**
The estimator should  do a forward pass. However, with no reshape_op_num it will crash.

**System information (please complete the following information):**
 - OS: Mac
 - Python version: 3.8
 - ART version or commit number: 1.12
 - PyTorch 1.13

**Comment by beat-buesser** [comment]
Hi @GiulioZizzo Thank you very much for reporting and fixing this bug!
