### ISSUE TITLE
categorical feature support

### ISSUE THREAD

**Issue by ghost** [Trusted-AI/adversarial-robustness-toolbox#199]
I have a dataset with categorical features (non-image data). After binarizing them and training a model, I need to create adversarial samples on some test dataset samples using any ART supported attack. Adversarial samples are created with continuous values.
I suggest adding support for categorical features, e.g. binarizing selected features after creating the adversarial samples by {0:<.5,1:else}.

**Comment by beat-buesser** [comment]
Hi @ggh96 Thank you for using ART and the great user feedback by making a great suggestion! We have been thinking about supporting categorical features in the past but didn't have the resources to implement it so far.

It looks like you have a solution for categorical features outside of ART. Would you be interested to work on implementing it as part of ART?

**Comment by ggh96** [comment]
Currently working on a attack independent solution. My solution is local. Will pull once ready.

**Comment by quinlivanb** [comment]
Hey, @ggh96, I would also be interested in this functionality, could you share your progress?
