### ISSUE TITLE
YOLO Object Detection Estimator for TensorFlow

### ISSUE THREAD

**Issue by f4str** [Trusted-AI/adversarial-robustness-toolbox#1996]
**Is your feature request related to a problem? Please describe.**
The current YOLO object detection estimator only has an implementation for PyTorch. There is no YOLO estimator for TensorFlow.

**Describe the solution you'd like**
An implementation of the YOLO object detection estimator for TensorFlow similar to the current PyTorch implementation. This should be located in `art.estimators.object_detection.pytorch_object_detector` and have the class name `TensorFlowV2Yolo` following the current conventions.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by beat-buesser** [comment]
Hi @f4str This sounds good. Which versions of YOLO do you plan to support?
