### ISSUE TITLE
Audio perturbations go out of range 

### ISSUE THREAD

**Issue by swsuggs** [Trusted-AI/adversarial-robustness-toolbox#2002]
**Describe the bug**
In the audio perturbation code for poisoning, it is possible for the range of the audio sample to exceed [-1,1] after the trigger is added.  See line 80 ([insert_tone_trigger](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/111578f10af3295e72c31bd20c20d8c71d8bb8ec/art/attacks/poisoning/perturbations/audio_perturbations.py#L80)) and line 147 ([insert_audio_trigger](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/111578f10af3295e72c31bd20c20d8c71d8bb8ec/art/attacks/poisoning/perturbations/audio_perturbations.py#L147))

**Expected behavior**
The output should remain within the valid range.  This can be fixed with ```audio = np.clip(audio, -1.0, 1.0)``` following each line linked above

**Comment by swsuggs** [comment]
@Swanand-Kadhe could you take a look at this?

**Comment by beat-buesser** [comment]
Hi @swsuggs Thank you very much for reporting this issue!

**Comment by Swanand-Kadhe** [comment]
Hi @swsuggs, thanks a lot for finding and reporting this issue! I will take a look and work on the fix. 
Hi @beat-buesser, I will keep you posted. Many thanks!
