### ISSUE TITLE
Audio perturbation code should cache the trigger

### ISSUE THREAD

**Issue by swsuggs** [Trusted-AI/adversarial-robustness-toolbox#2052]
**Is your feature request related to a problem? Please describe.**
In the audio perturbation code for backdoor poisoning, [librosa.load() is called](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/ee0c4b6c165157f5a65799a0b92a9de6634f62a9/art/attacks/poisoning/perturbations/audio_perturbations.py#L125) once per sample, even if the samples are batched.  This function seems a bit inefficient; we observed it to take around 2.5 seconds per call, which becomes impractical when poisoning hundreds or thousands of samples.

**Describe the solution you'd like**
It is much faster to load the trigger from disk only once, and store it for subsequent poisonings.  I have been using a variation of this code which employs a class to save the loaded trigger.  I have submitted this variation as a candidate solution in #2053.

**Comment by beat-buesser** [comment]
Hiu @swsuggs Thank you very much for proposing and implementing this feature!
