### ISSUE TITLE
Questions for robust decision tree.

### ISSUE THREAD

**Issue by hin1115** [Trusted-AI/adversarial-robustness-toolbox#2087]
I really appreciate your implementation.   
I found a some attack method for various decision trees.    
And now I'm trying to find some robust decision tree models against adversarial attack.    
I found some defense method against poisoning attack, but I'm not sure they're compatible with decision trees.    
Is there any robust decision tree models against adversarial attack?

**Comment by beat-buesser** [comment]
Hi @hin1115 We have an open discussion on this topic:https://github.com/Trusted-AI/adversarial-robustness-toolbox/discussions/2060
