### ISSUE TITLE
AdversarialPatchPyTorch does not work with pytorch 2.0.0

### ISSUE THREAD

**Issue by Shacharshm** [Trusted-AI/adversarial-robustness-toolbox#2095]
the problem seems to be that when AdversarialPatchPyTorch checks the torch version it checks if torch version is above 1.7.0 but doesn't take in to account that the 0 of 2.0.0 is above the 7 of 1.7.0.

thanks in advanced.

**Comment by beat-buesser** [comment]
Hi @Shacharshm PyTorch 2.0 is not yet supported by ART but we plan to add support soon.

**Comment by swsuggs** [comment]
@beat-buesser  The [code](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/d835ef359578521f6a509e874c0b3840fa86cc08/art/attacks/evasion/adversarial_patch/adversarial_patch_pytorch.py#LL126C9-L126C112) is incorrect in any case:
```
torch_version = list(map(int, torch.__version__.lower().split("+", maxsplit=1)[0].split(".")))
assert torch_version[0] >= 1 and torch_version[1] >= 7, "AdversarialPatchPyTorch requires torch>=1.7.0"
```
The assertion will rule out all versions where the second digit is lower than 7; this does not seem to be the intended behavior.

**Comment by beat-buesser** [comment]
@swsuggs Thank you very much!
