### ISSUE TITLE
Implement semantic adversarial attacks

### ISSUE THREAD

**Issue by sarathknv** [Trusted-AI/adversarial-robustness-toolbox#2126]
These are adversarial images that semantically represent the same object as the original images. For example, in [2] these are created by perturbing the following components of an image:
* Hue
* Saturation
* Rotation
* Brightness
* Contrast

Would these be of interest? If yes, I can implement them for ART.

My implementation: https://github.com/sarathknv/adversarial-examples-pytorch/tree/master/semantic_adversarial_examples

Papers:
1. [Semantic Adversarial Examples](https://arxiv.org/pdf/1804.00499.pdf) (CVPR Workshops 2018)
2. [Towards Compositional Adversarial Robustness: Generalizing Adversarial Training to Composite Semantic Perturbations](https://arxiv.org/pdf/2202.04235.pdf) (CVPR 2023)

**Comment by beat-buesser** [comment]
Hi @sarathknv Sorry for the delayed response. Yes, these attacks would be very interesting for ART and you are very welcome to implement them in ART. Are you already familiar with the architecture of ART?
