### ISSUE TITLE
Adversarial Patch attack is not working in **attack_adversarial_patch_pytorch_yolo.ipynb**

### ISSUE THREAD

**Issue by Tmoxic** [Trusted-AI/adversarial-robustness-toolbox#2197]
I used yolov5 to perform the adversarial patch attack for object detection with my own trained weight which was trained on Dior Dataset, I followed the steps described in "attack_adversarial_patch_pytorch_yolo.ipynb", but the output image does not affect the detection result, as can be seen from the image showing below. 
![Screenshot from 2023-06-20 15-07-52](https://github.com/Trusted-AI/adversarial-robustness-toolbox/assets/133834709/b25b454c-afd8-41fc-bd5f-3ec7f5a73f24)

**Comment by Foxglove144** [comment]
Try setting targeted=False and also playing around with the patch location. Maybe (100, 100)

**Comment by Tmoxic** [comment]
> Try setting `targeted=False` and also playing around with the `patch_location`. Maybe try `patch_location=(100, 100)`

Thank you so much, I will give it a try.

**Comment by Tmoxic** [comment]
> Try setting `targeted=False` and also playing around with the `patch_location`. Maybe try `patch_location=(100, 100)`

It worked, it detected the patch as different objects. but the airplane is still detected as airplane, is that common?

**Comment by Foxglove144** [comment]
In my testing, yeah that is what happens. However, if you want to suppress detection entirely, you might want to try `RobustDPatch`.
