### ISSUE TITLE
Inclusion of Huggingface Support

### ISSUE THREAD

**Issue by GiulioZizzo** [Trusted-AI/adversarial-robustness-toolbox#2225]
Huggingface is one of the most popular libraries for carrying out machine learning on large pre-trained foundation models. With growing interest and activity in this area, we can aim to include Huggingface as a framework in ART and thus make evaluating, securing, and developing foundation models a seamless experience in ART. 

To do so Huggingface will be included as a new estimator and framework which will support the maximum amount of ART tooling. Hence the aim is to make ART the best available library for foundation model robustness evaluations.

**Comment by reeshipaul** [comment]
I want to work on this issue!

**Comment by GiulioZizzo** [comment]
Hi @reeshipaul ! Thank you for your interest in ART and this planned PR. We have a good amount of the code developed for this already, targeting a core set of popular ART tools. I think the most effective way to contribute would be that after ART 1.16 is released, Huggingface functionality can be expanded from this core toolset to as many of the attacks and defences in ART as possible which could be a great place to jump in. @beat-buesser what do you think of this strategy going ahead for ART 1.16 - 1.17 and beyond?

**Comment by beat-buesser** [comment]
Hi @GiulioZizzo Thank you very much for opening this feature issue!

Hi @reeshipaul Nice to meet you and thank you for your interest in ART! I'm sure we can find a way for you to get started to contribute to ART. Have you been working with HuggingFace before?

**Comment by reeshipaul** [comment]
I have worked on ML Security before and referred to ART before. I was trying my hand on Hugging Face, pretty sure I can pick this up quickly :)

**Comment by reeshipaul** [comment]
Hi @beat-buesser can you please help me get started with this issue
