### ISSUE TITLE
Subclass the `PyTorchYolo` and `PyTorchDetectionTransformer` estimators off the `PyTorchObjectDetector` estimator class

### ISSUE THREAD

**Issue by f4str** [Trusted-AI/adversarial-robustness-toolbox#2267]
**Is your feature request related to a problem? Please describe.**
There is a lot of code overlap between the `PyTorchYolo`, `PyTorchDetectionTransformer`, and `PyTorchObjectDetector` estimators. This causes bugs to have to be fixed in both locations when reported. Missed changes in one estimator will still remain a bug in the other. In additional, the big overlap in code is redundant and makes it tedious from a maintenance perspective.

**Describe the solution you'd like**
The `PyTorchYolo` estimator should be subclassed off `PyTorchObjectDetector`. This will reuse a lot of the code and avoid redundant bugs.

**Describe alternatives you've considered**
N/A

**Additional context**
This is purely an codebase housekeeping change. Functionality should not be changed in any way.

**Comment by beat-buesser** [comment]
Hi @f4str Thank you for opening this feature proposal. I think this is great idea. I have combined the two issues to see both changes in the same PR.
