### ISSUE TITLE
Subclass the `PyTorchDetectionTransformer` estimator off the `PyTorchObjectDetector` estimator

### ISSUE THREAD

**Issue by f4str** [Trusted-AI/adversarial-robustness-toolbox#2268]
**Is your feature request related to a problem? Please describe.**
There is a lot of code overlap between the `PyTorchDetectionTransformer` and `PyTorchObjectDetector` estimators. This causes bugs to have to be fixed in both locations when reported. Missed changes in one estimator will still remain a bug in the other. In additional, the big overlap in code is redundant and makes it tedious from a maintenance perspective.

**Describe the solution you'd like**
The `PyTorchDetectionTransformer` estimator should be subclassed off `PyTorchObjectDetector`. This will reuse a lot of the code and avoid redundant bugs.

**Describe alternatives you've considered**
N/A

**Additional context**
This is purely an codebase housekeeping change. Functionality should not be changed in any way.

**Comment by beat-buesser** [comment]
This issue is very closely related to #2267. I think it is better to make both changes in the same pull request.
