### ISSUE TITLE
Square Attack Bug: Tensor shape mismatch resulting in ValueError when attempting broadcast

### ISSUE THREAD

**Issue by CrimsonScythe** [Trusted-AI/adversarial-robustness-toolbox#2277]
**Describe the bug**
Tensor shape mismatch resulting in ValueError when attempting broadcast. E.g.:
ValueError: could not broadcast input array from shape (3,1,1) into shape (1,0,200,224)
The error occurs on the delta_new assignment:
![image](https://github.com/Trusted-AI/adversarial-robustness-toolbox/assets/18627160/23c4b5e8-05ed-403b-a2a5-7e146627731d)

I fixed it by harcoding the dimensions and removing the batch size. i.e. resizing to (3,224,224)

**To Reproduce**
1. Run Square Attack with inputs of dimensions NCHW. My inputs were of shape (1,3,224,224)

**Expected behavior**
Error free execution

**Screenshots**

**System information (please complete the following information):**
 - OS: MacOS Ventura
 - Python version: 3.8.16
 - PyTorch version: 1.12.0

**Comment by beat-buesser** [comment]
Hi @CrimsonScythe Thank you for using ART! How did you define the classifier?
