### ISSUE TITLE
Formatting of Documentation is Broken

### ISSUE THREAD

**Issue by elanger4** [Trusted-AI/adversarial-robustness-toolbox#2311]
**Describe the bug**
The formatting of documentation on https://adversarial-robustness-toolbox.readthedocs.io/en/latest/index.html has changed, causing some text to obscure other text. It has also, compared to previous documentation, much less readable.

**To Reproduce**
1. Go to https://adversarial-robustness-toolbox.readthedocs.io/en/latest/index.html
2. See obfuscated text

**Expected behavior**
Text does not overlap, formatting is more readable

**Screenshots**
<img width="909" alt="image" src="https://github.com/Trusted-AI/adversarial-robustness-toolbox/assets/7189771/56bb5b49-d906-4d07-ad33-27663ce8b9dd">

**System information (please complete the following information):**
 - Mac OSX
 - Test on Google Chrome & Safari

**Comment by beat-buesser** [comment]
Hi @elanger4 Thank you for reporting this, I'll take a look as soon as possible.

**Comment by elanger4** [comment]
@beat-buesser 
Just checked the new changes, looks like they are partially fixed, but are still displaying the previous behavior in certain sections.

For example, on https://adversarial-robustness-toolbox.readthedocs.io/en/latest/modules/attacks/evasion.html
I'm seeing:
![image](https://github.com/Trusted-AI/adversarial-robustness-toolbox/assets/7189771/fe9d2afe-ba82-423e-8f92-b97e3547c739)
I've tested this on Chrome for both Windows & Mac.

Thank you again for your work on this project!
