### ISSUE TITLE
TensorFlow Addons is end of life in May 2024

### ISSUE THREAD

**Issue by jamesmyatt** [Trusted-AI/adversarial-robustness-toolbox#2316]
> TensorFlow Addons (TFA) has ended development and introduction of new features.
> TFA has entered a minimal maintenance and release mode until a planned end of life in May 2024.
> Please modify downstream libraries to take dependencies from other repositories in our TensorFlow community (e.g. Keras, Keras-CV, and Keras-NLP). 
> 
> For more information see: https://github.com/tensorflow/addons/issues/2807

What are the plans for removing/replacing TFA?

**Comment by beat-buesser** [comment]
Hi @jamesmyatt Thank you for the update, we have noticed it too. I'm currently working on updating ART and it's testing for Tensorflow 2.14. I have not yet found replacement function for all functions we use from TFA. Would you be interested to take a closer look at ART's dependencies and how to best replace them?

**Comment by jamesmyatt** [comment]
I think that:

* `tfa.image.transform` -> Keras has a function that appears to match (https://github.com/keras-team/keras/blob/v2.14.0/keras/layers/preprocessing/image_preprocessing.py#L720)
* `tfa.image.rotate` -> can be implemented via the transform function above (c.f. https://github.com/keras-team/keras/blob/68f9af408a1734704746f7e6fa9cfede0d6879d8/keras/layers/preprocessing/image_preprocessing.py#L987)
* `tfa.image.random_cutout` -> Keras CV (https://keras.io/api/keras_cv/layers/preprocessing/random_cutout/)
* `tfa.image.median_filter2d` -> probably just copy-and-paste this or replace it with a different filter from [tfio.experimental.filter](https://www.tensorflow.org/io/api_docs/python/tfio/experimental/filter)

**Comment by jamesmyatt** [comment]
Can you reopen this, please? It's going to make installing ART hard or impossible in the future.
