### ISSUE TITLE
adversarial audio example notebook not giving the same results

### ISSUE THREAD

**Issue by 3DVERSEjn** [Trusted-AI/adversarial-robustness-toolbox#2431]
<img width="961" alt="Screenshot 2024-04-11 at 12 34 49 PM" src="https://github.com/Trusted-AI/adversarial-robustness-toolbox/assets/72844102/82398e16-ee92-4b63-b963-aeb4e5ef421a">
This is what I am getting from the tutorial notebook. It does not match to the original outputs from the repo.

**Comment by beat-buesser** [comment]
Hi @3DVERSEjn ,Thank you very much for reporting your observations. Could you please provide more details about your experiments?

**Comment by 3DVERSEjn** [comment]
Yes I am simply running the provided notebooks for speech models. In particular this notebook result above comes from the adversarial audio example. When running the attack we get an audio file that contains only white noise, the original audio can no longer be heard.
