### ISSUE TITLE
Descriptive names for targeted attacks

### ISSUE THREAD

**Issue by ebubae** [Trusted-AI/adversarial-robustness-toolbox#299]
**Is your feature request related to a problem? Please describe.**
When generating generating targeted attacks the method arguments  `generate(x, y=None)` can be confusing. In this case `y` usually refers to the target label for the attack, but users may accidentally put the correct label there, rendering the attack ineffective.

**Describe the solution you'd like**
Maybe we should change that argument to `target` to show clearly that label is the target label.

**Additional context**
This would be a breaking change.

**Comment by beat-buesser** [comment]
Hi @ebubae Thank you very much for raising this issue! I think if we would make this change it should be made consistent across all attacks.
