### ISSUE TITLE
Implement Carlini & Wagner L_0 Attack

### ISSUE THREAD

**Issue by mamerzouk** [Trusted-AI/adversarial-robustness-toolbox#443]
_Carlini and Wagner_ introduced an interesting algorithm for the generation of targeted adversarial examples, their method defeats _Defensive distillation_ and other defense methods.
The authors define a new objective function that can be minimized with the distance (the paper introduces 7 objective function candidates). They also introduce a new variant _ω_ to avoid the box constraint. General optimizers like _Adam_ and _SGD_ were used to find adversarial examples.
The authors have adapted their method for the `L_0`, `L_2` and `L_inf` distance metrics. The `L_0` attack is complex since this distance metric is non-differentiable and therefore is ill-suited for standard gradient descent. Instead, the authors introduced an iterative method that calls the `L_2` attack to generate adversarial examples using a subset of attributes and then computes the derivatives to identify the attributes that contributed the least and fix them. 
ART provides an implementation Carlini & Wagner `L_2` and `L_inf ` attacks only. It would be interesting to provide an implementation for the `L_0` attacks.

Paper link : https://arxiv.org/abs/1608.04644
GitHub link : https://github.com/carlini/nn_robust_attacks/

**Comment by beat-buesser** [comment]
Hi @mamerzouk Thank you very much for proposing this new feature in ART and committing to implement it on Slack! Please let us know anytime if you have any questions or would like to discuss the implementation, etc.
