### ISSUE TITLE
LightGBM Tutorial

### ISSUE THREAD

**Issue by firmai** [Trusted-AI/adversarial-robustness-toolbox#474]
I want to create an exhaustive tutorial of all methods that work with LightGBM. Can you let me know which models should theoretically work with LightGBM?

**Comment by firmai** [comment]
I have done RobustnessVerificationTreeModelsCliqueMethod and ZooAttack. I am using a tabular data. A credit dataset.

**Comment by beat-buesser** [comment]
Hi @firmai Thank you very much for your interest in ART!

I think for this tutorial you are mainly looking for black-box attacks: in addition to `ZooAttack` there is currently `HopSkipJump` which also should work on tabular data.

Are you planning to share your tutorial publicly?
