### ISSUE TITLE
Wrong backward pass in chaining preprocessing defenses

### ISSUE THREAD

**Issue by mzweilin** [Trusted-AI/adversarial-robustness-toolbox#485]
**Describe the bug**
ART 1.2 and 1.3 support chaining preprocessing defenses, but the gradient computation is wrong.

In the forward pass, it is clear that the code is chaining a list of defenses:
https://github.com/IBM/adversarial-robustness-toolbox/blob/master/art/estimators/estimator.py#L250

In the backward pass, the estimate_gradient() of a defense should take the exact input of the defense. However, the original input is always used for defenses at different places of the chain.
https://github.com/IBM/adversarial-robustness-toolbox/blob/master/art/estimators/estimator.py#L377

**Expected behavior**
In the backward pass, the estimate_gradient() of a defense should take the exact input of the defense instead of the original input x.

**System information (please complete the following information):**
 - ART 1.2 and 1.3

**Comment by beat-buesser** [comment]
Hi @mzweilin Thank you very much for raising this issue!

I think you are right. My first feeling is that the original input has been used in the gradient estimation because the actual input states in-between the preprocessing defences created during the forward pass, that should be used in the gradient estimation, are not stored so far. We'll discuss and try to improve it as soon as possible.

**Comment by mzweilin** [comment]
Thanks for the confirmation, @beat-buesser 

We have a workaround in Pytorch for your reference. We require two methods in a preprocessing defense: 

1. `forward()` which defines pytorch operations for the defense;
2. `estimate_forward()` which is a differentiable counterpart of `forward()` in case it is not differentiable.

The `__call__()` method just converts input into a pytorch tensor, revokes `forward()` and detaches the returned tensor into numpy, so that it's compatible with existing infrastructure.

When we are chaining multiple preprocessing defenses, we can just chain `forward()` instead of `__call__()`. Similarly, the backward pass can chain multiple `estimate_forward()` together. In this way, we don't have to store the intermediate `x` somewhere. Also, we avoid switching between numpy and pytorch back and forth.

**Comment by beat-buesser** [comment]
@mzweilin Your approach sounds very useful and interesting! Would you be able to share your code and maybe contribute it to ART?

I think your work could introduce framework-specific preprocessing defences to ART and serve as pattern for the other deep learning frameworks. This could be very useful for many ART users.

**Comment by mzweilin** [comment]
@beat-buesser  I will be happy to file a PR with the framework change. But I need to consult with the legal team first if it's ok for me to contribute code to ART directly. Stay tuned.
