### ISSUE TITLE
art.estimators not found

### ISSUE THREAD

**Issue by mcdonaldnj304** [Trusted-AI/adversarial-robustness-toolbox#492]
I recently did a pip install of ART and have been trying to run example code from ART, but I get: ModuleNotFoundError: No module named 'art.estimators'

I any idea how to fix this?

**Comment by beat-buesser** [comment]
Hi @mcdonaldnj304 Thank you very much for getting started with ART!

Could you please provide more information about how you obtain this error? E.g. output of `pip list` and the command that you are running?

**Comment by mcdonaldnj304** [comment]
Hello, thank you for replying. 
pip list shows that ART 1.2.0 is installed
I'm using ubuntu 18.04.4 if that was what you were asking.

**Comment by beat-buesser** [comment]
The module `art.estimators` is available since ART 1.3.0. It looks like you are running a code example from ART 1.3 with ART 1.2. Upgrading your ART installation to 1.3.1 should fix this.

**Comment by pickle0412** [comment]
Hello, I am facing the same issue when running the example get_started_pytorch.py from the CLI. I am using ART 1.3.1 version.
Looking forward to your support. Thanks!

**Comment by beat-buesser** [comment]
I have run `get_started_pytorch.py` with a fresh installation of ART 1.3.1 and I'm not able to reproduce your observation so far.

Can you describe in more detail how you have installed ART, how you have verified that it is ART 1.3 and how you are running `get_started_pytorch.py`?

**Comment by pickle0412** [comment]
> I have run `get_started_pytorch.py` with a fresh installation of ART 1.3.1 and I'm not able to reproduce your observation so far.
> 
> Can you describe in more detail how you have installed ART, how you have verified that it is ART 1.3 and how you are running `get_started_pytorch.py`?

There seems to be some issue with the system executables on the server I am working on. I shall resolve those at my end and get back if the problem recurs. Thanks for your timely response!

**Comment by TanmayKhot** [comment]
> Hello, I am facing the same issue when running the example get_started_pytorch.py from the CLI. I am using ART 1.3.1 version.
> Looking forward to your support. Thanks!

Could you get it to work? I am facing the same issue
