### ISSUE TITLE
RuntimeError: Input type (torch.cuda.DoubleTensor) and weight type (torch.cuda.FloatTensor) should be the same

### ISSUE THREAD

**Issue by superctj** [Trusted-AI/adversarial-robustness-toolbox#497]
**Describe the bug**
I encountered the error "RuntimeError: Input type (torch.cuda.DoubleTensor) and weight type (torch.cuda.FloatTensor) should be the same" when initiating an instance of [AutoAttack](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/09262467e6f0a5832d2580b0bf995ecee333171d/art/attacks/evasion/auto_attack.py#L40). Following the traceback, I found the error was caused by [this line](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/09262467e6f0a5832d2580b0bf995ecee333171d/art/attacks/evasion/auto_projected_gradient_descent.py#L258). It seems like 'torch.from_numpy(...)' gives a DoubleTensor while my model was loaded with weights of type FloatTensor.

**To Reproduce**
1. Create a PyTorch model and load it with weights
2. Wrap the model with the ART PyTorch Classifier
3. Initiate an attack instance of AutoAttack and pass in the wrapped model

**Expected behavior**
"RuntimeError: Input type (torch.cuda.DoubleTensor) and weight type (torch.cuda.FloatTensor) should be the same"

**Screenshots**
<img width="733" alt="Screen Shot 2020-07-16 at 10 47 38 PM" src="https://user-images.githubusercontent.com/33765174/87743186-5b6bfb00-c7b6-11ea-9435-3b646a87781d.png">

**System information (please complete the following information):**
 - OS: Linux
 - Python version: 3.7
 - ART version or commit number: 1.3.1
 - PyTorch version: 1.4.0

**Comment by beat-buesser** [comment]
Hi @superctj Thank you very much for using ART and for reporting this issue! We'll fix it as soon as possible.

**Comment by beat-buesser** [comment]
Hi @superctj I have a solution for this issue implemented in #499 on branch `development_issue_497`. Could you please do a review in #499 and check if it also solves your issue?

**Comment by superctj** [comment]
It should fix the type issue. I can be more sure if I can run my code with this solution. Please let me know when I could update my local library to the new version.

**Comment by beat-buesser** [comment]
Hi @superctj That's great! I think it would be safer to test it before packaging, if possible could you please try to update your local library by cloning the ART repository and installing branch `development_issue_497` using `pip`, e.g. with:
```
git@github.com:Trusted-AI/adversarial-robustness-toolbox.git
cd adversarial-robustness-toolbox
git checkout development_issue_497
pip install .
```

**Comment by superctj** [comment]
@beat-buesser I appreciate this cautious suggestion. Do I need to uninstall the current version of ART first to avoid a conflict?

**Comment by beat-buesser** [comment]
No, the commands above should overwrite existing installations in your current pyhton environment.

To go back to the official PyPI version after testing you can do `pip install --upgrade --force-reinstall adversarial-robustness-toolbox==1.3.1`

**Comment by superctj** [comment]
Thank you for your detailed guidance. I have run my code with the update in the new branch and it does fix the type issue. However, I run into the same problem that I reported in #498.

**Comment by V-Sher** [comment]
I had a similar issue when I was trying to train a GAN using my own image dataset - i.e. I was reading my image dataset as NumPy arrays. The problem is that NumPy input uses `double` as the data type, whereas your model weights are `float`. 

What worked for me was explicitly converting the NumPy array as `float` before feeding it to the model (use `np.float32(img)`).

**Comment by beat-buesser** [comment]
Hi @V-Sher Thank you very much for sharing your solution. In this issue we had an operation inside of the attack that converted `float` or any input to type `double` before it reached the model.

**Comment by vizcox** [comment]
Es la primera vez que me resuelven un problema de programación en github, ante un problema simple una solución simple (usa np.float32(img). 
Aquí en github para un problema simple, donde se que yo me he equivocado, intentamos resolverlo modificando el código de python en c++.
A ver si es posible que si yo busco un fallo simple que no me aparezca github en las primeras busquedas.
