### ISSUE TITLE
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

### ISSUE THREAD

**Issue by superctj** [Trusted-AI/adversarial-robustness-toolbox#498]
**Describe the bug**
I encountered the error "RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn" when generating adversarial examples using [AutoProjectedGradientDescent](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/09262467e6f0a5832d2580b0bf995ecee333171d/art/attacks/evasion/auto_projected_gradient_descent.py#L38). It looks like input tensors do not have 'requires_grad' set to True when the loss is backpropagated.

**To Reproduce**
1. Create a PyTorch model and load it with weights
2. Wrap the model with the ART PyTorch Classifier
3. Initiate an instance of AutoProjectedGradientDescent and pass in the wrapped model
4. Loop through the data loader and generate adversarial examples batch by batch
5. See error

**Expected behavior**
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

**Screenshots**
<img width="732" alt="Screen Shot 2020-07-17 at 2 53 32 PM" src="https://user-images.githubusercontent.com/33765174/87821125-4c7c5b80-c83d-11ea-896e-d2c385282cff.png">

**System information (please complete the following information):**
 - OS: Linux
 - Python version: 3.7
 - ART version or commit number: 1.3.1
 - PyTorch version: 1.4.0

**Comment by beat-buesser** [comment]
Hi @superctj I have not been able to reproduce the issue based on the traceback posted above. Could you please post a short code snippet that produces the issue?

**Comment by superctj** [comment]
Hi @beat-buesser Thank you for your quick response. Here is a screenshot of my code <img width="640" alt="Screen Shot 2020-07-17 at 10 17 39 PM" src="https://user-images.githubusercontent.com/33765174/87842571-58870e00-c87b-11ea-8fb2-8ca30c9f62d9.png">

**Comment by beat-buesser** [comment]
Hi @superctj I have run this script similar to yours but without a data loader and it works:
```
import numpy as np

from art.utils import load_mnist
from art.attacks.evasion import AutoProjectedGradientDescent

from tests.utils import get_image_classifier_pt

(x_train, y_train), (x_test, y_test), min_pixel_value, max_pixel_value = load_mnist()

x_train = np.swapaxes(x_train, 1, 3).astype(np.float32)
x_test = np.swapaxes(x_test, 1, 3).astype(np.float32)

classifier = get_image_classifier_pt(load_init=True, from_logits=True)

attack = AutoProjectedGradientDescent(estimator=classifier,
                                      norm=np.inf,
                                      eps=0.3,
                                      eps_step=0.1,
                                      batch_size=50,
                                      loss_type='cross_entropy')

x_test_adv = attack.generate(x=x_test[0:110], y=y_test[0:110])

print('Max difference:', np.max(np.abs(x_test_adv - x_test[0:110])))
```

Could you please try to run your script with (adding `.cpu()`):
```
x_batch = x_batch.detach().cpu().numpy()
y_batch = y_batch.detach().cpu().numpy()
```

**Comment by superctj** [comment]
Hi @beat-buesser Thank you for your suggestion. Unfortunately, it doesn't fix the error.

**Comment by superctj** [comment]
Could you please try to replicate the error by using a PyTorch data loader?

**Comment by beat-buesser** [comment]
Hi @superctj The script below seems to work with a `torch.utils.data.DataLoader`:

```
import numpy as np
import torch
import torchvision

from art.utils import load_mnist
from art.attacks.evasion import AutoProjectedGradientDescent

from tests.utils import get_image_classifier_pt

(x_train, y_train), (x_test, y_test), min_pixel_value, max_pixel_value = load_mnist()

x_train = np.swapaxes(x_train, 1, 3).astype(np.float32)
x_test = np.swapaxes(x_test, 1, 3).astype(np.float32)

classifier = get_image_classifier_pt(load_init=True, from_logits=True)

batch_size = 500

attack = AutoProjectedGradientDescent(estimator=classifier,
                                      norm=np.inf,
                                      eps=0.3,
                                      eps_step=0.1,
                                      batch_size=batch_size,
                                      loss_type='cross_entropy')

train_loader = torch.utils.data.DataLoader(torchvision.datasets.MNIST('./files/', train=True, download=True,
                                                                      transform=torchvision.transforms.Compose(
                                                                          [torchvision.transforms.ToTensor(), ])),
                                           batch_size=batch_size,
                                           shuffle=True)

for batch_idx, (x_batch, y_batch) in enumerate(train_loader):

    x_batch = x_batch.detach().cpu().numpy()
    y_batch = y_batch.detach().cpu().numpy()

    x_batch_adv = attack.generate(x=x_batch, y=y_batch)

    print('batch_idx:', batch_idx)
    print('Max difference:', np.max(np.abs(x_batch_adv - x_batch)))
```

How do you define your data loader?

**Comment by superctj** [comment]
I have tried to debug this myself but haven't got any luck. I thought the issue was related to the gradient attribute, the tensor type or the axis order but neither helps. Basically, I have a custom dataset instance and wrap it with the PyTorch data loader. Do you have any ideas? I attach the data loader code for your reference.

<img width="921" alt="Screen Shot 2020-07-20 at 5 39 49 PM" src="https://user-images.githubusercontent.com/33765174/87989602-51951100-cab0-11ea-81bc-25b364b9068c.png">
<img width="944" alt="Screen Shot 2020-07-20 at 5 40 07 PM" src="https://user-images.githubusercontent.com/33765174/87989611-58238880-cab0-11ea-9bef-2d990d5951d3.png">
<img width="913" alt="Screen Shot 2020-07-20 at 5 40 19 PM" src="https://user-images.githubusercontent.com/33765174/87989616-5b1e7900-cab0-11ea-93d3-3c1cea28422f.png">

**Comment by beat-buesser** [comment]
Does the error occur for the first or last batch?

**Comment by beat-buesser** [comment]
What is the type of the elements in `self.y`?

**Comment by superctj** [comment]
1. The error occurs for the first batch.
2. The type of the elements in `self.y` is integer.

**Comment by beat-buesser** [comment]
How do you define your model? Can you also show the output of a forward pass with your model e.g. the output of `model(x)`

**Comment by superctj** [comment]
I load a pre-trained model and wrap it into an ART PyTorch classifier. The output of `model(x_batch)` is a bunch of logits 
<img width="427" alt="Screen Shot 2020-07-20 at 8 46 44 PM" src="https://user-images.githubusercontent.com/33765174/87999866-21f30280-caca-11ea-81eb-690a7be8e13d.png">


<img width="666" alt="Screen Shot 2020-07-20 at 8 43 55 PM" src="https://user-images.githubusercontent.com/33765174/87999728-c0cb2f00-cac9-11ea-8e84-9b3c7d880463.png">
<img width="446" alt="Screen Shot 2020-07-20 at 8 45 33 PM" src="https://user-images.githubusercontent.com/33765174/87999791-f6701800-cac9-11ea-8bad-8f683d6b06e0.png">

**Comment by superctj** [comment]
Could you replicate the error if you set `model.eval()` before you wrap the model into the ART PyTorch classifier?

**Comment by beat-buesser** [comment]
`model.eval()` does not change anything for me. I noticed that my script only runs inside of the `examples` directory of ART. Does `model.eval()` change anything for you?

**Comment by superctj** [comment]
Nah. I just thought it could be the difference between your and my code. Are you saying that you can reproduce the error outside the `examples` directory of ART.

**Comment by beat-buesser** [comment]
No, unfortunately not, it's just that `get_image_classifier_pt` uses relative paths to load a small trained classifier. I have repeated the test outside if examples with a new model and it still runs. Are you running on GPU? If yes, can you try to run on CPU only?

**Comment by beat-buesser** [comment]
Another debugging approach could be to test the your script by running the line `x_adv_batch = attack.generate(x=x_batch, y=y_batch)` with two arrays for `x_batch` and `y_batch` created with numpy (e.g. random numbers) instead of getting them from the data loader. That could show if the data loader or the attack and classifier combination are causing the problem.

**Comment by superctj** [comment]
Unfortunately, the error persists when I run on CPU only. Could it be a problem with PyTorch? I am using PyTorch 1.4.0.

**Comment by beat-buesser** [comment]
It should not, I have also been using PyTorch 1.4.0.

**Comment by superctj** [comment]
Cool, the error doesn't show up if I create `x_batch` and `y_batch` with numpy directly. It should be a problem with the data loader then. But it is interesting that `x_batch = x_batch.detach().cpu().numpy()` triggers the error while `x_batch = np.ones(x_batch.shape)` does not.

**Comment by beat-buesser** [comment]
Can you print the type and content of `x_batch` and `y_batch` after the lines `x_batch = x_batch.detach().cpu().numpy()` and `y_batch = y_batch.detach().cpu().numpy()`?

**Comment by superctj** [comment]
`x_batch` is a `<class 'numpy.ndarray'>` of shape (50, 3, 256, 256).
<img width="469" alt="Screen Shot 2020-07-21 at 10 47 24 AM" src="https://user-images.githubusercontent.com/33765174/88069520-91570980-cb3f-11ea-824c-5593204607c1.png">

`y_batch` is also a `<class 'numpy.ndarray'>` of shape (50,). It looks like [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

**Comment by beat-buesser** [comment]
I think I found the bug, in your first script above a line has a typo: `y_baych = y_batch.detach().cpu().numpy()` instead of `y_batch = y_batch.detach().cpu().numpy()` (y instead of t in y_batch). That way the original tensor `y_batch` gets to the attack instead of the numpy array in `y_baych`.

A second question: Is it correct that all the labels are 0 for this batch?

**Comment by superctj** [comment]
That was a typo. I found that as well yesterday but it didn't fix the error lol.

Yeah, I didn't shuffle the test set so it starts with images from label 0.

**Comment by superctj** [comment]
Hi @beat-buesser. I create a [minimal example](https://github.com/superctj/error_demo) to reproduce the error. Could you please take a look and see if you can reproduce the error?

**Comment by superctj** [comment]
With the help of my labmate, we found the problem was with `torch.no_grad`, which prevents the attack from being able to backpropagate to the inputs. Do you have any suggestions other than removing `with torch.no_grad` or is there a better solution?

**Comment by beat-buesser** [comment]
Hi @superctj Thank you very much for the minimal example, that's great!

Do you mean the `with torch.no_grad` in https://github.com/superctj/error_demo/blob/620368e21b7ae56fbcdab28fcba1281ddfd42073/eval.py#L30 ?

**Comment by superctj** [comment]
Yeah, after removing that line, I can run the PGD attack smoothly.

**Comment by beat-buesser** [comment]
Ok, that makes sense, great catch, I hadn't noticed it.

White-box attacks like `ProjectedGradientDescent` will not work inside of a `with torch.no_grad:` block because they are calculating loss or class gradients required to run their attack algorithm.

It is very likely possible that black-box attacks, like `HopSkipJump`, which don't require any gradient calculation by the framework will work inside of a `with torch.no_grad:` block. However since ART 1.3 `PytorchClassifier.predict` actually uses `with torch.no_grad:` inside of `predict` to take advantage of the faster model evaluation if gradients are disabled.

**Comment by superctj** [comment]
That's good to know! Thank you very much for your time and patience. I appreciate it.
