### ISSUE TITLE
cannot import name 'CLIP_VALUES_TYPE'

### ISSUE THREAD

**Issue by AbhishekSingl** [Trusted-AI/adversarial-robustness-toolbox#501]
Recently, I downloaded ART module. I tried to execute "poisoning _attack_SVM.py". I've got an error "cannot import CLIPS_VALUES_TYPE". 

Error Screenshot:
![image](https://user-images.githubusercontent.com/12597496/88019131-1538d380-caf7-11ea-9cbd-6a800e974e40.png)
![image](https://user-images.githubusercontent.com/12597496/88019279-6b0d7b80-caf7-11ea-89a1-ab7c3b56d180.png)

**System information:**
 - Mac OS
 - Python version 3
 - ART version
![image](https://user-images.githubusercontent.com/12597496/88019350-9bedb080-caf7-11ea-8317-8031d0f8fddc.png)

**Comment by beat-buesser** [comment]
Hi @AbhishekSingl Thank you very much for using ART and reporting this issue! We will investigate it as soon as possible.

**Comment by beat-buesser** [comment]
Could you please show a code example, and how you run it, that leads to this error message?
