### ISSUE TITLE
Adding examples for computing robustness metrics

### ISSUE THREAD

**Issue by rezacsedu** [Trusted-AI/adversarial-robustness-toolbox#504]
Re: https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/art/metrics/metrics.py, could you please add examples of computing different adversarial robustness metrics, e.g.,  empirical_robustness, CLEVER, loss_sensitivity, wasserstein_distance?

**Comment by beat-buesser** [comment]
Hi @rezacsedu Thank you very much for your interest in ART! I think that's a great idea!

We have a notebook for `RobustnessVerificationTreeModelsCliqueMethod` in https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/notebooks/robustness_verification_clique_method_tree_ensembles_gradient_boosted_decision_trees_classifiers.ipynb

Would you be interested to help developing new examples for other metrics?

**Comment by rezacsedu** [comment]
@beat-buesser, sure I could try. If I come accross something useful, I'll get back to you.

**Comment by beat-buesser** [comment]
@rezacsedu That's great! Also let us know anytime if you have any questions about these metrics.
