### ISSUE TITLE
Implement low frequency adversarial perturbation strategy

### ISSUE THREAD

**Issue by ririnicolae** [Trusted-AI/adversarial-robustness-toolbox#51]
This is a black-box attack search strategy allowing to reduce the number of queries to a model by 2-4x. It is based on discrete cosine transform (DCT). This selection strategy can be combined with existing black-box attacks, e.g., the paper proves effectiveness with NES and boundary attack. This should be implemented as a wrapper if possible, to allow the usage with existing black-box attacks in ART.

Paper link: https://arxiv.org/abs/1809.08758

**Comment by rish-16** [comment]
@beat-buesser Hello there, can you kindly assign this issue to me? I'll get started on it.

**Comment by beat-buesser** [comment]
@rish-16 Thank you! And let us know here if you have questions or need support.

**Comment by rish-16** [comment]
Will do. Thank you

**Comment by beat-buesser** [comment]
Hi @rish-16 Have you been able to make progress with this issue?

**Comment by beat-buesser** [comment]
Hi @rish-16 Are you still working on this issue?

**Comment by kztakemoto** [comment]
@ririnicolae Our implementation in ART I forked may be useful.
https://github.com/kztakemoto/SimBA-Keras

**Comment by ririnicolae** [comment]
@kztakemoto Would you like to pull request to ART your implementation of this attack?

**Comment by kztakemoto** [comment]
@ririnicolae thanks. I pull requested. https://github.com/IBM/adversarial-robustness-toolbox/pull/469
