### ISSUE TITLE
Not able to execute pixel defend

### ISSUE THREAD

**Issue by dsvrsec** [Trusted-AI/adversarial-robustness-toolbox#516]
I am not able to pixel defend Defense on CIFAR 10 or MNIST images.I am trying to use pixel cnn model and i am facing this error while using it in classifier before giving to pixel defend class.

![image](https://user-images.githubusercontent.com/39803284/89102450-f277ba80-d426-11ea-8359-095165552d0b.png)

Is there any example or notebook on how to use pixel defend for CIFAR 10 dataset.

**Comment by beat-buesser** [comment]
Hi @kumarvrsec Thank you very much for using ART!

Unfortunately I don't think we have an example for Pixel Defend.

Can you post here a short example script that leads to the error that you have observed?
