### ISSUE TITLE
The application_object_detection.py in examples doesn't work!

### ISSUE THREAD

**Issue by weiyikang** [Trusted-AI/adversarial-robustness-toolbox#548]
**Describe the bug**
The application_object_detection.py in examples doesn't work!

**To Reproduce**
1. Go to 'examples/application_object_detection.py'
2. Click on 'application_object_detection.py'
3. See error：/PyTorchFasterRCNN.py", line 193, in loss_gradient
    gradients = img.grad.cpu().numpy().copy()
AttributeError: 'NoneType' object has no attribute 'cpu'

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/15953968/90107647-b542ef00-dd7b-11ea-8b4d-f9b0edf3d0ae.png)

**System information (please complete the following information):**
 - OS：Ubuntu18
 - Python version: python3.7
 - ART version or commit number: git clone from github, latest 1.3.2
 - TensorFlow / Keras / PyTorch / MXNet version: Pytorch1.1.0, cuda9.0

**Comment by weiyikang** [comment]
There are other problems, such as doesn't transfer GPU to CPU:
![image](https://user-images.githubusercontent.com/15953968/90108036-4d40d880-dd7c-11ea-8fb0-80a72cc7ab1b.png)

**Comment by beat-buesser** [comment]
Hi @weiyikang Thank you for using ART for object detection!

I haven't been able so far to reproduce the first error and I would need more information. It looks like the gradients are None in your case. Are you running anything inside of a `with torch.no_grad():` block that stops the gradients in `torch`?

I agree with your second comment, this example script has only been test for CPU only so far. We should update it to work with CPU and GPU/CPU systems. Would you have an updated version that works in both cases ready for a pull request?

**Comment by weiyikang** [comment]
Thanks for your answer! The second problem has been answered. There are some details about the first problem:
1. I used two 500*500 png images as the test images, which is from coco dataset;
![6](https://user-images.githubusercontent.com/15953968/90198262-c6cfd980-de03-11ea-8b2d-dc12be2e3916.png)
![14](https://user-images.githubusercontent.com/15953968/90198270-ccc5ba80-de03-11ea-9039-fdba1b232c4d.png)
2. The code in application_object_detection.py doesn't been changed;
3. I have skipped to the errors in lines:193 at art/estimators/object_detection/PyTorchFasterRCNN.py, there is not the block "with torch.no_grad():". I try to modify the PyTorchFasterRCNN.py, it does work because I have installed the adversarial-robust-toolboxes, the modified about PyTorchFasterRCNN.py can't influence the using of adversarial-robust-toolboxes!

**Comment by weiyikang** [comment]
> Hi @weiyikang Thank you for using ART for object detection!
> 
> I haven't been able so far to reproduce the first error and I would need more information. It looks like the gradients are None in your case. Are you running anything inside of a `with torch.no_grad():` block that stops the gradients in `torch`?
> 
> I agree with your second comment, this example script has only been test for CPU only so far. We should update it to work with CPU and GPU/CPU systems. Would you have an updated version that works in both cases ready for a pull request?

Thanks for your answer! The second problem has been answered. There are some details about the first problem:
1. I used two 500*500 png images as the test images, which is from coco dataset;
![6](https://user-images.githubusercontent.com/15953968/90198262-c6cfd980-de03-11ea-8b2d-dc12be2e3916.png)
![14](https://user-images.githubusercontent.com/15953968/90198270-ccc5ba80-de03-11ea-9039-fdba1b232c4d.png)
2. The code in application_object_detection.py doesn't been changed;
3. I have skipped to the errors in lines:193 at art/estimators/object_detection/PyTorchFasterRCNN.py, there is not the block "with torch.no_grad():". I try to modify the PyTorchFasterRCNN.py, it does work because I have installed the adversarial-robust-toolboxes, the modified about PyTorchFasterRCNN.py can't influence the using of adversarial-robust-toolboxes!

**Comment by beat-buesser** [comment]
I think the problem is the version of your `torch` and torchvision`. I was able to reproduce the error with `torch==1.1.0` and `torchvision==0.3.0`. Could you please try with `torch==1.5.1` and `torchvision==0.6.1`?

**Comment by weiyikang** [comment]
> I think the problem is the version of your `torch` and `torchvision` versions. I was able to reproduce the error with `torch==1.1.0` and `torchvision==0.3.0`. Could you please try with `torch==1.5.1` and `torchvision==0.6.1`?

Thank you very much, the major problem has been solved! But there are some minor errors as follows:
![org0](https://user-images.githubusercontent.com/15953968/90203818-5087a300-de14-11ea-8b9f-7ccf4d118c97.png)
The errors can be described as the boxes and texts drawing by function:plot_image_with_boxes() in application_object_detection.py are rough and can't distinguish! I have changed the text_size, text_th and rect_th smaller, while the situation don't go well.

**Comment by beat-buesser** [comment]
I don't think this is an error. This script has not been designed to automatically adapt to all image sizes. Would you have a pull request available to make the plotting depend on image size?

**Comment by weiyikang** [comment]
> I don't think this is an error. This script has not been designed to automatically adapt to all image sizes. Would you have a pull request available to make the plotting depend on image size?

I will try other configs, there isn't any errors, thanks for your answering!

**Comment by beat-buesser** [comment]
Great! It's caused but the size settings on variables `text_size`, `text_th`, and `rect_th` in funciton `plot_image_with_boxes` which seem to be absolute instead of relative to image size.
