### ISSUE TITLE
Mismatched dtypes when using FGM-with-random-init and estimator clip_values

### ISSUE THREAD

**Issue by dxoigmn** [Trusted-AI/adversarial-robustness-toolbox#582]
**Describe the bug**
When `num_random_init > 0` is specified for `art.attacks.evasion.FastGradientMethod`, it is possible for there to be a type mismatch when the estimator's `clip_values` are specified. For example, in https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/art/attacks/evasion/fast_gradient.py#L330, it is possible for `clip_min` and `clip_max` to be of dtype `float64` which then causes `x_adv` to be different than `ART_NUMPY_DTYPE` (which defaults to `float32`) after clipping. See the below python example that demonstrates this numpy type promoting:
```
$ python
Python 3.7.7 (default, Mar 10 2020, 15:16:38)
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> x_adv = np.array([0], dtype=np.float32)
>>> x_adv.dtype
dtype('float32')
>>> x_adv = np.clip(x_adv, 0, 1)
>>> x_adv.dtype
dtype('float32')
>>> x_adv = np.clip(x_adv, np.array([0], dtype=np.float64), np.array([0], dtype=np.float64))
>>> x_adv.dtype
dtype('float64')
```

**To Reproduce**
I am unable to share my code that exhibits this bug, but I think the above Python example demonstrates the bug clearly. A minimal example would create a dummy estimator with `clip_values` of type `float64` and then setup the `FastGradientMethod` with `num_random_init = 1`.

**Expected behavior**
`x_adv` should be cast to `ART_NUMPY_DTYPE` after clipping.

**Screenshots**
N/A

**System information (please complete the following information):**
 - OS: Ubuntu 18.04.1 LTS
 - Python version: 3.7.7
 - ART version or commit number: 1.2 (but appears to be the case in 1.3)
 - TensorFlow / Keras / PyTorch / MXNet version: N/A

**Comment by beat-buesser** [comment]
Hi @dxoigmn Thank you very much for raising this issue! We had a related issue #366 on ART 1.2 earlier this year and PR #392 aimed to fix it for ART 1.3. I'll try to reproduce this issue with ART 1.3.

**Comment by dxoigmn** [comment]
Ah, yes. I should have searched the issue before submitting, my fault!

**Comment by beat-buesser** [comment]
Don't worry!

I tested the example `get_started_tensorflow_v2.py` with clip values of type `np.float64`  and `FastGradientMethod` returned the adversarial examples in `np.float32` for `num_random_init=1` using ART 1.3.3.

I was able to reproduce the issue with ART 1.2.0.

Can you confirm that the issue occurs also in ART 1.3.3?
Do you have an application requiring ART 1.2.0 that would need a patch to resolve this issue or can you upgrade to ART 1.3?

**Comment by dxoigmn** [comment]
Some more backstory. We are using [Armory](https://github.com/twosixlabs/armory/) which heavily depends upon ART. The version we are presently using, Armory 0.9.1, depends upon ART 1.2, and the next versions, Armory 0.10 and 0.11, depend upon ART 1.3.1. I have filed an issue with them as well: https://github.com/twosixlabs/armory/issues/730.

**Comment by beat-buesser** [comment]
I think this seems fixed, but feel free to reopen if not.
