### ISSUE TITLE
Less strict dependencies

### ISSUE THREAD

**Issue by illeatmyhat** [Trusted-AI/adversarial-robustness-toolbox#587]
All Trusted-AI libraries should have roughly the same version requirements.
As it is, they are incompatible with each other and you can't run them in the same environment if you have a strict dependency checker.

For that matter, a library should not lock to a specific version number, but should offer a range that still works.
https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/925b6957870f8b689e24cac482f8b1c2afcc69d3/setup.py#L11-L13
The latest version of scikit-learn (0.23.2) is not even supported as a WML deployment.

i.e.
```python

 "scipy>=1.4.1", 
 "scikit-learn>=0.20.3",
```

**Comment by beat-buesser** [comment]
Hi @illeatmyhat,

Thank you very much for the suggestion, which makes sense. We'll investigate how much we can relax the constraints for the upcoming release of ART 1.4. For most dependencies we don't have any strict requirements, but there are reasons for restrictions on `scipy` and `scikit-learn`.

ART is now a project of the Linux Foundation for AI and has therefore to be compatible with multiple deployment environments.
