### ISSUE TITLE
Parsing self.is_tensorflow from KerasClassifier input type

### ISSUE THREAD

**Issue by lcadalzo** [Trusted-AI/adversarial-robustness-toolbox#630]
**Describe the bug**
When instantiating the `KerasClassifier` class, ART determines the value of `self.is_tensorflow` by [parsing the string of the model type](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/1.3.1/art/estimators/classification/keras.py#L127-L132). I'm looking to instantiate `KerasClassifier` with a model of a class that wraps the `tf.keras.Model` class. More specifically, the class hierarchy of this model is:

 `(<class 'armory.baseline_models.keras.densenet121_resisc45.OuterModel'>, <class 'tensorflow.python.keras.engine.training.Model'>, ...`

Because the `type` of this model is `<class 'armory.baseline_models.keras.densenet121_resisc45.OuterModel'>`, it's considered to be of an unrecognized type and [an error is raised](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/1.3.1/art/estimators/classification/keras.py#L132).

**To Reproduce**
Run the following command on the `canonicalize-resisc` branch of the `lcadalzo` fork of Armory (https://github.com/lcadalzo/armory/tree/canonicalize-resisc45): 
` python -m armory run scenario_configs/resisc45_baseline_densenet121.json --check`

**Expected behavior**
It would be useful if users could instantiate `KerasClassifier` with models of custom classes that wrap the `tf.keras.Model` class. The code that's breaking here is simply trying to determine the value of `self.is_tensorflow`, so given an alternate solution for making this determination, I believe this should be feasible.

**System information (please complete the following information):**
 - ART 1.3.1
 - TensorFlow 1.15.0

**Comment by beat-buesser** [comment]
Hi @lcadalzo Thank you for raising this issue! We'll add our feature request to ART 1.4.1.
