### ISSUE TITLE
Allow Armory users to turn off progress bars in attacks/defenses

### ISSUE THREAD

**Issue by mzweilin** [Trusted-AI/adversarial-robustness-toolbox#640]
**Is your feature request related to a problem? Please describe.**
Armory has its own progress bar for a scenario. The frequently updated tqdm in ART makes it difficult to read the progress bar in Armory.

**Describe the solution you'd like**
Can we have an option to turn off the progress bars in ART?

I am aware that at least two modules have tqdm enabled:
`art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_pytorch.py`
`art/defences/preprocessor/video_compression.py`

How about adding a keyword argument `show_progress_bar=True` to these modules? I understand that the progress bars could be useful in other scenarios and it should be turned on by default. Just want to have an option for Armory users.

**Describe alternatives you've considered**

**Additional context**

**Comment by beat-buesser** [comment]
Hi @mzweilin Thank you for raising this issue and I think it is a good idea. So far we have the new `verbose` argument in `DeepFool` `Carlini&Wagner attacks` and `ProjectedGradientDescent*` which allows to disable the progress bar, but I agree we should provide `verbose` option for all attacks.
