### ISSUE TITLE
Add backward compatibility for TensorFlow v2 to v1

### ISSUE THREAD

**Issue by paperwhite** [Trusted-AI/adversarial-robustness-toolbox#665]
**Is your feature request related to a problem? Please describe.**
Issue when using TF1 methods by invoking tf.disable_v2_behavior. It doesn't work due to importing TF in the object detection module [tensorflow-faster-rcnn](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/bb7c1773902e4d2f3d43a2418136973eac55cf8d/art/estimators/object_detection/tensorflow_faster_rcnn.py#L103)

**Describe the solution you'd like**
An if conditioned version check based disabling could be a possible solution.

**Comment by beat-buesser** [comment]
Hi @paperwhite Thank you very much for this feature request. So far `TensorFlowFasterRCNN` has only been tested with TensorFlow 1.x.
