### ISSUE TITLE
NaN values in adversarial examples generated by ImperceptibleASRPytorch

### ISSUE THREAD

**Issue by hkakitani** [Trusted-AI/adversarial-robustness-toolbox#672]
For certain inputs, the generate() function of ImperceptibleASRPytorch returns an adversarial example with some NaN values in it. When DeepSpeech tries to transcribe the adversarial example, it predicts an empty string.  

This only occurs for some inputs. So far, I have only experienced this issue with certain clips from speaker 84 from librispeech-dev-clean. I have not experienced this with clips from other speakers, but I have not tested the whole dataset yet. 

Attached below is sample code that reproduces the problem and a sample of some of the generated adversarial examples. 
The code only runs the attack for clips from speaker 84. 
![bug_cap1](https://user-images.githubusercontent.com/59028895/96322357-935d2700-0fcd-11eb-8296-77d4db6576b9.PNG)

Sample output: 
![bug_cap2](https://user-images.githubusercontent.com/59028895/96322409-c9021000-0fcd-11eb-9117-2a0134e4afae.PNG)

 - Python 3.8
 - ART 1.4
 - Torch 1.6

**Comment by beat-buesser** [comment]
Hi @hkakitani Thank you very much for raising this issue, this is very helpful! We'll investigate it and try to fix it.

**Comment by minhitbk** [comment]
This issue was solved by downgrading torch to version 1.4 and torchaudio to version 0.4.0.
