### ISSUE TITLE
Enhance JPegCompression defense

### ISSUE THREAD

**Issue by ng390** [Trusted-AI/adversarial-robustness-toolbox#673]
Is your feature request related to a problem? Please describe.
The ART JPegCompression defense currently operates only on single channel or three channel images. It does not support multichannel images that do not have 3 channels, as in the So2Sat scenario.

Describe the solution you'd like.
If the number of channels in an image is not 1 or 3, the ART JPegCompression defense could be enhanced to loop through each channel separately and compress each channel like a greyscale image.

**Comment by beat-buesser** [comment]
Hi @ng390 Thank you very much for raising this issue! I think this should be a very useful feature.
