### ISSUE TITLE
Enable passing a list for attacks' mask argument

### ISSUE THREAD

**Issue by ng390** [Trusted-AI/adversarial-robustness-toolbox#674]
Is your feature request related to a problem? Please describe.
 The mask input for the PGD attack require an ndarray as an input for the [Numpy](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/ddfb4e29329891731ff2f7d36b114be784db0d03/art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_numpy.py#L173), [Pytorch](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/ddfb4e29329891731ff2f7d36b114be784db0d03/art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_pytorch.py#L143), and [TF2](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/ddfb4e29329891731ff2f7d36b114be784db0d03/art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_tensorflow_v2.py#L142) implementations. It would be convenient if it was possible to pass a list for this argument given that mask is being pulled from a JSON file in my use case.

Describe the solution you'd like. 
For this attack, if the input is a list, it could be cast to an ndarray, perhaps with a few additional checks. Given Issue #652 and #624 are expanding the usage of masks in attacks, it would also be very helpful if a similar option was available for those attacks, especially patch attacks.

**Comment by beat-buesser** [comment]
Hi @ng390 Thank you very much for raising this issue! We'll take a closer look at how to support this feature.
