### ISSUE TITLE
What is the adversarial training approach in classifier?

### ISSUE THREAD

**Issue by HarrialX** [Trusted-AI/adversarial-robustness-toolbox#683]
Hello Dear Developers,

For your provided example [here](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/examples/get_started_pytorch.py), seems like the classifier already do adversarial training inside? And later the step 6 is only a test-stage generation of adversarial samples for testing robustness? If this is a correct understanding, how could I control the technique used for the adversarial training process? Thanks!

**Comment by beat-buesser** [comment]
Hi @HarrialX Thank you very much for your interest in ART! There is no adversarial training in that example, the model is trained in line 70 with plain training using the Adam optimiser defined in line 55.

The examples https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/examples/adversarial_training_data_augmentation.py and https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/examples/adversarial_training_FBF.py show examples of adversarial training with ART. There is also trainer https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/art/defences/trainer/adversarial_trainer_madry_pgd.py which does not have a separate example but can be applied the same way as in the other trainers in the examples.

**Comment by HarrialX** [comment]
Got it, thanks for these very useful recommendations!
