### ISSUE TITLE
classifier accuracy increasing as attack strength (epsilon) increases

### ISSUE THREAD

**Issue by joelma1** [Trusted-AI/adversarial-robustness-toolbox#687]
I have been applying evasion adversarial attacks on medical datasets, and noticed that after attack strength (epsilon) of FGSM, PGD, BIM increases above a certain point, classifier accuracy starts increasing instead of decreasing. 

Is there an underlying reason for this behavior? 

Example plot: 
![image](https://user-images.githubusercontent.com/64549018/97228555-784c9d00-17ad-11eb-9dfb-1418bc090a7d.png)

**Comment by beat-buesser** [comment]
Hi @joelma1 Thank you very much for raising this issue and describing your observations.

Would you be able to provide more details about your experiments like model architecture, model training, dataset, framework (TensorFlow?), ART version, etc.?

Would you be able to share a script or notebook that runs your experiment for us to reproduce?
