### ISSUE TITLE
Make ART_DATA_PATH configurable after import

### ISSUE THREAD

**Issue by davidslater** [Trusted-AI/adversarial-robustness-toolbox#693]
**Is your feature request related to a problem? Please describe.**
When art is imported, `ART_DATA_PATH` is set in `art.config`. There are no APIs for passing either a different config file in after art is imported or modifying this value. Further, since this is imported directly in files throughout ART, such as:
https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/art/estimators/classification/tensorflow.py#L33
```
from art.config import ART_DATA_PATH
```
even directly modifying it directly like
```
art.config.ART_DATA_PATH = "my/data/path"
```
will not affect the other files that import it. For instance:
```
# python
Python 3.7.7 (default, May  7 2020, 21:25:33) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from art import config
>>> config.ART_DATA_PATH = "my/data/path"
>>> from art.estimators.classification import tensorflow
>>> tensorflow.ART_DATA_PATH == config.ART_DATA_PATH
False
```

**Describe the solution you'd like**
Since ART_DATA_PATH is the only attribute in the config file, this would only require changes to how it is used. I recommend:
1) creating a creating this function in `art.config` that modifies the attribute but does not modify the config or saved config:
```
def set_data_path(path):                                                                 
    expanded_path = os.path.abspath(os.path.expanduser(path))                            
    os.makedirs(expanded_path, exist_ok=True)                                            
    if not os.access(expanded_path, os.R_OK):                                            
        raise OSError(f"path {expanded_path} cannot be read from")                       
    elif not os.access(expanded_path, os.W_OK):                                          
        logger.warning(f"path {expanded_path} is read only")                             
                                                                                         
    global ART_DATA_PATH                                                                 
    ART_DATA_PATH = expanded_path                                                        
    logger.info(f"set ART_DATA_PATH to {expanded_path}")
```
Second, this would require modifying the import and usage of `ART_DATA_PATH` throughout art. In particular, import statements such as
```
from art.config import ART_DATA_PATH
```
would need to become
```
from art import config
```

And usage in the files would need to go from
```
ART_DATA_PATH
```
to
```
config.ART_DATA_PATH
```

**Describe alternatives you've considered**
The main alternative I see, which is much simpler but less configurable, is to use ART_DATA_PATH as an environment variable to override the default. This code would look something like (also at the end of the file):
```
_env_path = os.getenv("ART_DATA_PATH")                                                   
if _env_path is not None:                                                                
    ART_DATA_PATH = _env_path                                                            
    logger.warning(f"ART_DATA_PATH overridden by environment variable to {_env_path}")
```

That would look like this:
```
$ ART_DATA_PATH="my/data/path" python
Python 3.7.7 (default, May  7 2020, 21:25:33) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import art
ART_DATA_PATH overridden by environment variable to my/data/path
>>> art.estimators.classification.tensorflow.ART_DATA_PATH
'my/data/path'
```

**Additional context**
This is related to Armory usage.

**Comment by beat-buesser** [comment]
Hi @davidslater Thank you very much for this feature request and detailed description of great solutions! I think the first approach with`art.config` looks good and we'll include it in the upcoming release.
