### ISSUE TITLE
Making numpy object arrays from ragged sequences is deprecated

### ISSUE THREAD

**Issue by davidslater** [Trusted-AI/adversarial-robustness-toolbox#694]
**Describe the bug**
Nothing is broken, currently, but this deprecation warning pops up at multiple places in the toolbox, and may cause errors in later versions of numpy:
```
/workspace/art/estimators/speech_recognition/pytorch_deep_speech.py:279: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  x_ = np.array([x_i for x_i in x] + [np.array([0.1]), np.array([0.1, 0.2])])[:-2]
```

**Recommended Fix**
A simple two-line change would fix this:
```
x_ = np.empty(len(x), dtype=object)
x_[:] = x
```

**Other potential solutions considered**
With the intention of producing a 1D object array, I can think of no single line way of doing this, as
```
x_ = np.array(x, dtype=object)
```
will not always produce a 1D object as can be seen here:
```
>>> x = [np.arange(2), np.arange(2)]
>>> x_ = np.array(x, dtype=object)
>>> x_
array([[0, 1],
       [0, 1]], dtype=object)
>>> x_.shape
(2, 2)
```

**Comment by beat-buesser** [comment]
Hi @davidslater Thank you very much for proposing this update. We were also looking at this deprecation issue and will include a solution in the upcoming release.

**Comment by beat-buesser** [comment]
@davidslater I tested the proposed solution above on branch `development_issue_694` (https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/3ab399e77972b4d9517dfe22ac3c5f7b4c777fd3/art/estimators/speech_recognition/pytorch_deep_speech.py#L279) with our notebook `asr_deepspeech_examples.ipynb` and it seems to fail for prediction of a single array in cell 11:
```
pred1 = speech_recognizer.predict(np.array([x1]), transcription_output=True)
```
with error:
```/opt/conda/lib/python3.7/site-packages/art/estimators/speech_recognition/pytorch_deep_speech.py in predict(self, x, batch_size, **kwargs)
    278 
    279         x_ = np.empty(len(x), dtype=object)
--> 280         x_[:] = x
    281 
    282         # Put the model in the eval mode

ValueError: could not broadcast input array from shape (166960) into shape (1)
```
Have you seen something simila beforer?

**Comment by davidslater** [comment]
Can you print out `x`, `x.dtype`, and `x.shape`?

**Comment by davidslater** [comment]
Sorry, I think that line should be:
```
x_[:] = x[:]
```

**Comment by davidslater** [comment]
No, I'm still getting errors for that as well, hold on.

**Comment by beat-buesser** [comment]
`x1`:
```
array([0.0003357 , 0.00030519, 0.00036622, ..., 0.00210578, 0.00210578,
       0.00158696], dtype=float32)
```
`x1.dtype`:
```
dtype('float32')
```
`x1.shape`:
```
(166960,)
```

**Comment by davidslater** [comment]
I think that this will work:
```
x_[:] = list(x)
```

**Comment by davidslater** [comment]
Alternatively:
```
x_[:] = [x_i for x_i in x]
```

**Comment by davidslater** [comment]
The original one that I sent only works if x is already a list, tuple, generator, iterator, or 1D numpy object array.

**Comment by beat-buesser** [comment]
Great, thank you! I agree, the two solution seem to work for me too. I'll also update `loss_gradient` the line 364 in `predict` accordingly. Can I ask you for a review in a bit?

**Comment by davidslater** [comment]
Sure
