### ISSUE TITLE
Certified accuracy

### ISSUE THREAD

**Issue by ehsankf** [Trusted-AI/adversarial-robustness-toolbox#699]
In the computation of certified accuracy located in [https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/ddfb4e29329891731ff2f7d36b114be784db0d03/notebooks/output_randomized_smoothing_mnist.ipynb]
the samples with the radius zero are removed:
    `num_cert = len(np.where(radius > 0)[0])`

So in the testset if there is only one sample with positive certified radius, the certified accuracy would be `100%` in the interval [0, r], where r is the certified radius of that specific sample. In a nutshell, I believe the samples with zero radii should not be removed from the computation of certified accuracy.

**Comment by beat-buesser** [comment]
Hi @ehsankf Thank you for raising this question! I'm not completely sure, but I think the certified classifier in that notebook returns a radius of value 0 if it abstains from making a prediction. The value of returned `prediction` in these abstaining cases should be -1. I think the notebook tries there to follow the original paper to count only predictions without abstaining to calculate the approximate certified test set accuracy. What do you think?

**Comment by ehsankf** [comment]
It is true. The question is that the computation of the certified accuracy at a specific radius is inclusive or not. 
By looking at the original implementation for RSM it is seen that the radius is inclusive [https://github.com/locuslab/smoothing/blob/78a4d949e4f627d000a78908e001f8ca66c92943/code/analyze.py#L28].

**Comment by beat-buesser** [comment]
I think that makes sense. We probably should change:
```
num_cert = len(np.where(radius > 0)[0])
```
to
```
num_cert = len(np.where(pred != -1)[0])
```
to explicitly only count not-abstaining predictions and
```
rad_idx = np.where(radius > r)[0]
```
to
```
rad_idx = np.where(radius >= r)[0]
```
to count inclusive as the original paper's code. What do you think?

**Comment by ehsankf** [comment]
My understanding is that the samples on which the classifier abstains from prediction are **incorrect too** and should be reflected in the derivation of certified accuracy. 
 Again as a counter example, let's say there are two classifiers and the first classifier abstains to classify all the samples excluding one sample. Then based on this code it is not fair to compare it to a classifier that predicts all the samples without abstaining. So my fix would be to not extract `num_cert` **at all**.

**Comment by beat-buesser** [comment]
I see your point and I think both accuracy definitions can be useful. I think the notebook tries to reproduce the`approximate certified test set accuracy` of Cohen et al. which seems to only count predictions that don't abstain if I read their paper correct. Did you run the notebook with your definition of accuracy? I would be interested to take look at how the accuracy as function of radius would change.

**Comment by ehsankf** [comment]
I just looked at Cohen et al. and what I see for approximate certified accuracy: 

> By “approximate certified accuracy,” we mean that we ran CERTIFY on a subsample of the test set, and for each r we report the fraction of examples on which CERTIFY (a) did not abstain, (b) returned the correct class, and (c) returned a radius R greater than r.

So it is true that they did not consider the examples that are abstained as correct, but they never mentioned that the abstained examples are totally removed from the calculation of certified accuracy (the denominator is `num_cert = len(radius)`). 

Regarding the code I think you may simply run the notebook with the fix `num_cert = len(radius)` and see the differences.

**Comment by beat-buesser** [comment]
Oh, now I see, in another place of the paper they write 

> we instead report
the approximate certified test set accuracy, defined as the
fraction of the test set which CERTIFY classifies correctly
(without abstaining) and certifies robust with a radius R ≥ r.

and `fraction of the test set` means denominator should be `num_cert = len(radius)`. Thank you!

Would you be interested to make pull request? Otherwise we'll update the notebook in the coming days.

**Comment by ehsankf** [comment]
I shall open a pull request. Thanks for following up this discussion.
