### ISSUE TITLE
Change Implementation of Random Restarts in PGD 

### ISSUE THREAD

**Issue by GiulioZizzo** [Trusted-AI/adversarial-robustness-toolbox#714]
In it's current implementation PGD with N random restarts runs a batch N times though the PGD attack and picks the batch with the worst performance with the accuracy being computed averaged on a batch basis.

However, this can give overly optimistic scores of model performance. As a simple example, consider two random restarts and a batch size of 10. The first restart the first 5 examples are classified correctly. The second restart the last 5 are classified correctly. In both cases the accuracy is 50% averaged across the batch. However, on a per sample basis (ie the worst score achieved for a given example) the score is 0%.

As an improvement we can change how the accuracy is computed so that is conducted over each sample.

**Comment by beat-buesser** [comment]
Hi @GiulioZizzo Thank you very much for opening your first feature request for ART and signing up to implement it! I think the proposed changes will further improve the `ProjectedGradientDescent` attack.
