### ISSUE TITLE
data augmentation with classifier.fit

### ISSUE THREAD

**Issue by ZuowenWang0000** [Trusted-AI/adversarial-robustness-toolbox#721]
if there any easy way to do data augmentation (translation, rotation). with the fit method or in the load_cifar10?

Since it's rather standard in any training pipeline.

thx!

**Comment by beat-buesser** [comment]
Hi @ZuowenWang0000 Thank you for your feature request. We will give it consideration as part of our work on improved expectation over transformation features. Data augmentation for plain model training with classifier.fit can be replaced with training the model outside of ART in the respective framework and its data augmentation features. You can also use `fit_generator`, especially for adversarial training, with a framework-specific generator that includes data augmentation steps.

**Comment by ZuowenWang0000** [comment]
thanks!
