### ISSUE TITLE
Support for Python > 3.7 and/or scikit-learn > 0.22

### ISSUE THREAD

**Issue by MohammadSamragh** [Trusted-AI/adversarial-robustness-toolbox#734]
I get the following error when I try to install with pip:

```
ERROR: Could not find a version that satisfies the requirement scikit-learn==0.22.2 (from adversarial-robustness-toolbox==1.4.2) (from versions: 0.9, 0.10, 0.11, 0.12, 0.12.1, 0.13, 0.13.1, 0.14, 0.14.1, 0.15.0b1, 0.15.0b2, 0.15.0, 0.15.1, 0.15.2, 0.16b1, 0.16.0, 0.16.1, 0.17b1, 0.17, 0.17.1, 0.18rc2, 0.18, 0.18.1, 0.18.2, 0.19b2, 0.19.0, 0.19.1, 0.19.2, 0.20rc1, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.20.4, 0.21rc2)
ERROR: No matching distribution found for scikit-learn==0.22.2 (from adversarial-robustness-toolbox==1.4.2)
```

**Comment by beat-buesser** [comment]
Hi @MohammadSamragh My first impression is that your `pip` does not find the most recent versions of `scikit-learn` (only up to 0.21rc). Can you describe a bit more how and where you are installing (e.g. versions, etc.)?

Are you able to `pip install scikit-learn==0.22.2`?

**Comment by MohammadSamragh** [comment]
thanks for the reply.

I upgraded pip but it did not solve the issue. I downgraded my python from 3.8 to 3.6 and it was installed. Turns out that scikit-learn has not released version 0.22.2 for python 3.8.

**Comment by beat-buesser** [comment]
Hi @MohammadSamragh I thought about it and I think we should reopen this issue with the new goal to investigate if we can make ART support Python versions newer than 3.7 and relax the install requirements on `scikit-learn` towards newer versions than 0.22.2.

**Comment by beat-buesser** [comment]
This is issue is now related to #587.

**Comment by smgutstein** [comment]
I've tried to install `ART` within a `conda` virtual environment as follows:

```
(base) me@gimli:~$ conda create -n AdvRobTB python=3.6
...
(AdvRobTB) me@gimli:~$ conda install -c anaconda pip

(AdvRobTB) me@gimli:~$ pip install adversarial-robustness-toolbox all
Collecting adversarial-robustness-toolbox
  Using cached adversarial_robustness_toolbox-1.9.1-py3-none-any.whl (1.2 MB)
 ...
ERROR: Could not find a version that satisfies the requirement all (from versions: none)
ERROR: No matching distribution found for all
...
(AdvRobTB) me@gimli:~$ pip install scikit-learn==0.22.2
...
Successfully installed joblib-1.1.0 numpy-1.19.5 scikit-learn-0.22.2 scipy-1.5.4

(AdvRobTB) me@gimli:~$ pip install adversarial-robustness-toolbox all
Collecting adversarial-robustness-toolbox
  Using cached adversarial_robustness_toolbox-1.9.1-py3-none-any.whl (1.2 MB)
...
ERROR: Could not find a version that satisfies the requirement all (from versions: none)
ERROR: No matching distribution found for all
```

I held my `conda` environment to `Python3.6` and am able to install `scikit-learn 0.22.2`, but still get the original poster's error.
