### ISSUE TITLE
empirical robustness

### ISSUE THREAD

**Issue by ehsankf** [Trusted-AI/adversarial-robustness-toolbox#742]
I wonder if [this line](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/62ffe7c951d8a60d49a9ea6ac7b04aa4432a3fb7/art/metrics/metrics.py#L101):

should be instead:

`idxs = np.argmax(y_pred, axis=1) == np.argmax(y, axis=1)`

**Comment by beat-buesser** [comment]
Hi @ehsankf 

The current code selects the indices of successful adversarial examples and your code above selects the indices of unsuccessful adversarial examples.

Why do you think the code should be your version?
