### ISSUE TITLE
Any example/tutorial that demonstrate the model extraction attacks?

### ISSUE THREAD

**Issue by YuShenLu** [Trusted-AI/adversarial-robustness-toolbox#756]
I cannot find any examples using the model extraction attacks and I would quite like to use it as a part of my experiment...
Is there more information on how to use the model extraction attack than shown [here](https://adversarial-robustness-toolbox.readthedocs.io/en/stable/modules/attacks/extraction.html)?

I tried to use knockoff net but the repo created by the original paper is quite different compare to the one implemented here and I would like to use the algorithm here if possible, so it would be very helpful if there is an example/notebook demostrating it.

**Comment by beat-buesser** [comment]
Hi @YuShenLu Thank you very much for your interest in ART! I think, unfortunately, we don't have any examples or notebooks demonstrating the extraction attacks.

At the moment, the closest to an example would be the unit tests, for Knock-off nets: https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/tests/attacks/test_knockoff_nets.py and similar for other extraction attacks.

If your work leads to a "get-started" example, we would be very happy to include it in ART's example collection

**Comment by beat-buesser** [comment]
Hi @YuShenLu You have just added a new notebook on model extraction attacks and defences to ART: https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/notebooks/model-stealing-demo.ipynb

**Comment by YuShenLu** [comment]
Thank you! I will check this out.
