### ISSUE TITLE
"Only Keras classifiers (v2.2.4) are supported for this defence" in poisoning_defense_neural_cleanse.ipynd

### ISSUE THREAD

**Issue by authwork** [Trusted-AI/adversarial-robustness-toolbox#764]
Dear all, how to guarantee I am using v2.2.4 when I run this defense test?
I try to install keras v2.2.4, but it does not work.
Many thanks.

**Comment by beat-buesser** [comment]
Hi @authwork Thank you very much for using ART!

@ebubae Do you think it would be possible to support other versions of Keras than 2.2.4?

**Comment by ebubae** [comment]
@authwork to install Keras 2.2.4 you may be able to use `pip install keras==2.2.4`

We are definitely trying to support other versions of Keras. The current implementation of the defense had some issues with the optimizer that need to be investigated. @authwork which version of Keras are you using?

**Comment by authwork** [comment]
Then, when I execure to ```graph = tf.get_default_graph()```
It has the following problem (I have tried this before, that's why I said it does not work)
```
global _GRAPH_UID_DICTS
---> 74     graph = tf.get_default_graph()

AttributeError: module 'tensorflow' has no attribute 'get_default_graph'
```
Maybe there are some other requirements for it?

**Comment by ebubae** [comment]
@authwork great that you got it to work! Which version of Tensorflow and Keras are you using for the working version?

**Comment by authwork** [comment]
I used the least version of both and remove the limitation for 2.2.4 in ART.
