### ISSUE TITLE
"Divided by zero issue" using Wasserstein Attack

### ISSUE THREAD

**Issue by wangren09** [Trusted-AI/adversarial-robustness-toolbox#776]
We are using Wasserstein Attack to test a CNN model. When we set the regularization too large, the following error occurs
"raise ValueError("Overflow error in _conjugate_sinkhorn for exponential beta.") ValueError: Overflow error in _conjugate_sinkhorn for exponential beta."

When the regularization is set to a small value, there will be a warning
"python\python37\lib\site-packages\art\attacks\evasion\wasserstein.py:402: RuntimeWarning: divide by zero encountered in log
alpha[I_nonzero_] = (np.log(self.local_transport(K, exp_beta, self.kernel_size)) - np.log(x))[I_nonzero]".

Any one knows the reason?

**Comment by beat-buesser** [comment]
Hi @wangren09 Thank you very much for raising this issue! Could you please provide additional details? To facilitate reproducing this issue, which dataset are you using and what would are the numerical values for the regularization for the too large and the small value cases?

**Comment by wangren09** [comment]
> Hi @wangren09 Thank you very much for raising this issue! Could you please provide additional details? To facilitate reproducing this issue, which dataset are you using and what would are the numerical values for the regularization for the too large and the small value cases?

Sure, we only tested the attack on MNIST. The warning always exists. The error happens when we use regularization=1000, eps_factor=1.1. The error disappears when we set regularization to 100 or set eps_factor to 1.05.

**Comment by beat-buesser** [comment]
I was able to reproduce error and warning with the example script `get_started_tensorflow_v2.py` and the reported values and the default values of `Wasserstein` attack. We'll need to investigate this in more detail.

**Comment by beat-buesser** [comment]
Hi @wangren09 I think I have found two reasons: First the default values of the arguments of `Wasserstein` attack seem to be for CIFAR10 and all might need to be adjusted for MNIST. The second, probably more important, reason seems to be that the exponentiation of `beta` in line 379 of `wasserstein.py` is implemented in single precision which limits the range of possible values for `beta`. Adding `beta = beta.astype(np.float64)` after line 379 seems to solve the second problem with updated arguments for MNIST.

I'll prepare a pull request for this solution for ART 1.5.1.

**Comment by beat-buesser** [comment]
These are the default parameters I have used:
```
attack = Wasserstein(
    estimator=classifier,
    targeted=False,
    regularization=1000.0,
    p=2,
    kernel_size=5,
    eps_step=0.1,
    norm="wasserstein",
    ball="wasserstein",
    eps=0.1,
    eps_iter=5,
    eps_factor=1.4,
    max_iter=50,
    conjugate_sinkhorn_max_iter=200,
    projected_sinkhorn_max_iter=200,
    batch_size=5,
    verbose=True,
)
```

**Comment by beat-buesser** [comment]
Hi @wangren09 I have pushed a solution to #780 . Could you please test it and let me know if it works for you?

**Comment by wangren09** [comment]
> Hi @wangren09 I have pushed a solution to #780 . Could you please test it and let me know if it works for you?

We have tested your new setting on MNIST and the error does not appear. But there is still warning there. The cifar-10 still suffers from the same error while using the default setting. I think the error problem can be solved by changing the parameters. However, it is very sensitive to these parameters and the attack does not seem to work. Besides, the warning does not disappear.

**Comment by beat-buesser** [comment]
Hi @wangren09 I have tested the attack with #780 for CIFAR10 with the following parameters and it seems to work:
```
attack = Wasserstein(estimator=classifier,
        targeted=False,
        regularization=3000.0,
        p=2,
        kernel_size=5,
        eps_step=0.1,
        norm="inf",
        ball="wasserstein",
        eps=0.001,
        eps_iter=10,
        eps_factor=1.17,
        max_iter=400,
        conjugate_sinkhorn_max_iter=400,
        projected_sinkhorn_max_iter=400,
        batch_size=1,
        verbose=True)
```

What are the parameters you are using?

**Comment by wangren09** [comment]
Hi @beat-buesser  I tested on the default setting. The differences between your setting and the default setting are eps, eps_factor, and norm (0.3, 1.1, "wasserstein" in the default setting). There is a "Overflow error in _conjugate_sinkhorn" error under the default setting. It did disappear when I set norm="inf", but the norm="wasserstein" case did not work (Maybe the setting norm="wasserstein" should be tested since this is a non_lp attack).

I also tested on your new setting. There is a "ValueError: the iteration step should be smaller than the total attack eps". It seems that eps_step should be < eps. Was there any other revision besides adding the "beta = beta.astype(np.float64)"? Maybe I am still using the old code.

**Comment by beat-buesser** [comment]
You're right, I forgot to update `eps_step`. I have updated it now in my previous post above to `eps_step=0.0001`. These values can probably depend on the model that is under attack too.

The current default values seem to be a mixture of the paper's MNIST and CIFAR10 experiments and most likely require updates for any case. I selected the values in my two tests according to the paper for MNIST and CIFAR10 and the default values of the author's original implementation and they seem to be quite effectively generating adversarial examples for my small test classifier.

Yes, `beta = beta.astype(np.float64)` is the only required code change, so far.

The case `norm="wasserstein"` might also require different values for the other arguments, I think the values related to `eps` might have to be adjusted to corresponding values in the selected norm.

**Comment by beat-buesser** [comment]
Hi @wangren09 I have updated `eps_step` to 0.001 in my previous posts to make the attack more effective. I have also added two more updates to #780 to prevent the warning `RuntimeWarning: divide by zero` and relax the requirements for `eps_step` to be smaller than or equal to `eps` to be only apply for `norm="inf" because it does not make sense for other norms.
