### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'max_iters' in PoisoningAttackSVM.ipynb

### ISSUE THREAD

**Issue by sohanlal1234** [Trusted-AI/adversarial-robustness-toolbox#777]
**Describe the bug**
TypeError: __init__() got an unexpected keyword argument 'max_iters' in PoisoningAttackSVM

**To Reproduce**
1. Go to Notebooks '
2. Run provenance_defence Notebook . 
 While executing below line of code 
svm_attack = PoisoningAttackSVM(classifier=no_defense, x_train=x_train, y_train=y_train,
                                step=0.1, eps=1.0, x_val=valid_data, y_val=valid_labels, max_iters=200)
![image](https://user-images.githubusercontent.com/8319442/100781149-ac605100-3430-11eb-8019-85003ac1ee08.png)

**System information (please complete the following information):**
 - OS : Windows 10 
 - Python version : 3.7
 - ART version or commit number : 1.5.0

**Comment by ebubae** [comment]
@sohanlal1234 thanks for catching this! This is a issue with the notebook. I will change the notebook to use the correct argument `max_iter`.

Thanks for using ART!
