### ISSUE TITLE
Use tqdm.auto imports for use in notebooks

### ISSUE THREAD

**Issue by zacps** [Trusted-AI/adversarial-robustness-toolbox#798]
**Is your feature request related to a problem? Please describe.**
When running art attacks in a jupyter notebook the progress bars from art attacks display as plain text, instead of jupyter widgets.

**Describe the solution you'd like**
Replace imports in attacks (and anywhere else tqdm is used) from

```python
from tqdm import ...
```

to:

```python
from tqdm.auto import ...
```

**Describe alternatives you've considered**
Alternatively this could be controlled by a keyword argument, but as this is really just dependant on the environment I think an automatic switch is a better solution. A keyword argument could be added to force one style over the other.

**Comment by zacps** [comment]
Additionally, it would be good to set `leave=False`, either by keywork argument or by default.

**Comment by beat-buesser** [comment]
Hi @zacps Thank you very much for opening this feature proposal!
