### ISSUE TITLE
Support for multioutput model 

### ISSUE THREAD

**Issue by aqibsaeed** [Trusted-AI/adversarial-robustness-toolbox#813]
Is it possible to train a multi-output model similar to the following [example](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/examples/get_started_tensorflow_v2.py)? I tried with a custom `train_step` function and multi output model similar to the one in example but get shape mismatch error.

`ValueError: Shape mismatch: The shape of labels (received (<batch size>,)) should equal the shape of logits except for the last dimension (received (<batch size * number of outputs>, <number of classes>)).`

**Comment by aqibsaeed** [comment]
@beat-buesser could you please propose a way to resolve this issue?

**Comment by beat-buesser** [comment]
Hi @aqibsaeed Thank you for your interest in ART!

I think theoretically this should be possible, but right now with ART's focus on single output models might require small modifications and extensions, depending on how far you would like to go with the multi-output model.

To get a better understanding of your plans, can you provide more details like the full stack trace and a code example for `train_step`?

**Comment by aqibsaeed** [comment]
Thank you for the response @beat-buesser. I tried many things but it is not possible currently due to the implementation of `TensorFlowV2Classifier` (see snippet below line 857). I am trying to train a model following [this example ](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/examples/adversarial_training_data_augmentation.py) with `PGD` and `AdversarialTrainer` but replacing `KerasClassifier` with  `TensorFlowV2Classifier`. Here is the example train_step:

https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/99c7efa379d149194cc35c0a564685199f28b4e0/art/estimators/classification/tensorflow.py#L857

```
loss_object = tf.keras.losses.CategoricalCrossentropy()
def train_step(model, x, y_a, y_b, y_c):
    with tf.GradientTape() as tape:
        pred_a, pred_b, pred_c = model(x, training=True)
        loss_a = loss_object(pred_a, y_a)
        loss_b = loss_object(pred_b, y_b)
        loss_c = loss_object(pred_c, y_c)
        total_loss = loss_a + loss_b + loss_c
    gradients = tape.gradient(total_loss, model.trainable_weights)
    optimizer.apply_gradients(zip(gradients, model.trainable_weights))
```

**Comment by beat-buesser** [comment]
@aqibsaeed These are modifications that I expected above, but more changes are probably required.  Do you plan to calculate loss gradients on`total_loss` in `train_step`? Did you also modify `AdversarialTrainer` and `ProjectedGradientDescent` accordingly?

**Comment by aqibsaeed** [comment]
Yes the gradients will be calculated using total_loss. I made changes in `AdversarialTrainer` but that's not the only thing that need to be changed. The implementation of `fit` in `TensorFlowV2Classifier` also needs to be changed accordingly.  https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/99c7efa379d149194cc35c0a564685199f28b4e0/art/estimators/classification/tensorflow.py#L857

That's the reason I opened this issue. Is there any easy way to make and train a multi-output model?

**Comment by beat-buesser** [comment]
I see. At the moment, these are the changes that I would currently expect to be required for multi-output models since ART focuses on single output models so far. But I find your case an interesting example for us to think about abstracting the data to enable more complex models including multi-output models in the near future.

It looks like you are getting close to make it work for your case. In which line is the `ValueError` in your first post raised?
