### ISSUE TITLE
Expand range of eps_step (and potentially eps) in PGD

### ISSUE THREAD

**Issue by davidslater** [Trusted-AI/adversarial-robustness-toolbox#823]
**Is your feature request related to a problem? Please describe.**
a) Enable the `eps_step` parameter to take values greater than `eps`. Currently, the max value is `eps`, though if taking a step from the boundary, the distance to the other side of the Lp ball is `2 * eps`. So, at the minimum, I would recommend allowing up to that value. However, since clipping and projection are performed after the step, I don't see a reason that `eps_step` couldn't be even larger.
b) Enable `eps_step = np.inf` (in particular, when `eps = np.inf`). If `eps` is infinite and `eps_step` is finite, it works fine, but if both are infinite, nans show up and cause errors. 
c) (Optional) Enable `eps = 0`. This would in principle be a no-op, but could be a useful test, e.g., checking for modifications to the input by the model.

**Describe the solution you'd like**
These would only require a couple of minor one-or-two line changes in `__init__` (a and c) and `_apply_perturbation` (b).

**Comment by beat-buesser** [comment]
Hi @davidslater Thank you very much for the detailed feature request, I think they make sense. Item a) should already be supported for norm `inf` but this request would extend support for all norms.

**Comment by beat-buesser** [comment]
I have updated my previous comment.
