### ISSUE TITLE
Better PGD handling of NaN and Inf gradient outputs

### ISSUE THREAD

**Issue by davidslater** [Trusted-AI/adversarial-robustness-toolbox#824]
**Is your feature request related to a problem? Please describe.**
Currently, if the gradient produces a single nan during PGD (at least for `norm != inf`), it propagates to the rest of the produced adversarial sample (and in PyTorch, it crashes). This happens most clearly here:
https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_pytorch.py#L284-L293
While `.sign()` in torch directly maps nan to 0, the normalization for L1 and L2 will make `grad` equal to nan for all values if a single element is nan.

**Describe the solution you'd like**
A) Looks for NANs and generate warnings when they occur.
B) Set NANs to 0 when they do occur.
In torch, a simple solution to B that solves my specific problem would be to add this before L284:
```
grad[grad.isnan()] = 0
```
There are some edge cases where infinite values and masks could also generate nans, and I can walk through some of those as well.

**Describe alternatives you've considered**
The primary alternative would be to modify the estimator. While most model gradients and typically well behaved with respect to the weights, they are not always so well behaved with respect to the input, and it can be difficult to remove nan-generating edge cases from models. As an example, in one recent model I was working with, if the audio sample was zero-padded, it would generate nan gradients for the first section of the input. However, I do not have an easy way to modify the model to remove that issue, so this would be a difficult process.

**Comment by beat-buesser** [comment]
Hi @davidslater Thank you very much for raising this improvement and providing a possible solution, I think this will make ART's PGD more robust for many users.
