### ISSUE TITLE
Implement Convex Polytope clean label attack 

### ISSUE THREAD

**Issue by Nathalie-B** [Trusted-AI/adversarial-robustness-toolbox#831]
**Is your feature request related to a problem? Please describe.**
This attack allows for transferability of clean label attacks.

**Describe the solution you'd like**
Implementation of the paper Transferable Clean-Label Poisoning Attacks on Deep Neural Nets 
https://arxiv.org/abs/1905.05897

**Describe alternatives you've considered**
NA

**Additional context**
NA

@ebubae

**Comment by beat-buesser** [comment]
Hi @Nathalie-B Thank you very much for proposing and implementing this new poisoning attack!
