### ISSUE TITLE
'BlackBoxClassifier' object has no attribute 'channels_first'

### ISSUE THREAD

**Issue by Code-Ranger** [Trusted-AI/adversarial-robustness-toolbox#837]
**Describe the bug**
Tried to working on black-box evision attacking like SimBA and Square Attack by based on the example code from https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/notebooks/classifier_blackbox.ipynb , but got the error report that there is no attribute "channels_first" in BlackBoxClassifier.

**To Reproduce**
1. based on the example code of https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/notebooks/classifier_blackbox.ipynb
2. change the black-box attacking method to SimBA or SquareAttack
3. See error

Traceback (most recent call last):
  File "/home/ranger/lizhu/src/art/square_attack.py", line 93, in <module>
    x_adv = attack.generate(x=np.array([target_image]), x_adv_init=x_adv)
  File "/home/ranger/tools/anaconda/lib/python3.8/site-packages/art/attacks/attack.py", line 74, in replacement_function
    return fdict[func_name](self, *args, **kwargs)
  File "/home/ranger/tools/anaconda/lib/python3.8/site-packages/art/attacks/evasion/square_attack.py", line 133, in generate
    if self.estimator.channels_first:
AttributeError: 'BlackBoxClassifier' object has no attribute 'channels_first'

**Expected behavior**
there should be parameters for BlackBoxClassifier to specify the 'channel_first'.

**Comment by beat-buesser** [comment]
Hi @Code-Ranger Thank you very much for using ART and for notifying us of this bug! We'll fix it in the next release of ART 1.5.2.

**Comment by beat-buesser** [comment]
Hi @Code-Ranger I have pushed a possible solution to #849. It required the introduction of a new `BlackBoxClassifierNeuralNetwork` to support `channels_first` for `SimBA` and `Square attack. Does the notebook work for you if you replace `BlackBoxClassifier` with `BlackBoxClassifierNeuralNetwork`?

**Comment by Code-Ranger** [comment]
> Hi @Code-Ranger I have pushed a possible solution to #849. It required the introduction of a new `BlackBoxClassifierNeuralNetwork` to support `channels_first` for `SimBA` and `Square attack. Does the notebook work for you if you replace `BlackBoxClassifier`with`BlackBoxClassifi

**Comment by beat-buesser** [comment]
Hi @Code-Ranger 
`BlackBoxClassifierNeuralNetwork` is still on a development branch `development_issue_837` and not yet in the docs. You can install it from `development_issue_837` and import it with `from art.estimators.classification import BlackBoxClassifierNeuralNetwork`. Please let me know if it works for you and we'll add it to the next release.
