### ISSUE TITLE
JSMA only iterates once when clip_values is not set

### ISSUE THREAD

**Issue by mamerzouk** [Trusted-AI/adversarial-robustness-toolbox#841]
I noticed some incomprehensible behavior in `art.attacks.evasion.SaliencyMapMethod()` (JSMA).
The method is supposed to work even without `clip_values` but I noticed that if it is not set, the method only perturbs 2 features and stops.
When I checked the code with more attention, I found that if `clip_values` is not set, the `search_space` (which is one of the stop conditions) is initialized with zeros. So right after the first iteration (which perturbs 2 features), it does not satisfy the condition.

What I think would be better is to initialize `search_space` with ones when `clip_values` are not set. When `clip_values` is set, `search_space` can be initialized with zeros and then the right features can be activated.

Actual implementation :
```
#Initialize the search space; optimize to remove features that can't be changed
search_space = np.zeros(batch.shape)
if self.estimator.clip_values is not None:
    clip_min, clip_max = self.estimator.clip_values
    if self.theta > 0:
        search_space[batch < clip_max] = 1
    else:
        search_space[batch > clip_min] = 1
```
Proposed solution :
```
#Initialize the search space; optimize to remove features that can't be changed
search_space = np.ones(batch.shape)
if self.estimator.clip_values is not None:
    search_space = np.zeros(batch.shape)
    clip_min, clip_max = self.estimator.clip_values
    if self.theta > 0:
        search_space[batch < clip_max] = 1
    else:
        search_space[batch > clip_min] = 1
```

**Comment by beat-buesser** [comment]
Hi @mamerzouk Thank you for raising this issue! On a first look, I think your proposed solution makes sense. The line `search_space = np.ones(batch.shape)` could also be moved to an `else` block at the end of the code snippet.

I just noticed your pull request #843, let me take a look.
