### ISSUE TITLE
Batch SimBA

### ISSUE THREAD

**Issue by lihuiknight** [Trusted-AI/adversarial-robustness-toolbox#855]
Dear author, 

according to the paper: **simple black-box adversarial attacks**, it seems that it's very difficult to implement the batch version for SimBA because the condition for the for loop is sample-dependent. Is there any friendly implementation for the batch SimBA?

**Comment by beat-buesser** [comment]
Hi @lihuiknight No, the current implementation of the attack `SimBA` only accepts `batch_size=1`.
