### ISSUE TITLE
SimBA bug? inconsistent with the original paper 

### ISSUE THREAD

**Issue by lihuiknight** [Trusted-AI/adversarial-robustness-toolbox#856]
Dear authors,

I read carefully for the implementation of SimBA. The implementation is inconsistent with the original paper.

Specifically, in this [line](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/art/attacks/evasion/simba.py#L194), the x will be updated no matter whether the attack is successful. 
However, according to the Algorithm 1 in SimBA paper, the original x will never updated. please have a check.

**Comment by lihuiknight** [comment]
the algorithm from the original paper updates delta, it has the equivalence relation with updating x.

i close this issue.

**Comment by beat-buesser** [comment]
Hi @lihuiknight Thank you very much for testing ART!

I close the issue based on the previous message. Please feel free to reopen if necessary.
