### ISSUE TITLE
Problem loading pretrained Keras models in an ART tutorial

### ISSUE THREAD

**Issue by mmaras-tessella** [Trusted-AI/adversarial-robustness-toolbox#870]
When running the adversarial_training_mnist.ipynb notebook, the two trained models cannot be loaded. 

1. Run the notebook: https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/notebooks/adversarial_training_mnist.ipynb
2. In [8]: 
path = get_file('mnist_cnn_robust.h5', extract=False, path=config.ART_DATA_PATH, url='https://www.dropbox.com/s/yutsncaniiy5uy8/mnist_cnn_robust.h5?dl=1')
robust_classifier_model = load_model(path)
3. Loading the model results in this error:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-23-a41d37d60adb> in <module>
      1 path = get_file('mnist_cnn_robust.h5', extract=False, path=config.ART_DATA_PATH,
      2                 url='https://www.dropbox.com/s/yutsncaniiy5uy8/mnist_cnn_robust.h5?dl=1')
----> 3 robust_classifier_model = keras.models.load_model(path)

~\Anaconda3\envs\tf21\lib\site-packages\tensorflow_core\python\keras\saving\save.py in load_model(filepath, custom_objects, compile)
    144   if (h5py is not None and (
    145       isinstance(filepath, h5py.File) or h5py.is_hdf5(filepath))):
--> 146     return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
    147 
    148   if isinstance(filepath, six.string_types):

~\Anaconda3\envs\tf21\lib\site-packages\tensorflow_core\python\keras\saving\hdf5_format.py in load_model_from_hdf5(filepath, custom_objects, compile)
    166     model_config = json.loads(model_config.decode('utf-8'))
    167     model = model_config_lib.model_from_config(model_config,
--> 168                                                custom_objects=custom_objects)
    169 
    170     # set weights

~\Anaconda3\envs\tf21\lib\site-packages\tensorflow_core\python\keras\saving\model_config.py in model_from_config(config, custom_objects)
     53                     '`Sequential.from_config(config)`?')
     54   from tensorflow.python.keras.layers import deserialize  # pylint: disable=g-import-not-at-top
---> 55   return deserialize(config, custom_objects=custom_objects)
     56 
     57 

~\Anaconda3\envs\tf21\lib\site-packages\tensorflow_core\python\keras\layers\serialization.py in deserialize(config, custom_objects)
    104       module_objects=globs,
    105       custom_objects=custom_objects,
--> 106       printable_module_name='layer')

~\Anaconda3\envs\tf21\lib\site-packages\tensorflow_core\python\keras\utils\generic_utils.py in deserialize_keras_object(identifier, module_objects, custom_objects, printable_module_name)
    290     config = identifier
    291     (cls, cls_config) = class_and_config_for_serialized_keras_object(
--> 292         config, module_objects, custom_objects, printable_module_name)
    293 
    294     if hasattr(cls, 'from_config'):

~\Anaconda3\envs\tf21\lib\site-packages\tensorflow_core\python\keras\utils\generic_utils.py in class_and_config_for_serialized_keras_object(config, module_objects, custom_objects, printable_module_name)
    252   cls_config = config['config']
    253   deserialized_objects = {}
--> 254   for key, item in cls_config.items():
    255     if isinstance(item, dict) and '__passive_serialization__' in item:
    256       deserialized_objects[key] = deserialize_keras_object(

AttributeError: 'list' object has no attribute 'items'

Expected behavior:
The Keras model (h5 file) is expected to load.

Screenshots:
![image](https://user-images.githubusercontent.com/69858478/105982368-78538600-6097-11eb-93e2-3cb488821515.png)

System information:
 - Windows 10
 - Python version 3.7
 - ART version 1.5.1
 - TensorFlow 2.1

**Comment by beat-buesser** [comment]
Hi @mmaras-tessella Thank you very much for reporting this notebook issue! we'll take a look as soon as possible.

**Comment by beat-buesser** [comment]
Hi @mmaras-tessella I have tested the notebook with ART 1.5.1 on my Linux machine and it seems to run without problems. The problem could be related to your Windows OS. Did the call to `get_file`, in the line before the error occurs, download the file correctly?
