### ISSUE TITLE
square attack fails with 2 norm against pytorch classifier, due to tensor type mismatch

### ISSUE THREAD

**Issue by Embeddave** [Trusted-AI/adversarial-robustness-toolbox#874]
**Describe the bug**
When generating square attack with 2 norm against a PyTorch classifier, a `RuntimeError` gets thrown:  
```
RuntimeError: Input type (torch.cuda.DoubleTensor) and weight type (torch.cuda.FloatTensor) should be the same
```

Within the `square_attack` module, this results from (higher up the traceback):
```
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/disarm-EwujDfbL-py3.7/lib/python3.7/site-packages/art/attacks/evasion/square_attack.py", line 296, in generate
    sample_logits_diff_new = self._get_logits_diff(x_robust_new, y_robust)
```
Full traceback attached as a .txt file
[squareattack-l2-pytorchclassifier.txt](https://github.com/Trusted-AI/adversarial-robustness-toolbox/files/5884307/squareattack-l2-pytorchclassifier.txt)

I stepped through with `pdb` and I think the source of the error is here when `delta_init` is instantiated.
It's `dtype` is `np.float64`:
https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/82727cb56975a1a41eca86e1ef669ad675646cc7/art/attacks/evasion/square_attack.py#L262

Maybe the fix is just to append a method call `.astype(ART_NUMPY_DTYPE)` to that call to `np.zeros`?

I noticed that `self.eps` is also `np.float64`, not sure if that could also cause "upcasting" in line 290:
```
                x_robust_new = np.clip(
                    x_robust + delta_init / np.sqrt(np.sum(delta_init ** 2, axis=(1, 2, 3), keepdims=True)) * self.eps,
                    self.estimator.clip_values[0],
                    self.estimator.clip_values[1],
                )
```

**To Reproduce**

Here's a unit test that should error when `image_dl_estimator` returns a `PytorchClassifier`, if I'm grokking the bug correctly

```
@pytest.mark.framework_agnostic
def test_generate(art_warning, fix_get_mnist_subset, image_dl_estimator_for_attack):
    try:
        classifier = image_dl_estimator_for_attack(SquareAttack)

        attack = SquareAttack(estimator=classifier, norm=2, max_iter=5, eps=0.3, p_init=0.8, nb_restarts=1)

        (x_train_mnist, y_train_mnist, x_test_mnist, y_test_mnist) = fix_get_mnist_subset

        x_train_mnist_adv = attack.generate(x=x_train_mnist, y=y_train_mnist)

        assert np.mean(np.abs(x_train_mnist_adv - x_train_mnist)) == pytest.approx(0.053533513, abs=0.025)
        assert np.max(np.abs(x_train_mnist_adv - x_train_mnist)) == pytest.approx(0.3, abs=0.05)
    except ARTTestException as e:
        art_warning(e)
```

**Expected behavior**

Not failing

**Screenshots**

**System information (please complete the following information):**
 - OS: Ubuntu 18.04
 - Python version: 3.7.6
 - ART version or commit number: 1.5.1
 - Pytorch 1.6.0

**Comment by beat-buesser** [comment]
Hi @Embeddave Thank you very much for reporting this issue! This looks like a bug, we'll fix it as soon as possible.

**Comment by beat-buesser** [comment]
Hi @Embeddave I have opened a pull request with a solution in #877
