### ISSUE TITLE
Include exclusionary reclassification technique to activation clustering as poisoning defense 

### ISSUE THREAD

**Issue by Nathalie-B** [Trusted-AI/adversarial-robustness-toolbox#875]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Please implement exclusionary reclassification as part of activation clustering defense.

**Describe alternatives you've considered**
N/A

**Comment by beat-buesser** [comment]
Hi @ebubae and @Nathalie-B Thank you for implementing the exclusionary reclassification technique in the activation clustering poisoning defense!
