### ISSUE TITLE
Implement Over-the-Air Adversarial Flickering Attacks against Video Recognition Networks

### ISSUE THREAD

**Issue by beat-buesser** [Trusted-AI/adversarial-robustness-toolbox#881]
Paper link: https://arxiv.org/abs/2002.05123

**Comment by kwockn17** [comment]
Hello. I am interested in working on this issue.

**Comment by gabeorlanski** [comment]
I am interested in working on this issue.

**Comment by seanhung07** [comment]
I'm interested in working on this issue.

**Comment by jfang2799** [comment]
I would be interested in working on this issue.
