### ISSUE TITLE
dtype issue in security_curve.py

### ISSUE THREAD

**Issue by keykholt** [Trusted-AI/adversarial-robustness-toolbox#884]
**Describe the bug**
On the current version of ART, the security_curve module exits with an error due to the eps value not matching the `float` type. More specifically, when ` _check_gradient()` is called during a security_curve evaluation, the function defines eps as: `kwargs["eps"] = classifier.clip_values[1]`. Later, when the PGD attack object is created, the PGD code performs a parameter check in `_check_params()`, which fails.

```
if not (isinstance(self.eps, (int, float, np.ndarray)) and isinstance(self.eps_step, (int, float, np.ndarray))):
            raise TypeError(
                "The perturbation size `eps` and the perturbation step-size `eps_step` must have the same type."
            )
```

The check fails because `classifier.clip_values[1]` is of type `numpy.float32`, which is not recognized as a `float` type. This may be due to a numpy issue with types. The current workaround I have is to change `kwargs["eps"] = classifier.clip_values[1]` -> `kwargs["eps"] = float(classifier.clip_values[1])`

**To Reproduce**
Run the notebook in notebooks/art_evaluations/security_curve.ipynb. In my current environment, the notebook fails when `_check_gradient()` is called

**Expected behavior**
The notebook to run

**Screenshots**
```
print(classifier.clip_values[1])
print('-----------------')
max_iter=100
kwargs_pgd["eps"] = classifier.clip_values[1]
kwargs_pgd["eps_step"] = classifier.clip_values[1] / (max_iter / 2)
print(type(kwargs_pgd["eps"]), kwargs_pgd["eps"])
print(isinstance(kwargs_pgd["eps"] , (int, float, np.ndarray))) <------- This check is performed when the PGD object is made
print(type(kwargs_pgd["eps_step"]), kwargs_pgd["eps_step"])
print(isinstance(kwargs_pgd["eps_step"], (int, float, np.ndarray))) <------- This check is performed when the PGD object is made
----------------------------------------------------------------------------------------------------------------------------------------
OUTPUT
255.0
-----------------
<class 'numpy.float32'> 255.0
False.  <-------- This results in _check_gradient throwing an error because apparently a numpy.float32 is not one of these types (int, float, np.ndarray)
<class 'numpy.float64'> 5.1
True
```

**System information (please complete the following information):**
 - ART 1.15.0
 - Python 3.7.9
 - Numpy 1.19.2

**Comment by beat-buesser** [comment]
Hi @keykholt Thank you very much for reporting this issue!
