### ISSUE TITLE
Incorrect import statements in notebooks/attack_membership_inference.ipynb

### ISSUE THREAD

**Issue by evansakmar** [Trusted-AI/adversarial-robustness-toolbox#897]
**Describe the bug**
Incorrect import statements in _notebooks/attack_membership_inference.ipynb_

**To Reproduce**
Start the notebook _notebooks/attack_membership_inference.ipynb_

Both "Rule-based attack" and "Train attack model" fail to run due to import errors.
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-e4caf591daac> in <module>()
      1 import numpy as np
----> 2 from art.attacks.inference import MembershipInferenceBlackBoxRuleBased
      3 
      4 attack = MembershipInferenceBlackBoxRuleBased(art_classifier)
      5 

ImportError: cannot import name 'MembershipInferenceBlackBoxRuleBased'
```

**Expected behavior**
Should import the classes and run the code.

**System information (please complete the following information):**
 - OS: MacOS
 - Python version: 3.6.9
 - ART version or commit number: 065ac24e7f5ec124f6cfe39ce21f085f4c87a401
 - TensorFlow / Keras / PyTorch / MXNet version: TensorFlow 2.4, Keras 2.4.3 torch 1.6.0+cu92, MXNet 1.6.0

**Comment by evansakmar** [comment]
I have an incoming pull request for this.

**Comment by beat-buesser** [comment]
Hi @evansakmar Thank you very much, that's really great!
