### ISSUE TITLE
GPU support for MembershipInferenceBlackBox#infer

### ISSUE THREAD

**Issue by evansakmar** [Trusted-AI/adversarial-robustness-toolbox#899]
**Describe the bug**
Whenever you run _infer_ on _MembershipInferenceBlackBox_ you get a CUDA runtime error. 

The _fit_ method seems to handle CUDA properly already.  Noting the _to_cuda_ method.

**To Reproduce**
- Run MembershipInferenceBlackBox#infer on a cuda enabled instance.  
- Or run through the _notebooks/attack_membership_inference.ipynb_ notebook in a CUDA enable instance.
- Or run the membership inference tests on a CUDA enabled instance. 

**Expected behavior**
It should run properly without erroring out

**Stacktrace**
RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at /pytorch/aten/src/THC/THCCachingHostAllocator.cpp:278

**System information (please complete the following information):**
 - OS: Ubuntu 18.04
 - CUDA: 10.1
 - Python version: 3.6.9
 - ART version or commit number: 065ac24
 - TensorFlow / Keras / PyTorch / MXNet version: TensorFlow 2.4, Keras 2.4.3 torch 1.6.0+cu92, MXNet 1.6.0

**Comment by evansakmar** [comment]
I also have an incoming PR for this

**Comment by beat-buesser** [comment]
Hi @ehsankf Thank you very much!

**Comment by ehsankf** [comment]
@beat-buesser

Hello, 

This issue has not been opened by me.

**Comment by beat-buesser** [comment]
Hi @ehsankf Thank you for notifying me, it must have been an autocomplete accident with user names starting with letter e. I wanted to mention @evansakmar above.
