### ISSUE TITLE
Does the implementation of side length schedule on square attack make sense?

### ISSUE THREAD

**Issue by lihuiknight** [Trusted-AI/adversarial-robustness-toolbox#903]
Dear authors, i read your implementation of square attack. It's a little bit of confusing about the function [`_get_percentage_of_elements` ](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/ad42a790c83e70f99c8defd2d1876df0250c676e/art/attacks/evasion/square_attack.py#L105). 
Specifically,  i notice that the side length schedule is from large length to the small length. I think the version from small to large will be more reasonable and realistic. What do you think?

**Comment by beat-buesser** [comment]
Hi @lihuiknight Thank you very much for raising this question!

I think this implementation is following the original publication of SquareAttack to half the size of `p` and therefore reduce the size of the added square perturbations with the goal to start with large scale perturbations first and adding smaller, in some sense detail, perturbations in later iterations.

**Comment by beat-buesser** [comment]
On a second thought, it might be interesting to test what would happen if you reverse the order to from small to large. Let me know what you find out and how the results compare to from large to small.

**Comment by lihuiknight** [comment]
I find perturbation from small to large works well. it's more suitable for our applications.

**Comment by beat-buesser** [comment]
Hi @lihuiknight That's great news! Is you application image classification?

Would you be able to make a pull request on making the order of `p` an option of `SqaureAttack`?
