### ISSUE TITLE
Adoption of DecisionTreeClassifier on FastGradient attack

### ISSUE THREAD

**Issue by ivanv6** [Trusted-AI/adversarial-robustness-toolbox#904]
Dear all, i'm trying to use the FastGradientMethod to execute an attack against a DecisionTreeClassifier. Here you can find the code:

```
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
import numpy as np

from art.attacks.evasion import FastGradientMethod
from art.estimators.classification.scikitlearn import ScikitlearnDecisionTreeClassifier
from art.utils import load_mnist

# Step 1: Load the MNIST dataset

(x_train, y_train), (x_test, y_test), min_pixel_value, max_pixel_value = load_mnist()

# Step 1a: Flatten dataset

nb_samples_train = x_train.shape[0]
nb_samples_test = x_test.shape[0]
x_train = x_train.reshape((nb_samples_train, 28 * 28))
x_test = x_test.reshape((nb_samples_test, 28 * 28))

# Step 2: Create the model

model = DecisionTreeClassifier()

# Step 3: Create the ART classifier

classifier = ScikitlearnDecisionTreeClassifier(model=model, clip_values=(min_pixel_value, max_pixel_value))

# Step 4: Train the ART classifier

classifier.fit(x_train, y_train)

# Step 5: Evaluate the ART classifier on benign test examples

predictions = classifier.predict(x_test)
accuracy = np.sum(np.argmax(predictions, axis=1) == np.argmax(y_test, axis=1)) / len(y_test)
print("Accuracy on benign test examples: {}%".format(accuracy * 100))

# Step 6: Generate adversarial test examples
attack = FastGradientMethod(estimator=classifier, eps=0.2)
x_test_adv = attack.generate(x=x_test)

# Step 7: Evaluate the ART classifier on adversarial test examples

predictions = classifier.predict(x_test_adv)
accuracy = np.sum(np.argmax(predictions, axis=1) == np.argmax(y_test, axis=1)) / len(y_test)
print("Accuracy on adversarial test examples: {}%".format(accuracy * 100))
```

It returns this error:
`EstimatorError: FastGradientMethod requires an estimator derived from <class 'art.estimators.estimator.BaseEstimator'> and <class 'art.estimators.estimator.LossGradientsMixin'>, the provided classifier is an instance of <class 'art.estimators.classification.scikitlearn.ScikitlearnDecisionTreeClassifier'> and is derived from (<class 'art.estimators.classification.scikitlearn.ScikitlearnClassifier'>,).`

How can I handle it? Thanks a lot

**Comment by beat-buesser** [comment]
Hi @ivanv6 Thank you very much for exploring ART!

This error tries to express that the attack and estimator are not compatible with each other. In this specific case the reason is that `FastGradientMethod` is an attack calculating a model's loss gradients, but `DecisionTreeClassifier` is an estimator that cannot provide loss gradients because of its underlying decision tree model.

A possible attack on decision tree classifiers would be `DecisionTreeAttack`.
