### ISSUE TITLE
Implement mini-batch version of BoundaryAttack

### ISSUE THREAD

**Issue by lihuiknight** [Trusted-AI/adversarial-robustness-toolbox#905]
Dear authors, according to the implementation of boundary attack at [line](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/ad42a790c83e70f99c8defd2d1876df0250c676e/art/attacks/evasion/boundary.py#L207), it seems that all the samples share the same initial starting point and target. Why not use different initial data?

**Comment by lihuiknight** [comment]
sorry, i notice that there is a for loop in this [line ](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/ad42a790c83e70f99c8defd2d1876df0250c676e/art/attacks/evasion/boundary.py#L152), the instance-based implementation will be very time-consuming, do you plan to make a mini-batch version?

**Comment by beat-buesser** [comment]
Hi @lihuiknight Thank you very much for your questions! To the question about mini-batches, I think it's very interesting and possible in the near future, similar to ZOO (#845).

Would you be interested to try implementing a solution for mini-batches?

**Comment by lihuiknight** [comment]
Yes. I will implement a mini-batch version for boundary attack.

**Comment by beat-buesser** [comment]
Great! Let us know if you need any support from us!

**Comment by LorenzoAgnolucci** [comment]
Hello @lihuiknight, have you already implemented the mini-batch version? It would be really useful to me. Thanks in advance!

**Comment by lihuiknight** [comment]
@beat-buesser @LorenzoAgnolucci  I'd like to implement SimBA in mini-batch version first, because such method is very simple and will be helpful in my application. Then I'd implement other method in mini-batch version later.  If you have already implemented the methods in mini-batch version, pls let me know.

BTW, the mini-batch version will be really helpful especially in the scenarios of adversarial training with attack and defense.

**Comment by beat-buesser** [comment]
Hi @lihuiknight That sounds good. As far as I know, SimBA has not been implemented in mini-batch version so far. Also let us know if you need help or support.

Hi @LorenzoAgnolucci Would you be interested to help with the mini-batch version of `BoundaryAttack`?

**Comment by beat-buesser** [comment]
Hi @lihuiknight and @LorenzoAgnolucci We have now support for mini-batches in model predictions for `BoundaryAttack` and `HopSkipJump` implemented by @amodas (#971) on our branch `dev_1.6.1` to be released with ART 1.6.1 which makes these attacks much faster.
