### ISSUE TITLE
Don't overwrite labels in PyTorch Faster-RCNN's loss_gradient()

### ISSUE THREAD

**Issue by lcadalzo** [Trusted-AI/adversarial-robustness-toolbox#928]
**Is your feature request related to a problem? Please describe.**
ART's PyTorch Faster R-CNN's `loss_gradient()` overwrites the input `y` variable, converting "boxes", "labels", and "scores" arrays to torch tensors, unexpectedly modifying the `y` variable that is passed to it. 

**Describe the solution you'd like**
Making a copy of the `y` variable in the estimator's `loss_gradient()`, i.e adding something like the following [here](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/1.4.2/art/estimators/object_detection/pytorch_faster_rcnn.py#L161) which I've tested locally:
```
import copy
y_copy = copy.deepcopy(y)
if y is not None and isinstance(y[0]["boxes"], np.ndarray):
    for i, y_i in enumerate(y_copy):
        y_copy[i]["boxes"] = torch.from_numpy(y_i["boxes"]).type(torch.float).to(self._device)
        y_copy[i]["labels"] = torch.from_numpy(y_i["labels"]).type(torch.int64).to(self._device)
        y_copy[i]["scores"] = torch.from_numpy(y_i["scores"]).to(self._device)
```

**Additional context**
I'm using ART 1.4.2 but it looks like this will occur in other versions as well. The reason this came up is since Armory's metrics code expects the boxes/labels/scores arrays to be numpy arrays, so this is causing an error there.

**Comment by beat-buesser** [comment]
Hi @lcadalzo I think your proposal makes sense, we'll include it in one of the upcoming releases.
