### ISSUE TITLE
 the input type (torch.cuda.DoubleTensor) and the weight type ( FloatTensor) should be the same. torch.cuda.

### ISSUE THREAD

**Issue by zhangshuaizxc** [Trusted-AI/adversarial-robustness-toolbox#933]
Running adversarial_training_FBF.py in the example in adversarial-robustness-toolbox version 1.5.0 gives a RuntimeError. the input type (torch.cuda.DoubleTensor) and the weight type ( FloatTensor) should be the same. torch.cuda.

**Comment by beat-buesser** [comment]
Hi @zhangshuaizxc Thank you very much for reporting this issue. We have fixed it with ART 1.5.2.

**Comment by zhangshuaizxc** [comment]
Thank you for your contribution.
