### ISSUE TITLE
Zoo, Carlini&Wegner and JSM attacks

### ISSUE THREAD

**Issue by ivanv6** [Trusted-AI/adversarial-robustness-toolbox#934]
Hi, thanks a lot for your incredible work. A quick question, is possible to use the Zoo, Carlini&Wegner and JSM attacks by using a Keras neural network as classifier? Thanks a lot

**Comment by beat-buesser** [comment]
Hi @ivanv6 Thank you very much for your kind words, this is great motivation! Yes, we have full support for Keras models. There are two options: `art.estimators.classification.KerasClassifier` for models of `keras` and `tensorflow.keras` without eager execution and `art.estimators.classification.TensorFlowV2Classifier` for models of `keras` and `tensorflow.keras` with eager execution.

**Comment by beat-buesser** [comment]
If you add your model either to eihter ART's `KerasClassifier` or `TensorFlowV2Classifier` it will be compatible with all attacks of ART, including Zoo, Carlini&Wegner and JSM.
