### ISSUE TITLE
TensorFlowFasterRCNN's __init__() missing arg

### ISSUE THREAD

**Issue by lcadalzo** [Trusted-AI/adversarial-robustness-toolbox#950]
**Describe the bug**
The `__init__()` of the TensorFlowFasterRCNN model is missing the `model` arg when it calls `super().init()`, see [here](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/dev_1.6.0/art/estimators/object_detection/tensorflow_faster_rcnn.py#L108). This causes an error since `model` is now a required arg in the `BaseEstimator` class's `__init__()`, see [here](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/dev_1.6.0/art/estimators/estimator.py#L54), which was not the case in ART 1.4.2, see [here](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/1.4.2/art/estimators/estimator.py#L55). 

**Expected Behavior**
Instantiate the model without error. The model appeared to load ok after I added `model=model` to the call of `super().__init__()`, see first link above. E.g. `super().__init__(model=model, clip_values=clip_values, ...)`

**To Reproduce**
I'm attempting to load Armory's TensorFlowFasterRCNN baseline model, see [here](https://github.com/twosixlabs/armory/blob/v0.12.3/armory/baseline_models/tf_graph/mscoco_frcnn.py#L55-#L58). However, I would think that any instantiation of `TensorFlowFasterRCNN` would error since the `model` (optionally) passed [here](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/dev_1.6.0/art/estimators/object_detection/tensorflow_faster_rcnn.py#L55) isn't passed to the `super().__init__()` [here](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/dev_1.6.0/art/estimators/object_detection/tensorflow_faster_rcnn.py#L108), and the latter appears to now require a `model` arg.

**System information (please complete the following information):**
 I'm using the `dev_1.6.0` branch. This issue I imagine would go back to whenever `BaseEstimator`'s `__init__()` began to require a `model` arg, which appears to be ART 1.5.0.

**Comment by beat-buesser** [comment]
Hi @lcadalzo Thank you very much for reporting this issue, we'll fixx it as soon as possible.
