### ISSUE TITLE
Black-box classifier and Speech Recognition

### ISSUE THREAD

**Issue by scfang** [Trusted-AI/adversarial-robustness-toolbox#953]
Hello,

I was wondering if it is possible to use the black-box classifier wrapper class on a speech recognition estimator, namely the DeepSpeech PyTorch implementation in ART. I looked over the example found in the notebooks section, but I am a bit confused on how the pass in the number of nb_classes (prediction classes). In the example, the number of potential classifications is 10, but this value is hard to discern with speech recognition.

Moreover, I was also wondering if it was possible to apply other forms of attacks on the black-box classifier given that the only output is the classification. The example demonstrates an attack with HopSkipJump, but I am aiming to do a targeted attack on one of the ASR models. Can any of the attack methods in the toolbox help with my scenario?

Regards

**Comment by beat-buesser** [comment]
Hi @scfang Thank you very much for using ART! These are interesting questions.

Yes, `BlackBoxClassifier` is works only for classification tasks and attacks. However it should be easy to modify it for other tasks. Why would you like to use a black-box estimator instead of ART's `PyTorchDeepSpeech` estimator?

I think a bigger step would be a black-box attack on ASR, I don't think ART has at moment a black-box attack that would be ready for this task. So far we have been focusing on the white-box scenario in ASR.

**Comment by scfang** [comment]
Hi @beat-buesser, thank you for your reply.

I planned to use the BlackBoxClassifier for models other than DeepSpeech (namely online classifiers such as the one demonstrated in the notebook example). Part of my research involves exploring those types of attacks in the audio domain, so that's where the motivation lies.

I think my best bet would be to explore substitution model training. This paper offers a good idea on what I would like to attempt, although my bet is that the approach is not as straightforward as the paper makes it out to be:
https://www.mdpi.com/2076-3417/10/20/7168/htm

Regards

**Comment by beat-buesser** [comment]
Hi @scfang 

That sounds like an interesting and ambitious experiment. If you have a local substitution model for generating the adversarial examples, as in Figure 1, you would be able to abstract it with one of the ASR estimators in `art.estimators.speech_recognition` or adapt them to your substitution model. In that case you would be able to use white-box attacks like `ImperceptibleASR`/`ImperceptibleASRPyTorch` or `ProjectedGradientDescent` to generate the adversarial examples.
