### ISSUE TITLE
Bug in Pixel Attack and Threshold Attack.

### ISSUE THREAD

**Issue by shashankkotyan** [Trusted-AI/adversarial-robustness-toolbox#960]
When th=None (to find minimal perturbation), the generate function returns only adversarial images for th=1 and not for any other thresholds. 

The bug arises due to [line number 165](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/7c6326905aed874eed23e6c35c2965396bdf25ab/art/attacks/evasion/pixel_threshold.py#L165) in pixel_threshold.py file which forgets the 2nd best adversarial sample. 

Current Line 164-173

```
while True:
                    image_result: Union[List[np.ndarray], np.ndarray] = []      # BUG IN THIS LINE !!!
                    threshold = (start + end) // 2
                    success, trial_image_result = self._attack(image, target_class, threshold, max_iter)
                    if image_result or success:
                        image_result = trial_image_result
                    if success:
                        end = threshold - 1
                    else:
                        start = threshold + 1
```

Possible solution to the bug:

```
image_result: Union[List[np.ndarray], np.ndarray] = []
while True:
                    threshold = (start + end) // 2
                    success, trial_image_result = self._attack(image, target_class, threshold, max_iter)
                    if success:
                        image_result = trial_image_result
                        end = threshold - 1
                    else:
                        start = threshold + 1
```

**Comment by beat-buesser** [comment]
Hi @shashankkotyan Thank you very much for reporting this bug. Are you planning a pull request for this update?

**Comment by shashankkotyan** [comment]
I can open a pull request. Which branch should I use for the pull request?

**Comment by beat-buesser** [comment]
Hi @shashankkotyan That's great, thank you! Could you please target branch `dev_1.6.1`?
