### ISSUE TITLE
elastic net - low confidence adversarial examples

### ISSUE THREAD

**Issue by Stefan78** [Trusted-AI/adversarial-robustness-toolbox#966]
When performing elastic net attack, it seems that the parameter "confidence" is not used, so the attack does not return high confidence adversarial examples, even when one sets confidence to a high number.

**Comment by beat-buesser** [comment]
Hi @Stefan78 Thank you very much for using ART and reporting this issue! We will take a closer look as soon as possible.

**Comment by beat-buesser** [comment]
Hi @Stefan78 We have an update for `ElasticNet` on branch `fix_bug_cw` related to this issue. If your time allows, we would be very interested in your opinion to see if the attack works for you.
