### ISSUE TITLE
ZooAttack error against keras classifier

### ISSUE THREAD

**Issue by ivanv6** [Trusted-AI/adversarial-robustness-toolbox#974]
Dear all, i'm trying to implement a ZooAttack against a simple Keras classifier on the KDDCUP dataset. When i run the attack, it returns to me this error:

`Cannot take a larger sample than population when 'replace=False'`

How can i fix it? Thanks

**Comment by beat-buesser** [comment]
Hi @ivanv6 That's interesting, could you please share an example that reproduces this error message?

**Comment by albutko** [comment]
I was having the same error and  was able to fix the issue by setting the `nb_parallel` kwarg of `ZooAttack` to a number less than or equal to your feature dimension. The default value is 128, so in my case ZooAttack was trying to update 128 features in parallel when I only had 2 features to perturb. 

Try setting `nb_parallel=YOUR_FEATURE_DIM` when instantiating the attack.

**Comment by ivanv6** [comment]
Dear @albutko, thanks a lot. I fixed it in the same way. @beat-buesser congrats for this amazing tool!

**Comment by beat-buesser** [comment]
Thank you @albutko and @ivanv6, that's great!

I'll reopen this issue to add a check to `ZooAttack` in ART 1.6.1 to catch this case and log a better explanation.
