### ISSUE TITLE
TypeError: 'NoneType' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by MajidAkh** [Trusted-AI/adversarial-robustness-toolbox#975]
**Describe the bug**
I load my  XGBoost classifier named xgb_model train on tabular data.

As in the examples I import necessary library:

`from art.attacks.evasion import ZooAttack
from art.estimators.classification import XGBoostClassifier
import xgboost as xgb`

the I train the art classifier :

classifier = XGBoostClassifier(model=xgb_model,nb_classes=2)

Then when  i trie to create an attack object with 

attack= ZooAttack(classifier=classifier)

I got this typerror:

TypeError: 'NoneType' object cannot be interpreted as an integer 

It point the line 164 of zoo.py but can't figure out whats wrong..
![Capture d’écran (1)](https://user-images.githubusercontent.com/6216205/111461245-410b6800-871d-11eb-955b-f75ccdb9481e.png)

**Comment by beat-buesser** [comment]
Hi @MajidAkh Thank you for using ART! Could you please print the value of `model` in cell 130 and classifier in cell 132?

**Comment by MajidAkh** [comment]
Hello thank you for your answer in fact I figure out this issu and I am facing another one now.

When I use the method generate on my benign dataset it process normaly but I see no changes on the data set. 

As you can see the score is the same for the two data set.
![Capture d’écran (2)](https://user-images.githubusercontent.com/6216205/111700998-748fe480-883a-11eb-8102-7df68b5e8a17.png)

I think I miss something also I am working on tabular data.

**Comment by beat-buesser** [comment]
Can you describe the tabular dataset in more detail? What kind of features does it contain?

Did you notice that the default values `ZooAttack` are set to run the attack fast rather than strong? Did you experiment with the arguments of the attack?

**Comment by MajidAkh** [comment]
thank you for your answer.

The dataset is the 'Adult' dataset which has been preprocessing such that it contains only integer. The task is to perform a binary classification in order to predict instances which earn less or more than 50K.

No I do not experiment in fact I am reading your code and trying to understand it. What  arguments should I change according to you ?
