### ISSUE TITLE
why uap generated images are gray with divided by 9 net ?

### ISSUE THREAD

**Issue by luolugithub** [Trusted-AI/adversarial-robustness-toolbox#977]
universal_perturbation.py 
generate fun

**Expected behavior**

**Screenshots**

**System information (please complete the following information):**
 - OS
 - Python version
 - ART version or commit number
 - TensorFlow / Keras / PyTorch / MXNet version

**Comment by beat-buesser** [comment]
Hi @luolugithub I'm not sure if I understand the question.
