### ISSUE TITLE
Add support for sklearn 0.24

### ISSUE THREAD

**Issue by zacps** [Trusted-AI/adversarial-robustness-toolbox#985]
**Is your feature request related to a problem? Please describe.**
I need features available in sklearn >= 0.24, but art does not support it.

**Describe the solution you'd like**
For art to be tested on sklearn 0.24 and for it to be enabled in the `requirements.txt` version specification.

**Comment by beat-buesser** [comment]
Hi @zacps Thank you very much for this feature request. We will investigate it for the upcoming release of ART 1.6.1.

Have you already tested ART with sklearn >= 0.24?

**Comment by zacps** [comment]
Not to any significant extent.
