### ISSUE TITLE
Attacks on medical images

### ISSUE THREAD

**Issue by furkandurmus** [Trusted-AI/adversarial-robustness-toolbox#989]
Hello, I am new on adversarial attacks, I checked nearly all the examples. Especially Mnist examples look super easy to apply. However, I want to attack some segmentation models for medical images. I just cannot figure out where to start, how can I apply ART for more complex models? If a model is written in pytorch should I have to use ART's pytorch wrappers? Thanks.

**Comment by beat-buesser** [comment]
Hi @furkandurmus 

Thank you for exploring ART! I think this should be possible, although currently you would have to adapt or implement an new estimator for the segmentation model by following the estimators for classification or object detection. Estimators for object segmentation is on our list of features we would like to support in future releases.
