### ISSUE TITLE
Got ValueError again while using SimBA

### ISSUE THREAD

**Issue by Code-Ranger** [Trusted-AI/adversarial-robustness-toolbox#998]
Hi,
Event though with the dicusssion in #924, I still got ValueError by using the parameters you recommended (max_iter = 500, freq_dim = 28, order = "random", stride = 4, epsilon = 25)

Please find the belowing my code, I have change the retun of predict() from logits to probabilities.
BTW, if I change the parameters to max_iter = 500, freq_dim = 28, order = "random", stride = 1, epsilon = 25, the following code can run without error, but the SimBA seems not working, i.e., the result image can still be correctly classified by ResNet-50.

```
def predict(x):
    x = np.array(x[0])
    # convert np array back to image
    img = Image.fromarray(x.astype(np.uint8)).convert('RGB')

    # preprocess then inference
    img_t = preprocess(img)
    batch_t = torch.unsqueeze(img_t, 0)
    resnet.eval()
    logits= resnet(batch_t)

    probability = torch.softmax(input=logits, dim=1)
    return probability.detach().numpy()


classifier = BlackBoxClassifierNeuralNetwork(predict, image_array[0].shape, 1000, channels_first=False, clip_values=(0, 255))

# Generate SimBA attack
attack = SimBA(classifier=classifier, max_iter=500, freq_dim=28, order='random', stride=4, epsilon=25.5)
x_adv = attack.generate(x=np.array([origin_image]))

prediction = str(np.argmax(predict(x_adv)))
print("L2 error: ", np.linalg.norm(np.reshape(x_adv[0] - origin_image, [-1])),
      "and class label is %s " % prediction, str(classes[prediction]))
```

Then I got the Error as following,

Traceback (most recent call last):
  File "/home/ranger/lizhu/home/ranger/lizhu/src/terminal/generate_adv_example.py", line 119, in <module>
    x_adv = attack.generate(x=np.array([origin_image]))
  File "/home/ranger/tools/anaconda/lib/python3.8/site-packages/art/attacks/attack.py", line 74, in replacement_function
    return fdict[func_name](self, *args, **kwargs)
  File "/home/ranger/tools/anaconda/lib/python3.8/site-packages/art/attacks/evasion/simba.py", line 139, in generate
    indices = self._block_order(x.shape[2], nb_channels, initial_size=self.freq_dim, stride=self.stride)[
  File "/home/ranger/tools/anaconda/lib/python3.8/site-packages/art/attacks/evasion/simba.py", line 306, in _block_order
    order[:, : (i + stride), i : (i + stride)] = perm[:num_first].reshape((channels, -1, stride))
ValueError: could not broadcast input array from shape (3,300,4) into shape (3,299,3)

**Comment by beat-buesser** [comment]
Hi @Code-Ranger I'm not able to reproduce this issue. Could you please share the shape of `origin_image` just before this line `x_adv = attack.generate(x=np.array([origin_image]))`?

**Comment by Code-Ranger** [comment]
The shape of origin_image is (299, 299,3)
The image is this one 
![koala](https://user-images.githubusercontent.com/13929749/112706106-081d8100-8edd-11eb-8d15-2575c84311f7.jpg)

**Comment by beat-buesser** [comment]
Hi @Code-Ranger The shape of `x` in `x_adv = attack.generate(x=np.array([origin_image]))` should be either of format NHWC or NCHW, your input is missing the batch dimension N, for a single image `origin_image` should have shape (1, 299, 299, 3)

**Comment by Code-Ranger** [comment]
Hi @beat-buesser 
Thanks for supporting。
I have changed the code to 
    ```x_adv = attack.generate(x=np.array(image_array))```
where image_array = np.array([np.array(origin_image, dtype='float32')]), therefore the shape of x is (1, 299, 299, 3) now.
But I still got error prompt as following,

Traceback (most recent call last):
  File "/home/ranger/.pycharm_helpers/pydev/pydevd.py", line 1438, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/ranger/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/ranger/lizhu/home/ranger/lizhu/src/detection/generate_adv_examples.py", line 123, in <module>
    x_adv = attack.generate(x=np.array(image_array))
  File "/home/ranger/tools/anaconda/lib/python3.8/site-packages/art/attacks/attack.py", line 74, in replacement_function
    return fdict[func_name](self, *args, **kwargs)
  File "/home/ranger/tools/anaconda/lib/python3.8/site-packages/art/attacks/evasion/simba.py", line 139, in generate
    indices = self._block_order(x.shape[2], nb_channels, initial_size=self.freq_dim, stride=self.stride)[
  File "/home/ranger/tools/anaconda/lib/python3.8/site-packages/art/attacks/evasion/simba.py", line 306, in _block_order
    order[:, : (i + stride), i : (i + stride)] = perm[:num_first].reshape((channels, -1, stride))
ValueError: could not broadcast input array from shape (3,300,4) into shape (3,299,3)

**Comment by beat-buesser** [comment]
Hi @Code-Ranger The possible values for `freq_dim` and `stride` depend on the input image size, more values should be possible if you scale the image to 224 (where the recommended values in #924 are working) or 300. For a size of 299 the `values iter_ = 5000, freq_dim = 13, order = "random", stride = 11` seem to work.

**Comment by Code-Ranger** [comment]
Hi @beat-buesser , with the parameters (values iter_ = 5000, freq_dim = 13, order = "random", stride = 11) you recommended, I finally got the SimBA working (have to set the epsilon=100).
Thanks very much for your supporting. :)

**Comment by Code-Ranger** [comment]
Hi @beat-buesser ，
Yes, some documentation will be helpful for explaining how to use the different attacking methods. THX

**Comment by beat-buesser** [comment]
Hi @Code-Ranger

I have added a check to `SimBA`. This condition defines valid combinations of `stride` and `freq_dim` as function of image size: divmod(image_size - freq_dim, stride)[1] == 0
