### ISSUE TITLE
BlackBoxClassifierNeuralNetwork 1.6.0 TypeError: abstract methods compute_loss

### ISSUE THREAD

**Issue by jgc128** [Trusted-AI/adversarial-robustness-toolbox#999]
**Describe the bug**
It seems like BlackBoxClassifierNeuralNetwork cannot be instantiated in ART 1.6.0. The same code works fine in 1.5.2

**To Reproduce**
```
from art.estimators.classification import BlackBoxClassifierNeuralNetwork
predict = lambda x: x    
classifier = BlackBoxClassifierNeuralNetwork(predict, (224, 224, 3), 1000, channels_first=False, clip_values=(0, 255))
```
The code above gives the following error:
`TypeError: Can't instantiate abstract class BlackBoxClassifierNeuralNetwork with abstract methods compute_loss`

The same code work without any problems with ART 1.5.2

**Expected behavior**
Classifier is instantiated

**System information (please complete the following information):**
 - Ubuntu 
 - Python 3.7.9
 - ART 1.6.0

**Comment by beat-buesser** [comment]
Hi @jgc128 Thank you very much for reporting this issue! We have an update on branch `development_maintenance_161` which should fix this issue. We'll merge it soon and release with ART 1.6.1.

Does the updated version on `development_maintenance_161` work for you?

**Comment by jgc128** [comment]
Yeah, this branch works! Thanks!
